// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.31.0
// source: hub_client.proto

package hub_client

import (
	hub_node "github.com/nanoping-labs/nanoping-api-go/v11/hub_node"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Connection state between a node and its hub server.
type ConnectionState int32

const (
	// The node is not authenticated with a hub server.
	ConnectionState_UNAUTHENTICATED ConnectionState = 0
	// The node is authenticated but not connected to the hub server.
	ConnectionState_DISCONNECTED ConnectionState = 1
	// The node is connected to the hub server.
	ConnectionState_CONNECTED ConnectionState = 2
)

// Enum value maps for ConnectionState.
var (
	ConnectionState_name = map[int32]string{
		0: "UNAUTHENTICATED",
		1: "DISCONNECTED",
		2: "CONNECTED",
	}
	ConnectionState_value = map[string]int32{
		"UNAUTHENTICATED": 0,
		"DISCONNECTED":    1,
		"CONNECTED":       2,
	}
)

func (x ConnectionState) Enum() *ConnectionState {
	p := new(ConnectionState)
	*p = x
	return p
}

func (x ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_client_proto_enumTypes[0].Descriptor()
}

func (ConnectionState) Type() protoreflect.EnumType {
	return &file_hub_client_proto_enumTypes[0]
}

func (x ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionState.Descriptor instead.
func (ConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{0}
}

// Request for getLocalNodeId.
type GetLocalNodeIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocalNodeIdRequest) Reset() {
	*x = GetLocalNodeIdRequest{}
	mi := &file_hub_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocalNodeIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocalNodeIdRequest) ProtoMessage() {}

func (x *GetLocalNodeIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocalNodeIdRequest.ProtoReflect.Descriptor instead.
func (*GetLocalNodeIdRequest) Descriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{0}
}

// Response for getLocalNodeId.
type GetLocalNodeIdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the node hosting the API.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// True if the node holds a sign-in to a hub server. It may still be disconnected from it at the moment.
	IsAuthenticated bool `protobuf:"varint,2,opt,name=is_authenticated,json=isAuthenticated,proto3" json:"is_authenticated,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLocalNodeIdResponse) Reset() {
	*x = GetLocalNodeIdResponse{}
	mi := &file_hub_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocalNodeIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocalNodeIdResponse) ProtoMessage() {}

func (x *GetLocalNodeIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocalNodeIdResponse.ProtoReflect.Descriptor instead.
func (*GetLocalNodeIdResponse) Descriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{1}
}

func (x *GetLocalNodeIdResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetLocalNodeIdResponse) GetIsAuthenticated() bool {
	if x != nil {
		return x.IsAuthenticated
	}
	return false
}

// Request for getNode.
type GetNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the node to get information about, for example the id returned by getLocalNodeId.
	NodeId        string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_hub_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{2}
}

func (x *GetNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// Response for getNode.
type GetNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information about the node.
	Node          *hub_node.Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_hub_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{3}
}

func (x *GetNodeResponse) GetNode() *hub_node.Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// Request for setNode.
type SetNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the node to change.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// New name of the node. Example: `edge-node-1`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// New metadata of the node. Replaces all existing metadata, so leaving it empty removes the metadata.
	Metadata      *hub_node.NodeMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNodeRequest) Reset() {
	*x = SetNodeRequest{}
	mi := &file_hub_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeRequest) ProtoMessage() {}

func (x *SetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeRequest.ProtoReflect.Descriptor instead.
func (*SetNodeRequest) Descriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{4}
}

func (x *SetNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SetNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetNodeRequest) GetMetadata() *hub_node.NodeMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response for setNode.
type SetNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node information after the change.
	Node          *hub_node.Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNodeResponse) Reset() {
	*x = SetNodeResponse{}
	mi := &file_hub_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeResponse) ProtoMessage() {}

func (x *SetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeResponse.ProtoReflect.Descriptor instead.
func (*SetNodeResponse) Descriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{5}
}

func (x *SetNodeResponse) GetNode() *hub_node.Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// Request for authenticateByRequest.
type AuthenticateByRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP or HTTPS address of the hub server. Example: `http://127.0.0.1:8769`
	HubServerAddress string `protobuf:"bytes,1,opt,name=hub_server_address,json=hubServerAddress,proto3" json:"hub_server_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthenticateByRequestRequest) Reset() {
	*x = AuthenticateByRequestRequest{}
	mi := &file_hub_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateByRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateByRequestRequest) ProtoMessage() {}

func (x *AuthenticateByRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateByRequestRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateByRequestRequest) Descriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{6}
}

func (x *AuthenticateByRequestRequest) GetHubServerAddress() string {
	if x != nil {
		return x.HubServerAddress
	}
	return ""
}

// Response for authenticateByRequest. Empty on success.
type AuthenticateByRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateByRequestResponse) Reset() {
	*x = AuthenticateByRequestResponse{}
	mi := &file_hub_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateByRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateByRequestResponse) ProtoMessage() {}

func (x *AuthenticateByRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateByRequestResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateByRequestResponse) Descriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{7}
}

// Request for disconnect.
type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_hub_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{8}
}

// Response for disconnect.
type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_hub_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{9}
}

// Request for streamConnectionState.
type StreamConnectionStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamConnectionStateRequest) Reset() {
	*x = StreamConnectionStateRequest{}
	mi := &file_hub_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConnectionStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConnectionStateRequest) ProtoMessage() {}

func (x *StreamConnectionStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConnectionStateRequest.ProtoReflect.Descriptor instead.
func (*StreamConnectionStateRequest) Descriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{10}
}

// A connection state update.
type StreamConnectionStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current connection state.
	State         ConnectionState `protobuf:"varint,1,opt,name=state,proto3,enum=nanopinggrpc.hub.ConnectionState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamConnectionStateResponse) Reset() {
	*x = StreamConnectionStateResponse{}
	mi := &file_hub_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConnectionStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConnectionStateResponse) ProtoMessage() {}

func (x *StreamConnectionStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConnectionStateResponse.ProtoReflect.Descriptor instead.
func (*StreamConnectionStateResponse) Descriptor() ([]byte, []int) {
	return file_hub_client_proto_rawDescGZIP(), []int{11}
}

func (x *StreamConnectionStateResponse) GetState() ConnectionState {
	if x != nil {
		return x.State
	}
	return ConnectionState_UNAUTHENTICATED
}

var File_hub_client_proto protoreflect.FileDescriptor

var file_hub_client_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x68, 0x75, 0x62, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x68, 0x75, 0x62, 0x1a, 0x0e, 0x68, 0x75, 0x62, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5c, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x29, 0x0a, 0x10, 0x69, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x22, 0x29, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69,
	0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x79, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e,
	0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x3d, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22,
	0x4c, 0x0a, 0x1c, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x42,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2c, 0x0a, 0x12, 0x68, 0x75, 0x62, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x68, 0x75, 0x62,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x1f, 0x0a,
	0x1d, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x42, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13,
	0x0a, 0x11, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x58, 0x0a, 0x1d, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6e, 0x61, 0x6e, 0x6f,
	0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2a, 0x47, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48,
	0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x44,
	0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x32, 0xf2, 0x04, 0x0a,
	0x10, 0x48, 0x75, 0x62, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x65, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x12, 0x27, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6e,
	0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x20, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x07, 0x73, 0x65,
	0x74, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69,
	0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7a, 0x0a, 0x15,
	0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x42, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x42, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x42, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x23, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e,
	0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6e, 0x61,
	0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x7c, 0x0a, 0x15, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x2e, 0x6e,
	0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6e,
	0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x1a, 0x5a, 0x18, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x68, 0x75, 0x62, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_hub_client_proto_rawDescOnce sync.Once
	file_hub_client_proto_rawDescData []byte
)

func file_hub_client_proto_rawDescGZIP() []byte {
	file_hub_client_proto_rawDescOnce.Do(func() {
		file_hub_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_client_proto_rawDesc), len(file_hub_client_proto_rawDesc)))
	})
	return file_hub_client_proto_rawDescData
}

var file_hub_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hub_client_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_hub_client_proto_goTypes = []any{
	(ConnectionState)(0),                  // 0: nanopinggrpc.hub.ConnectionState
	(*GetLocalNodeIdRequest)(nil),         // 1: nanopinggrpc.hub.GetLocalNodeIdRequest
	(*GetLocalNodeIdResponse)(nil),        // 2: nanopinggrpc.hub.GetLocalNodeIdResponse
	(*GetNodeRequest)(nil),                // 3: nanopinggrpc.hub.GetNodeRequest
	(*GetNodeResponse)(nil),               // 4: nanopinggrpc.hub.GetNodeResponse
	(*SetNodeRequest)(nil),                // 5: nanopinggrpc.hub.SetNodeRequest
	(*SetNodeResponse)(nil),               // 6: nanopinggrpc.hub.SetNodeResponse
	(*AuthenticateByRequestRequest)(nil),  // 7: nanopinggrpc.hub.AuthenticateByRequestRequest
	(*AuthenticateByRequestResponse)(nil), // 8: nanopinggrpc.hub.AuthenticateByRequestResponse
	(*DisconnectRequest)(nil),             // 9: nanopinggrpc.hub.DisconnectRequest
	(*DisconnectResponse)(nil),            // 10: nanopinggrpc.hub.DisconnectResponse
	(*StreamConnectionStateRequest)(nil),  // 11: nanopinggrpc.hub.StreamConnectionStateRequest
	(*StreamConnectionStateResponse)(nil), // 12: nanopinggrpc.hub.StreamConnectionStateResponse
	(*hub_node.Node)(nil),                 // 13: nanopinggrpc.hub.Node
	(*hub_node.NodeMetadata)(nil),         // 14: nanopinggrpc.hub.NodeMetadata
}
var file_hub_client_proto_depIdxs = []int32{
	13, // 0: nanopinggrpc.hub.GetNodeResponse.node:type_name -> nanopinggrpc.hub.Node
	14, // 1: nanopinggrpc.hub.SetNodeRequest.metadata:type_name -> nanopinggrpc.hub.NodeMetadata
	13, // 2: nanopinggrpc.hub.SetNodeResponse.node:type_name -> nanopinggrpc.hub.Node
	0,  // 3: nanopinggrpc.hub.StreamConnectionStateResponse.state:type_name -> nanopinggrpc.hub.ConnectionState
	1,  // 4: nanopinggrpc.hub.HubClientService.getLocalNodeId:input_type -> nanopinggrpc.hub.GetLocalNodeIdRequest
	3,  // 5: nanopinggrpc.hub.HubClientService.getNode:input_type -> nanopinggrpc.hub.GetNodeRequest
	5,  // 6: nanopinggrpc.hub.HubClientService.setNode:input_type -> nanopinggrpc.hub.SetNodeRequest
	7,  // 7: nanopinggrpc.hub.HubClientService.authenticateByRequest:input_type -> nanopinggrpc.hub.AuthenticateByRequestRequest
	9,  // 8: nanopinggrpc.hub.HubClientService.disconnect:input_type -> nanopinggrpc.hub.DisconnectRequest
	11, // 9: nanopinggrpc.hub.HubClientService.streamConnectionState:input_type -> nanopinggrpc.hub.StreamConnectionStateRequest
	2,  // 10: nanopinggrpc.hub.HubClientService.getLocalNodeId:output_type -> nanopinggrpc.hub.GetLocalNodeIdResponse
	4,  // 11: nanopinggrpc.hub.HubClientService.getNode:output_type -> nanopinggrpc.hub.GetNodeResponse
	6,  // 12: nanopinggrpc.hub.HubClientService.setNode:output_type -> nanopinggrpc.hub.SetNodeResponse
	8,  // 13: nanopinggrpc.hub.HubClientService.authenticateByRequest:output_type -> nanopinggrpc.hub.AuthenticateByRequestResponse
	10, // 14: nanopinggrpc.hub.HubClientService.disconnect:output_type -> nanopinggrpc.hub.DisconnectResponse
	12, // 15: nanopinggrpc.hub.HubClientService.streamConnectionState:output_type -> nanopinggrpc.hub.StreamConnectionStateResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_hub_client_proto_init() }
func file_hub_client_proto_init() {
	if File_hub_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_client_proto_rawDesc), len(file_hub_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_client_proto_goTypes,
		DependencyIndexes: file_hub_client_proto_depIdxs,
		EnumInfos:         file_hub_client_proto_enumTypes,
		MessageInfos:      file_hub_client_proto_msgTypes,
	}.Build()
	File_hub_client_proto = out.File
	file_hub_client_proto_goTypes = nil
	file_hub_client_proto_depIdxs = nil
}
