// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: hub_client.proto

package hub_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HubClientService_GetLocalNodeId_FullMethodName        = "/nanopinggrpc.hub.HubClientService/getLocalNodeId"
	HubClientService_GetNode_FullMethodName               = "/nanopinggrpc.hub.HubClientService/getNode"
	HubClientService_SetNode_FullMethodName               = "/nanopinggrpc.hub.HubClientService/setNode"
	HubClientService_AuthenticateByRequest_FullMethodName = "/nanopinggrpc.hub.HubClientService/authenticateByRequest"
	HubClientService_Disconnect_FullMethodName            = "/nanopinggrpc.hub.HubClientService/disconnect"
	HubClientService_StreamConnectionState_FullMethodName = "/nanopinggrpc.hub.HubClientService/streamConnectionState"
)

// HubClientServiceClient is the client API for HubClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The hub client is the part of every node that connects it to a hub server, the control plane that lets connected
// nodes find and manage each other. Use this service to sign the node hosting the API in to a hub server, disconnect
// it, follow its connection state, and read or change the details of nodes.
type HubClientServiceClient interface {
	// Get the ID of the node hosting the API, and whether it is authenticated with a hub server.
	GetLocalNodeId(ctx context.Context, in *GetLocalNodeIdRequest, opts ...grpc.CallOption) (*GetLocalNodeIdResponse, error)
	// Get the details of a node. Fails with Unavailable when the node cannot be reached.
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// Change the details of a node, replacing the current values. Fails with PermissionDenied when the node's
	// configuration comes from a config file.
	SetNode(ctx context.Context, in *SetNodeRequest, opts ...grpc.CallOption) (*SetNodeResponse, error)
	// Ask a hub server to authenticate the node hosting the API, and wait for the hub server to accept or reject the
	// request. On success the node stays authenticated, also after a restart. Fails with AlreadyExists if the node is
	// already authenticated, Unauthenticated if the request was rejected, DeadlineExceeded if the hub server did not
	// answer in time, Unavailable if the hub server could not be reached, and NotFound if the hub server does not accept
	// authentication by request.
	AuthenticateByRequest(ctx context.Context, in *AuthenticateByRequestRequest, opts ...grpc.CallOption) (*AuthenticateByRequestResponse, error)
	// Disconnect the node hosting the API from its hub server. The node always leaves, even if the hub server could not
	// remove it from its list of nodes.
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	// Stream the connection state between the node hosting the API and its hub server. The current state is sent first,
	// then a new message every time the state changes. The stream stays open until the caller closes it.
	StreamConnectionState(ctx context.Context, in *StreamConnectionStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamConnectionStateResponse], error)
}

type hubClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHubClientServiceClient(cc grpc.ClientConnInterface) HubClientServiceClient {
	return &hubClientServiceClient{cc}
}

func (c *hubClientServiceClient) GetLocalNodeId(ctx context.Context, in *GetLocalNodeIdRequest, opts ...grpc.CallOption) (*GetLocalNodeIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocalNodeIdResponse)
	err := c.cc.Invoke(ctx, HubClientService_GetLocalNodeId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubClientServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, HubClientService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubClientServiceClient) SetNode(ctx context.Context, in *SetNodeRequest, opts ...grpc.CallOption) (*SetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNodeResponse)
	err := c.cc.Invoke(ctx, HubClientService_SetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubClientServiceClient) AuthenticateByRequest(ctx context.Context, in *AuthenticateByRequestRequest, opts ...grpc.CallOption) (*AuthenticateByRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateByRequestResponse)
	err := c.cc.Invoke(ctx, HubClientService_AuthenticateByRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubClientServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, HubClientService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubClientServiceClient) StreamConnectionState(ctx context.Context, in *StreamConnectionStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamConnectionStateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubClientService_ServiceDesc.Streams[0], HubClientService_StreamConnectionState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConnectionStateRequest, StreamConnectionStateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubClientService_StreamConnectionStateClient = grpc.ServerStreamingClient[StreamConnectionStateResponse]

// HubClientServiceServer is the server API for HubClientService service.
// All implementations must embed UnimplementedHubClientServiceServer
// for forward compatibility.
//
// The hub client is the part of every node that connects it to a hub server, the control plane that lets connected
// nodes find and manage each other. Use this service to sign the node hosting the API in to a hub server, disconnect
// it, follow its connection state, and read or change the details of nodes.
type HubClientServiceServer interface {
	// Get the ID of the node hosting the API, and whether it is authenticated with a hub server.
	GetLocalNodeId(context.Context, *GetLocalNodeIdRequest) (*GetLocalNodeIdResponse, error)
	// Get the details of a node. Fails with Unavailable when the node cannot be reached.
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// Change the details of a node, replacing the current values. Fails with PermissionDenied when the node's
	// configuration comes from a config file.
	SetNode(context.Context, *SetNodeRequest) (*SetNodeResponse, error)
	// Ask a hub server to authenticate the node hosting the API, and wait for the hub server to accept or reject the
	// request. On success the node stays authenticated, also after a restart. Fails with AlreadyExists if the node is
	// already authenticated, Unauthenticated if the request was rejected, DeadlineExceeded if the hub server did not
	// answer in time, Unavailable if the hub server could not be reached, and NotFound if the hub server does not accept
	// authentication by request.
	AuthenticateByRequest(context.Context, *AuthenticateByRequestRequest) (*AuthenticateByRequestResponse, error)
	// Disconnect the node hosting the API from its hub server. The node always leaves, even if the hub server could not
	// remove it from its list of nodes.
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	// Stream the connection state between the node hosting the API and its hub server. The current state is sent first,
	// then a new message every time the state changes. The stream stays open until the caller closes it.
	StreamConnectionState(*StreamConnectionStateRequest, grpc.ServerStreamingServer[StreamConnectionStateResponse]) error
	mustEmbedUnimplementedHubClientServiceServer()
}

// UnimplementedHubClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHubClientServiceServer struct{}

func (UnimplementedHubClientServiceServer) GetLocalNodeId(context.Context, *GetLocalNodeIdRequest) (*GetLocalNodeIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocalNodeId not implemented")
}
func (UnimplementedHubClientServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedHubClientServiceServer) SetNode(context.Context, *SetNodeRequest) (*SetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNode not implemented")
}
func (UnimplementedHubClientServiceServer) AuthenticateByRequest(context.Context, *AuthenticateByRequestRequest) (*AuthenticateByRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateByRequest not implemented")
}
func (UnimplementedHubClientServiceServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedHubClientServiceServer) StreamConnectionState(*StreamConnectionStateRequest, grpc.ServerStreamingServer[StreamConnectionStateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamConnectionState not implemented")
}
func (UnimplementedHubClientServiceServer) mustEmbedUnimplementedHubClientServiceServer() {}
func (UnimplementedHubClientServiceServer) testEmbeddedByValue()                          {}

// UnsafeHubClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubClientServiceServer will
// result in compilation errors.
type UnsafeHubClientServiceServer interface {
	mustEmbedUnimplementedHubClientServiceServer()
}

func RegisterHubClientServiceServer(s grpc.ServiceRegistrar, srv HubClientServiceServer) {
	// If the following call pancis, it indicates UnimplementedHubClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HubClientService_ServiceDesc, srv)
}

func _HubClientService_GetLocalNodeId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocalNodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubClientServiceServer).GetLocalNodeId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubClientService_GetLocalNodeId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubClientServiceServer).GetLocalNodeId(ctx, req.(*GetLocalNodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubClientService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubClientServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubClientService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubClientServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubClientService_SetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubClientServiceServer).SetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubClientService_SetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubClientServiceServer).SetNode(ctx, req.(*SetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubClientService_AuthenticateByRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateByRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubClientServiceServer).AuthenticateByRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubClientService_AuthenticateByRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubClientServiceServer).AuthenticateByRequest(ctx, req.(*AuthenticateByRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubClientService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubClientServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubClientService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubClientServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubClientService_StreamConnectionState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamConnectionStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubClientServiceServer).StreamConnectionState(m, &grpc.GenericServerStream[StreamConnectionStateRequest, StreamConnectionStateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubClientService_StreamConnectionStateServer = grpc.ServerStreamingServer[StreamConnectionStateResponse]

// HubClientService_ServiceDesc is the grpc.ServiceDesc for HubClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanopinggrpc.hub.HubClientService",
	HandlerType: (*HubClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getLocalNodeId",
			Handler:    _HubClientService_GetLocalNodeId_Handler,
		},
		{
			MethodName: "getNode",
			Handler:    _HubClientService_GetNode_Handler,
		},
		{
			MethodName: "setNode",
			Handler:    _HubClientService_SetNode_Handler,
		},
		{
			MethodName: "authenticateByRequest",
			Handler:    _HubClientService_AuthenticateByRequest_Handler,
		},
		{
			MethodName: "disconnect",
			Handler:    _HubClientService_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamConnectionState",
			Handler:       _HubClientService_StreamConnectionState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hub_client.proto",
}
