// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: network_instances.proto

package networks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkInstances_GetNetworkInstances_FullMethodName    = "/nanopinggrpc.networks.NetworkInstances/getNetworkInstances"
	NetworkInstances_StreamNetworkInstances_FullMethodName = "/nanopinggrpc.networks.NetworkInstances/streamNetworkInstances"
	NetworkInstances_GetNetworkPipelines_FullMethodName    = "/nanopinggrpc.networks.NetworkInstances/getNetworkPipelines"
	NetworkInstances_StreamNetworkPipelines_FullMethodName = "/nanopinggrpc.networks.NetworkInstances/streamNetworkPipelines"
	NetworkInstances_ToggleNetworkPipeline_FullMethodName  = "/nanopinggrpc.networks.NetworkInstances/toggleNetworkPipeline"
	NetworkInstances_OpenLogStream_FullMethodName          = "/nanopinggrpc.networks.NetworkInstances/openLogStream"
)

// NetworkInstancesClient is the client API for NetworkInstances service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A network instance is a network's presence on one node: the pipelines generated for that node from the network's
// blueprints. Instances are created, updated and removed automatically when their network changes, so they cannot be
// managed directly. Use this service to see which networks a node takes part in, follow its network pipelines, turn
// them on or off, and read their logs. The node needs pipelines enabled.
type NetworkInstancesClient interface {
	// Get all network instances on a node, each with its pipelines.
	GetNetworkInstances(ctx context.Context, in *GetNetworkInstancesRequest, opts ...grpc.CallOption) (*GetNetworkInstancesResponse, error)
	// Stream changes to the network instances on a node. Nothing is sent when the stream opens; an event is sent each
	// time an instance is created, updated or deleted, and an update is also sent when one of its pipelines changes.
	// The stream ends if the connection to the node is lost.
	StreamNetworkInstances(ctx context.Context, in *StreamNetworkInstancesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamNetworkInstanceEvent], error)
	// Get the network instance pipelines on a node, optionally filtered. A pipeline must match every filter that is set.
	GetNetworkPipelines(ctx context.Context, in *GetNetworkPipelinesRequest, opts ...grpc.CallOption) (*GetNetworkPipelinesResponse, error)
	// Stream changes to the network instance pipelines on a node. Nothing is sent when the stream opens; an event is
	// sent each time a pipeline is created, updated or deleted. The stream ends if the connection to the node is lost.
	StreamNetworkPipelines(ctx context.Context, in *StreamNetworkPipelinesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamNetworkPipelineEvent], error)
	// Enable or disable a network instance pipeline on a node, which starts or stops the pipeline. Each call flips the
	// current state. Fails with a not found error if no matching pipeline exists.
	ToggleNetworkPipeline(ctx context.Context, in *ToggleNetworkPipelineRequest, opts ...grpc.CallOption) (*ToggleNetworkPipelineResponse, error)
	// Stream the log messages of a network instance on a node. The requested number of past lines is sent first, then
	// new messages as they are logged, until the connection to the node is lost.
	OpenLogStream(ctx context.Context, in *OpenNetworkInstanceLogStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetworkInstanceLogStreamMessages], error)
}

type networkInstancesClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkInstancesClient(cc grpc.ClientConnInterface) NetworkInstancesClient {
	return &networkInstancesClient{cc}
}

func (c *networkInstancesClient) GetNetworkInstances(ctx context.Context, in *GetNetworkInstancesRequest, opts ...grpc.CallOption) (*GetNetworkInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkInstancesResponse)
	err := c.cc.Invoke(ctx, NetworkInstances_GetNetworkInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkInstancesClient) StreamNetworkInstances(ctx context.Context, in *StreamNetworkInstancesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamNetworkInstanceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkInstances_ServiceDesc.Streams[0], NetworkInstances_StreamNetworkInstances_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamNetworkInstancesRequest, StreamNetworkInstanceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkInstances_StreamNetworkInstancesClient = grpc.ServerStreamingClient[StreamNetworkInstanceEvent]

func (c *networkInstancesClient) GetNetworkPipelines(ctx context.Context, in *GetNetworkPipelinesRequest, opts ...grpc.CallOption) (*GetNetworkPipelinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkPipelinesResponse)
	err := c.cc.Invoke(ctx, NetworkInstances_GetNetworkPipelines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkInstancesClient) StreamNetworkPipelines(ctx context.Context, in *StreamNetworkPipelinesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamNetworkPipelineEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkInstances_ServiceDesc.Streams[1], NetworkInstances_StreamNetworkPipelines_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamNetworkPipelinesRequest, StreamNetworkPipelineEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkInstances_StreamNetworkPipelinesClient = grpc.ServerStreamingClient[StreamNetworkPipelineEvent]

func (c *networkInstancesClient) ToggleNetworkPipeline(ctx context.Context, in *ToggleNetworkPipelineRequest, opts ...grpc.CallOption) (*ToggleNetworkPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleNetworkPipelineResponse)
	err := c.cc.Invoke(ctx, NetworkInstances_ToggleNetworkPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkInstancesClient) OpenLogStream(ctx context.Context, in *OpenNetworkInstanceLogStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetworkInstanceLogStreamMessages], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkInstances_ServiceDesc.Streams[2], NetworkInstances_OpenLogStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenNetworkInstanceLogStreamRequest, NetworkInstanceLogStreamMessages]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkInstances_OpenLogStreamClient = grpc.ServerStreamingClient[NetworkInstanceLogStreamMessages]

// NetworkInstancesServer is the server API for NetworkInstances service.
// All implementations must embed UnimplementedNetworkInstancesServer
// for forward compatibility.
//
// A network instance is a network's presence on one node: the pipelines generated for that node from the network's
// blueprints. Instances are created, updated and removed automatically when their network changes, so they cannot be
// managed directly. Use this service to see which networks a node takes part in, follow its network pipelines, turn
// them on or off, and read their logs. The node needs pipelines enabled.
type NetworkInstancesServer interface {
	// Get all network instances on a node, each with its pipelines.
	GetNetworkInstances(context.Context, *GetNetworkInstancesRequest) (*GetNetworkInstancesResponse, error)
	// Stream changes to the network instances on a node. Nothing is sent when the stream opens; an event is sent each
	// time an instance is created, updated or deleted, and an update is also sent when one of its pipelines changes.
	// The stream ends if the connection to the node is lost.
	StreamNetworkInstances(*StreamNetworkInstancesRequest, grpc.ServerStreamingServer[StreamNetworkInstanceEvent]) error
	// Get the network instance pipelines on a node, optionally filtered. A pipeline must match every filter that is set.
	GetNetworkPipelines(context.Context, *GetNetworkPipelinesRequest) (*GetNetworkPipelinesResponse, error)
	// Stream changes to the network instance pipelines on a node. Nothing is sent when the stream opens; an event is
	// sent each time a pipeline is created, updated or deleted. The stream ends if the connection to the node is lost.
	StreamNetworkPipelines(*StreamNetworkPipelinesRequest, grpc.ServerStreamingServer[StreamNetworkPipelineEvent]) error
	// Enable or disable a network instance pipeline on a node, which starts or stops the pipeline. Each call flips the
	// current state. Fails with a not found error if no matching pipeline exists.
	ToggleNetworkPipeline(context.Context, *ToggleNetworkPipelineRequest) (*ToggleNetworkPipelineResponse, error)
	// Stream the log messages of a network instance on a node. The requested number of past lines is sent first, then
	// new messages as they are logged, until the connection to the node is lost.
	OpenLogStream(*OpenNetworkInstanceLogStreamRequest, grpc.ServerStreamingServer[NetworkInstanceLogStreamMessages]) error
	mustEmbedUnimplementedNetworkInstancesServer()
}

// UnimplementedNetworkInstancesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkInstancesServer struct{}

func (UnimplementedNetworkInstancesServer) GetNetworkInstances(context.Context, *GetNetworkInstancesRequest) (*GetNetworkInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetworkInstances not implemented")
}
func (UnimplementedNetworkInstancesServer) StreamNetworkInstances(*StreamNetworkInstancesRequest, grpc.ServerStreamingServer[StreamNetworkInstanceEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamNetworkInstances not implemented")
}
func (UnimplementedNetworkInstancesServer) GetNetworkPipelines(context.Context, *GetNetworkPipelinesRequest) (*GetNetworkPipelinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetworkPipelines not implemented")
}
func (UnimplementedNetworkInstancesServer) StreamNetworkPipelines(*StreamNetworkPipelinesRequest, grpc.ServerStreamingServer[StreamNetworkPipelineEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamNetworkPipelines not implemented")
}
func (UnimplementedNetworkInstancesServer) ToggleNetworkPipeline(context.Context, *ToggleNetworkPipelineRequest) (*ToggleNetworkPipelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleNetworkPipeline not implemented")
}
func (UnimplementedNetworkInstancesServer) OpenLogStream(*OpenNetworkInstanceLogStreamRequest, grpc.ServerStreamingServer[NetworkInstanceLogStreamMessages]) error {
	return status.Errorf(codes.Unimplemented, "method OpenLogStream not implemented")
}
func (UnimplementedNetworkInstancesServer) mustEmbedUnimplementedNetworkInstancesServer() {}
func (UnimplementedNetworkInstancesServer) testEmbeddedByValue()                          {}

// UnsafeNetworkInstancesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkInstancesServer will
// result in compilation errors.
type UnsafeNetworkInstancesServer interface {
	mustEmbedUnimplementedNetworkInstancesServer()
}

func RegisterNetworkInstancesServer(s grpc.ServiceRegistrar, srv NetworkInstancesServer) {
	// If the following call pancis, it indicates UnimplementedNetworkInstancesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkInstances_ServiceDesc, srv)
}

func _NetworkInstances_GetNetworkInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInstancesServer).GetNetworkInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkInstances_GetNetworkInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInstancesServer).GetNetworkInstances(ctx, req.(*GetNetworkInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkInstances_StreamNetworkInstances_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamNetworkInstancesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetworkInstancesServer).StreamNetworkInstances(m, &grpc.GenericServerStream[StreamNetworkInstancesRequest, StreamNetworkInstanceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkInstances_StreamNetworkInstancesServer = grpc.ServerStreamingServer[StreamNetworkInstanceEvent]

func _NetworkInstances_GetNetworkPipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkPipelinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInstancesServer).GetNetworkPipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkInstances_GetNetworkPipelines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInstancesServer).GetNetworkPipelines(ctx, req.(*GetNetworkPipelinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkInstances_StreamNetworkPipelines_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamNetworkPipelinesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetworkInstancesServer).StreamNetworkPipelines(m, &grpc.GenericServerStream[StreamNetworkPipelinesRequest, StreamNetworkPipelineEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkInstances_StreamNetworkPipelinesServer = grpc.ServerStreamingServer[StreamNetworkPipelineEvent]

func _NetworkInstances_ToggleNetworkPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleNetworkPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInstancesServer).ToggleNetworkPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkInstances_ToggleNetworkPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInstancesServer).ToggleNetworkPipeline(ctx, req.(*ToggleNetworkPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkInstances_OpenLogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpenNetworkInstanceLogStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetworkInstancesServer).OpenLogStream(m, &grpc.GenericServerStream[OpenNetworkInstanceLogStreamRequest, NetworkInstanceLogStreamMessages]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkInstances_OpenLogStreamServer = grpc.ServerStreamingServer[NetworkInstanceLogStreamMessages]

// NetworkInstances_ServiceDesc is the grpc.ServiceDesc for NetworkInstances service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkInstances_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanopinggrpc.networks.NetworkInstances",
	HandlerType: (*NetworkInstancesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getNetworkInstances",
			Handler:    _NetworkInstances_GetNetworkInstances_Handler,
		},
		{
			MethodName: "getNetworkPipelines",
			Handler:    _NetworkInstances_GetNetworkPipelines_Handler,
		},
		{
			MethodName: "toggleNetworkPipeline",
			Handler:    _NetworkInstances_ToggleNetworkPipeline_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamNetworkInstances",
			Handler:       _NetworkInstances_StreamNetworkInstances_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "streamNetworkPipelines",
			Handler:       _NetworkInstances_StreamNetworkPipelines_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "openLogStream",
			Handler:       _NetworkInstances_OpenLogStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "network_instances.proto",
}
