// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.31.0
// source: networks.proto

package networks

import (
	logging "github.com/nanoping-labs/nanoping-api-go/v11/logging"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The role of a node in a network.
type NodeType int32

const (
	// A client node.
	NodeType_NODE_TYPE_CLIENT NodeType = 0
	// The relay node, named by the network's `relay_node_id`.
	NodeType_NODE_TYPE_RELAY NodeType = 1
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_CLIENT",
		1: "NODE_TYPE_RELAY",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_CLIENT": 0,
		"NODE_TYPE_RELAY":  1,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_networks_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_networks_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{0}
}

// A virtual network connecting nodes through a central relay node.
type Network struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the network. Must not be empty. Example: `Office network`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The IPv4 subnet, in CIDR notation, that node IP addresses are assigned from. Example: `100.65.254.0/24`
	SubnetCidr string `protobuf:"bytes,2,opt,name=subnet_cidr,json=subnetCidr,proto3" json:"subnet_cidr,omitempty"`
	// The blueprints used to generate the network's pipelines.
	Blueprints *NetworkBlueprints `protobuf:"bytes,3,opt,name=blueprints,proto3" json:"blueprints,omitempty"`
	// Parameters available to the network's blueprints, as a JSON object. May be empty.
	// Example:
	//
	//	`{
	//	  "raft_timeout": 9000,
	//	  "loss_emulation_percentage": 1
	//	}`
	Parameters string `protobuf:"bytes,4,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// The node ID of the relay node. Must be the node that has networks enabled.
	RelayNodeId string `protobuf:"bytes,5,opt,name=relay_node_id,json=relayNodeId,proto3" json:"relay_node_id,omitempty"`
	// The nodes in the network, each with its assigned IP address and carriers.
	Nodes         []*Node `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_networks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{0}
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Network) GetSubnetCidr() string {
	if x != nil {
		return x.SubnetCidr
	}
	return ""
}

func (x *Network) GetBlueprints() *NetworkBlueprints {
	if x != nil {
		return x.Blueprints
	}
	return nil
}

func (x *Network) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

func (x *Network) GetRelayNodeId() string {
	if x != nil {
		return x.RelayNodeId
	}
	return ""
}

func (x *Network) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// The blueprint IDs used for each role in a network. A blueprint left unset falls back to the default blueprint for
// that role configured on the networks node.
type NetworkBlueprints struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional relay blueprint.
	//
	// Types that are valid to be assigned to OptionalRelayBlueprint:
	//
	//	*NetworkBlueprints_RelayBlueprint
	OptionalRelayBlueprint isNetworkBlueprints_OptionalRelayBlueprint `protobuf_oneof:"optional_relay_blueprint"`
	// Optional relay client blueprint.
	//
	// Types that are valid to be assigned to OptionalRelayClientBlueprint:
	//
	//	*NetworkBlueprints_RelayClientBlueprint
	OptionalRelayClientBlueprint isNetworkBlueprints_OptionalRelayClientBlueprint `protobuf_oneof:"optional_relay_client_blueprint"`
	// Optional client blueprint.
	//
	// Types that are valid to be assigned to OptionalClientBlueprint:
	//
	//	*NetworkBlueprints_ClientBlueprint
	OptionalClientBlueprint isNetworkBlueprints_OptionalClientBlueprint `protobuf_oneof:"optional_client_blueprint"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NetworkBlueprints) Reset() {
	*x = NetworkBlueprints{}
	mi := &file_networks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkBlueprints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkBlueprints) ProtoMessage() {}

func (x *NetworkBlueprints) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkBlueprints.ProtoReflect.Descriptor instead.
func (*NetworkBlueprints) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkBlueprints) GetOptionalRelayBlueprint() isNetworkBlueprints_OptionalRelayBlueprint {
	if x != nil {
		return x.OptionalRelayBlueprint
	}
	return nil
}

func (x *NetworkBlueprints) GetRelayBlueprint() string {
	if x != nil {
		if x, ok := x.OptionalRelayBlueprint.(*NetworkBlueprints_RelayBlueprint); ok {
			return x.RelayBlueprint
		}
	}
	return ""
}

func (x *NetworkBlueprints) GetOptionalRelayClientBlueprint() isNetworkBlueprints_OptionalRelayClientBlueprint {
	if x != nil {
		return x.OptionalRelayClientBlueprint
	}
	return nil
}

func (x *NetworkBlueprints) GetRelayClientBlueprint() string {
	if x != nil {
		if x, ok := x.OptionalRelayClientBlueprint.(*NetworkBlueprints_RelayClientBlueprint); ok {
			return x.RelayClientBlueprint
		}
	}
	return ""
}

func (x *NetworkBlueprints) GetOptionalClientBlueprint() isNetworkBlueprints_OptionalClientBlueprint {
	if x != nil {
		return x.OptionalClientBlueprint
	}
	return nil
}

func (x *NetworkBlueprints) GetClientBlueprint() string {
	if x != nil {
		if x, ok := x.OptionalClientBlueprint.(*NetworkBlueprints_ClientBlueprint); ok {
			return x.ClientBlueprint
		}
	}
	return ""
}

type isNetworkBlueprints_OptionalRelayBlueprint interface {
	isNetworkBlueprints_OptionalRelayBlueprint()
}

type NetworkBlueprints_RelayBlueprint struct {
	// ID of the blueprint deployed to the relay node.
	RelayBlueprint string `protobuf:"bytes,1,opt,name=relay_blueprint,json=relayBlueprint,proto3,oneof"`
}

func (*NetworkBlueprints_RelayBlueprint) isNetworkBlueprints_OptionalRelayBlueprint() {}

type isNetworkBlueprints_OptionalRelayClientBlueprint interface {
	isNetworkBlueprints_OptionalRelayClientBlueprint()
}

type NetworkBlueprints_RelayClientBlueprint struct {
	// ID of the blueprint deployed to the relay node once for every client in the network.
	RelayClientBlueprint string `protobuf:"bytes,2,opt,name=relay_client_blueprint,json=relayClientBlueprint,proto3,oneof"`
}

func (*NetworkBlueprints_RelayClientBlueprint) isNetworkBlueprints_OptionalRelayClientBlueprint() {}

type isNetworkBlueprints_OptionalClientBlueprint interface {
	isNetworkBlueprints_OptionalClientBlueprint()
}

type NetworkBlueprints_ClientBlueprint struct {
	// ID of the blueprint deployed to every node in the network.
	ClientBlueprint string `protobuf:"bytes,3,opt,name=client_blueprint,json=clientBlueprint,proto3,oneof"`
}

func (*NetworkBlueprints_ClientBlueprint) isNetworkBlueprints_OptionalClientBlueprint() {}

// A node's membership in a network.
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the node.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// The node's IP address in the network. Must be unique within the network and cannot be changed. Example:
	// `100.65.254.2`
	NodeIp string `protobuf:"bytes,2,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
	// The carriers the node uses in the network. Each carrier of the relay node needs an `address`; each carrier of a
	// client needs an `address` or an `interface`.
	Carriers []*Carrier `protobuf:"bytes,3,rep,name=carriers,proto3" json:"carriers,omitempty"`
	// The node's role, derived from the network's `relay_node_id`. Cannot be changed directly.
	Type NodeType `protobuf:"varint,4,opt,name=type,proto3,enum=nanopinggrpc.networks.NodeType" json:"type,omitempty"`
	// Parameters for this node available to the blueprints, as a JSON object. May be empty.
	Parameters    string `protobuf:"bytes,5,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_networks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Node) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

func (x *Node) GetCarriers() []*Carrier {
	if x != nil {
		return x.Carriers
	}
	return nil
}

func (x *Node) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_NODE_TYPE_CLIENT
}

func (x *Node) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

// A connection a node uses to carry network traffic.
type Carrier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional address.
	//
	// Types that are valid to be assigned to OptionalAddress:
	//
	//	*Carrier_Address
	OptionalAddress isCarrier_OptionalAddress `protobuf_oneof:"optional_address"`
	// Optional interface.
	//
	// Types that are valid to be assigned to OptionalInterface:
	//
	//	*Carrier_Interface
	OptionalInterface isCarrier_OptionalInterface `protobuf_oneof:"optional_interface"`
	// Optional bandwidth priority.
	//
	// Types that are valid to be assigned to OptionalBandwidthPriority:
	//
	//	*Carrier_BandwidthPriority
	OptionalBandwidthPriority isCarrier_OptionalBandwidthPriority `protobuf_oneof:"optional_bandwidth_priority"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Carrier) Reset() {
	*x = Carrier{}
	mi := &file_networks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Carrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Carrier) ProtoMessage() {}

func (x *Carrier) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Carrier.ProtoReflect.Descriptor instead.
func (*Carrier) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{3}
}

func (x *Carrier) GetOptionalAddress() isCarrier_OptionalAddress {
	if x != nil {
		return x.OptionalAddress
	}
	return nil
}

func (x *Carrier) GetAddress() *Address {
	if x != nil {
		if x, ok := x.OptionalAddress.(*Carrier_Address); ok {
			return x.Address
		}
	}
	return nil
}

func (x *Carrier) GetOptionalInterface() isCarrier_OptionalInterface {
	if x != nil {
		return x.OptionalInterface
	}
	return nil
}

func (x *Carrier) GetInterface() string {
	if x != nil {
		if x, ok := x.OptionalInterface.(*Carrier_Interface); ok {
			return x.Interface
		}
	}
	return ""
}

func (x *Carrier) GetOptionalBandwidthPriority() isCarrier_OptionalBandwidthPriority {
	if x != nil {
		return x.OptionalBandwidthPriority
	}
	return nil
}

func (x *Carrier) GetBandwidthPriority() uint32 {
	if x != nil {
		if x, ok := x.OptionalBandwidthPriority.(*Carrier_BandwidthPriority); ok {
			return x.BandwidthPriority
		}
	}
	return 0
}

type isCarrier_OptionalAddress interface {
	isCarrier_OptionalAddress()
}

type Carrier_Address struct {
	// The IP address and port of the carrier.
	Address *Address `protobuf:"bytes,1,opt,name=address,proto3,oneof"`
}

func (*Carrier_Address) isCarrier_OptionalAddress() {}

type isCarrier_OptionalInterface interface {
	isCarrier_OptionalInterface()
}

type Carrier_Interface struct {
	// The name of the network interface to use. Example: `eth0`
	Interface string `protobuf:"bytes,2,opt,name=interface,proto3,oneof"`
}

func (*Carrier_Interface) isCarrier_OptionalInterface() {}

type isCarrier_OptionalBandwidthPriority interface {
	isCarrier_OptionalBandwidthPriority()
}

type Carrier_BandwidthPriority struct {
	// The bandwidth priority of the carrier.
	BandwidthPriority uint32 `protobuf:"varint,3,opt,name=bandwidth_priority,json=bandwidthPriority,proto3,oneof"`
}

func (*Carrier_BandwidthPriority) isCarrier_OptionalBandwidthPriority() {}

// The address of a carrier.
type Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IP address. Example: `192.168.1.20`
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// The port. Example: `3425`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Optional external IP.
	//
	// Types that are valid to be assigned to OptionalExternalIp:
	//
	//	*Address_ExternalIp
	OptionalExternalIp isAddress_OptionalExternalIp `protobuf_oneof:"optional_external_ip"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_networks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{4}
}

func (x *Address) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Address) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Address) GetOptionalExternalIp() isAddress_OptionalExternalIp {
	if x != nil {
		return x.OptionalExternalIp
	}
	return nil
}

func (x *Address) GetExternalIp() string {
	if x != nil {
		if x, ok := x.OptionalExternalIp.(*Address_ExternalIp); ok {
			return x.ExternalIp
		}
	}
	return ""
}

type isAddress_OptionalExternalIp interface {
	isAddress_OptionalExternalIp()
}

type Address_ExternalIp struct {
	// The external IP address of the carrier. Example: `203.0.113.10`
	ExternalIp string `protobuf:"bytes,3,opt,name=external_ip,json=externalIp,proto3,oneof"`
}

func (*Address_ExternalIp) isAddress_OptionalExternalIp() {}

// Request for a single network.
type GetNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the network to fetch.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkRequest) Reset() {
	*x = GetNetworkRequest{}
	mi := &file_networks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkRequest) ProtoMessage() {}

func (x *GetNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkRequest) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{5}
}

func (x *GetNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// A network and its ID.
type GetNetworkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the network.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The network.
	Network       *Network `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkResponse) Reset() {
	*x = GetNetworkResponse{}
	mi := &file_networks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkResponse) ProtoMessage() {}

func (x *GetNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkResponse) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{6}
}

func (x *GetNetworkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetNetworkResponse) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

// Request for all networks.
type GetNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworksRequest) Reset() {
	*x = GetNetworksRequest{}
	mi := &file_networks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworksRequest) ProtoMessage() {}

func (x *GetNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworksRequest.ProtoReflect.Descriptor instead.
func (*GetNetworksRequest) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{7}
}

// All networks.
type GetNetworksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The networks with their IDs.
	Networks      []*GetNetworkResponse `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworksResponse) Reset() {
	*x = GetNetworksResponse{}
	mi := &file_networks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworksResponse) ProtoMessage() {}

func (x *GetNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworksResponse.ProtoReflect.Descriptor instead.
func (*GetNetworksResponse) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{8}
}

func (x *GetNetworksResponse) GetNetworks() []*GetNetworkResponse {
	if x != nil {
		return x.Networks
	}
	return nil
}

// Request to create a network.
type CreateNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The network to create. Required.
	Network       *Network `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkRequest) Reset() {
	*x = CreateNetworkRequest{}
	mi := &file_networks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkRequest) ProtoMessage() {}

func (x *CreateNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkRequest.ProtoReflect.Descriptor instead.
func (*CreateNetworkRequest) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{9}
}

func (x *CreateNetworkRequest) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

// The created network.
type CreateNetworkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The generated ID of the network.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The created network.
	Network       *Network `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkResponse) Reset() {
	*x = CreateNetworkResponse{}
	mi := &file_networks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkResponse) ProtoMessage() {}

func (x *CreateNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkResponse.ProtoReflect.Descriptor instead.
func (*CreateNetworkResponse) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{10}
}

func (x *CreateNetworkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateNetworkResponse) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

// Request to update a network.
type UpdateNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the network to update.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The new settings of the network. Required. All fields replace the current values, except `nodes`: leave it empty
	// to keep the nodes unchanged, or list every current node to edit their carriers and parameters.
	Network       *Network `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNetworkRequest) Reset() {
	*x = UpdateNetworkRequest{}
	mi := &file_networks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNetworkRequest) ProtoMessage() {}

func (x *UpdateNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNetworkRequest.ProtoReflect.Descriptor instead.
func (*UpdateNetworkRequest) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNetworkRequest) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

// The updated network.
type UpdateNetworkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the network.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The network after the update.
	Network       *Network `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNetworkResponse) Reset() {
	*x = UpdateNetworkResponse{}
	mi := &file_networks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNetworkResponse) ProtoMessage() {}

func (x *UpdateNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNetworkResponse.ProtoReflect.Descriptor instead.
func (*UpdateNetworkResponse) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateNetworkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNetworkResponse) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

// Request to delete a network.
type DeleteNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the network to delete.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkRequest) Reset() {
	*x = DeleteNetworkRequest{}
	mi := &file_networks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkRequest) ProtoMessage() {}

func (x *DeleteNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkRequest.ProtoReflect.Descriptor instead.
func (*DeleteNetworkRequest) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Empty response to a network deletion.
type DeleteNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkResponse) Reset() {
	*x = DeleteNetworkResponse{}
	mi := &file_networks_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkResponse) ProtoMessage() {}

func (x *DeleteNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkResponse.ProtoReflect.Descriptor instead.
func (*DeleteNetworkResponse) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{14}
}

// Request to stream network changes.
type StreamNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNetworksRequest) Reset() {
	*x = StreamNetworksRequest{}
	mi := &file_networks_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNetworksRequest) ProtoMessage() {}

func (x *StreamNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNetworksRequest.ProtoReflect.Descriptor instead.
func (*StreamNetworksRequest) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{15}
}

// Sent when a network is created.
type StreamNetworksCreateEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created network.
	Network       *Network `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNetworksCreateEvent) Reset() {
	*x = StreamNetworksCreateEvent{}
	mi := &file_networks_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNetworksCreateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNetworksCreateEvent) ProtoMessage() {}

func (x *StreamNetworksCreateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNetworksCreateEvent.ProtoReflect.Descriptor instead.
func (*StreamNetworksCreateEvent) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{16}
}

func (x *StreamNetworksCreateEvent) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

// Sent when a network is updated.
type StreamNetworksUpdateEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The network after the update.
	Network       *Network `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNetworksUpdateEvent) Reset() {
	*x = StreamNetworksUpdateEvent{}
	mi := &file_networks_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNetworksUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNetworksUpdateEvent) ProtoMessage() {}

func (x *StreamNetworksUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNetworksUpdateEvent.ProtoReflect.Descriptor instead.
func (*StreamNetworksUpdateEvent) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{17}
}

func (x *StreamNetworksUpdateEvent) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

// Sent when a network is deleted.
type StreamNetworksDeleteEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The deleted network.
	Network       *Network `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNetworksDeleteEvent) Reset() {
	*x = StreamNetworksDeleteEvent{}
	mi := &file_networks_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNetworksDeleteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNetworksDeleteEvent) ProtoMessage() {}

func (x *StreamNetworksDeleteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNetworksDeleteEvent.ProtoReflect.Descriptor instead.
func (*StreamNetworksDeleteEvent) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{18}
}

func (x *StreamNetworksDeleteEvent) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

// A change to a network.
type StreamNetworksEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The kind of change.
	//
	// Types that are valid to be assigned to Event:
	//
	//	*StreamNetworksEvent_Create
	//	*StreamNetworksEvent_Update
	//	*StreamNetworksEvent_Delete
	Event         isStreamNetworksEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNetworksEvent) Reset() {
	*x = StreamNetworksEvent{}
	mi := &file_networks_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNetworksEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNetworksEvent) ProtoMessage() {}

func (x *StreamNetworksEvent) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNetworksEvent.ProtoReflect.Descriptor instead.
func (*StreamNetworksEvent) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{19}
}

func (x *StreamNetworksEvent) GetEvent() isStreamNetworksEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamNetworksEvent) GetCreate() *StreamNetworksCreateEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamNetworksEvent_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *StreamNetworksEvent) GetUpdate() *StreamNetworksUpdateEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamNetworksEvent_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *StreamNetworksEvent) GetDelete() *StreamNetworksDeleteEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamNetworksEvent_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isStreamNetworksEvent_Event interface {
	isStreamNetworksEvent_Event()
}

type StreamNetworksEvent_Create struct {
	// A network was created.
	Create *StreamNetworksCreateEvent `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type StreamNetworksEvent_Update struct {
	// A network was updated.
	Update *StreamNetworksUpdateEvent `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type StreamNetworksEvent_Delete struct {
	// A network was deleted.
	Delete *StreamNetworksDeleteEvent `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

func (*StreamNetworksEvent_Create) isStreamNetworksEvent_Event() {}

func (*StreamNetworksEvent_Update) isStreamNetworksEvent_Event() {}

func (*StreamNetworksEvent_Delete) isStreamNetworksEvent_Event() {}

// Request to stream the log of a network.
type OpenNetworkLogStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the network whose log to stream.
	NetworkId string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Log stream options, such as how many past lines to send first.
	Options       *logging.Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenNetworkLogStreamRequest) Reset() {
	*x = OpenNetworkLogStreamRequest{}
	mi := &file_networks_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenNetworkLogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenNetworkLogStreamRequest) ProtoMessage() {}

func (x *OpenNetworkLogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenNetworkLogStreamRequest.ProtoReflect.Descriptor instead.
func (*OpenNetworkLogStreamRequest) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{20}
}

func (x *OpenNetworkLogStreamRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *OpenNetworkLogStreamRequest) GetOptions() *logging.Options {
	if x != nil {
		return x.Options
	}
	return nil
}

// A batch of network log messages.
type NetworkLogStreamMessages struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The log messages.
	Messages      []*logging.Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkLogStreamMessages) Reset() {
	*x = NetworkLogStreamMessages{}
	mi := &file_networks_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkLogStreamMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkLogStreamMessages) ProtoMessage() {}

func (x *NetworkLogStreamMessages) ProtoReflect() protoreflect.Message {
	mi := &file_networks_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkLogStreamMessages.ProtoReflect.Descriptor instead.
func (*NetworkLogStreamMessages) Descriptor() ([]byte, []int) {
	return file_networks_proto_rawDescGZIP(), []int{21}
}

func (x *NetworkLogStreamMessages) GetMessages() []*logging.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_networks_proto protoreflect.FileDescriptor

var file_networks_proto_rawDesc = string([]byte{
	0x0a, 0x0e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x15, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x1a, 0x0d, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xff, 0x01, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74,
	0x5f, 0x63, 0x69, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62,
	0x6e, 0x65, 0x74, 0x43, 0x69, 0x64, 0x72, 0x12, 0x48, 0x0a, 0x0a, 0x62, 0x6c, 0x75, 0x65, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6e, 0x61,
	0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x6c, 0x75, 0x65, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x0a, 0x62, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0xff, 0x01, 0x0a, 0x11, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x42, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x29,
	0x0a, 0x0f, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x62, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x65, 0x6c, 0x61, 0x79,
	0x42, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x16, 0x72, 0x65, 0x6c,
	0x61, 0x79, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x6c, 0x75, 0x65, 0x70, 0x72,
	0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x14, 0x72, 0x65, 0x6c,
	0x61, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x12, 0x2b, 0x0a, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x6c, 0x75, 0x65,
	0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x42, 0x1a,
	0x0a, 0x18, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x79,
	0x5f, 0x62, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x42, 0x21, 0x0a, 0x1f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x62, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x42, 0x1b, 0x0a,
	0x19, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x62, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x22, 0xc9, 0x01, 0x0a, 0x04, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x70, 0x12, 0x3a, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69,
	0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e,
	0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x52, 0x08, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72,
	0x73, 0x12, 0x33, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1f, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0xdf, 0x01, 0x0a, 0x07, 0x43, 0x61, 0x72, 0x72, 0x69,
	0x65, 0x72, 0x12, 0x3a, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e,
	0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x2f,
	0x0a, 0x12, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x69, 0x6f,
	0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x02, 0x52, 0x11, 0x62, 0x61,
	0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x42,
	0x12, 0x0a, 0x10, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x42, 0x14, 0x0a, 0x12, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x42, 0x1d, 0x0a, 0x1b, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x5f,
	0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x22, 0x68, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a,
	0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x70, 0x42, 0x16, 0x0a, 0x14, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f,
	0x69, 0x70, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x38, 0x0a,
	0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5c, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x08, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e,
	0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x08, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x22, 0x50, 0x0a, 0x14, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x61, 0x0a,
	0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69,
	0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x22, 0x60, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x61, 0x6e, 0x6f,
	0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x22, 0x61, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e,
	0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x17, 0x0a,
	0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x55, 0x0a, 0x19, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x07,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x55, 0x0a, 0x19, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x55, 0x0a,
	0x19, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x61,
	0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x22, 0x82, 0x02, 0x0a, 0x13, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x4a, 0x0a, 0x06,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6e,
	0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x4a, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70,
	0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x4a, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x75, 0x0a, 0x1b, 0x4f, 0x70, 0x65,
	0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70,
	0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x55, 0x0a, 0x18, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x67, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f,
	0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2a, 0x35, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x4f, 0x44,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x4c, 0x41, 0x59, 0x10, 0x01, 0x32, 0x8b,
	0x06, 0x0a, 0x08, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x12, 0x63, 0x0a, 0x0a, 0x67,
	0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x28, 0x2e, 0x6e, 0x61, 0x6e, 0x6f,
	0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x66, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x12,
	0x29, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6e, 0x61, 0x6e,
	0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x2b, 0x2e, 0x6e, 0x61, 0x6e, 0x6f,
	0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e,
	0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x2b, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69,
	0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x2b, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x6e, 0x0a, 0x0e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x12, 0x2c, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x78, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x6e, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x32, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x6e,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69,
	0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01, 0x42, 0x18, 0x5a, 0x16,
	0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_networks_proto_rawDescOnce sync.Once
	file_networks_proto_rawDescData []byte
)

func file_networks_proto_rawDescGZIP() []byte {
	file_networks_proto_rawDescOnce.Do(func() {
		file_networks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networks_proto_rawDesc), len(file_networks_proto_rawDesc)))
	})
	return file_networks_proto_rawDescData
}

var file_networks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_networks_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_networks_proto_goTypes = []any{
	(NodeType)(0),                       // 0: nanopinggrpc.networks.NodeType
	(*Network)(nil),                     // 1: nanopinggrpc.networks.Network
	(*NetworkBlueprints)(nil),           // 2: nanopinggrpc.networks.NetworkBlueprints
	(*Node)(nil),                        // 3: nanopinggrpc.networks.Node
	(*Carrier)(nil),                     // 4: nanopinggrpc.networks.Carrier
	(*Address)(nil),                     // 5: nanopinggrpc.networks.Address
	(*GetNetworkRequest)(nil),           // 6: nanopinggrpc.networks.GetNetworkRequest
	(*GetNetworkResponse)(nil),          // 7: nanopinggrpc.networks.GetNetworkResponse
	(*GetNetworksRequest)(nil),          // 8: nanopinggrpc.networks.GetNetworksRequest
	(*GetNetworksResponse)(nil),         // 9: nanopinggrpc.networks.GetNetworksResponse
	(*CreateNetworkRequest)(nil),        // 10: nanopinggrpc.networks.CreateNetworkRequest
	(*CreateNetworkResponse)(nil),       // 11: nanopinggrpc.networks.CreateNetworkResponse
	(*UpdateNetworkRequest)(nil),        // 12: nanopinggrpc.networks.UpdateNetworkRequest
	(*UpdateNetworkResponse)(nil),       // 13: nanopinggrpc.networks.UpdateNetworkResponse
	(*DeleteNetworkRequest)(nil),        // 14: nanopinggrpc.networks.DeleteNetworkRequest
	(*DeleteNetworkResponse)(nil),       // 15: nanopinggrpc.networks.DeleteNetworkResponse
	(*StreamNetworksRequest)(nil),       // 16: nanopinggrpc.networks.StreamNetworksRequest
	(*StreamNetworksCreateEvent)(nil),   // 17: nanopinggrpc.networks.StreamNetworksCreateEvent
	(*StreamNetworksUpdateEvent)(nil),   // 18: nanopinggrpc.networks.StreamNetworksUpdateEvent
	(*StreamNetworksDeleteEvent)(nil),   // 19: nanopinggrpc.networks.StreamNetworksDeleteEvent
	(*StreamNetworksEvent)(nil),         // 20: nanopinggrpc.networks.StreamNetworksEvent
	(*OpenNetworkLogStreamRequest)(nil), // 21: nanopinggrpc.networks.OpenNetworkLogStreamRequest
	(*NetworkLogStreamMessages)(nil),    // 22: nanopinggrpc.networks.NetworkLogStreamMessages
	(*logging.Options)(nil),             // 23: nanopinggrpc.logging.Options
	(*logging.Message)(nil),             // 24: nanopinggrpc.logging.Message
}
var file_networks_proto_depIdxs = []int32{
	2,  // 0: nanopinggrpc.networks.Network.blueprints:type_name -> nanopinggrpc.networks.NetworkBlueprints
	3,  // 1: nanopinggrpc.networks.Network.nodes:type_name -> nanopinggrpc.networks.Node
	4,  // 2: nanopinggrpc.networks.Node.carriers:type_name -> nanopinggrpc.networks.Carrier
	0,  // 3: nanopinggrpc.networks.Node.type:type_name -> nanopinggrpc.networks.NodeType
	5,  // 4: nanopinggrpc.networks.Carrier.address:type_name -> nanopinggrpc.networks.Address
	1,  // 5: nanopinggrpc.networks.GetNetworkResponse.network:type_name -> nanopinggrpc.networks.Network
	7,  // 6: nanopinggrpc.networks.GetNetworksResponse.networks:type_name -> nanopinggrpc.networks.GetNetworkResponse
	1,  // 7: nanopinggrpc.networks.CreateNetworkRequest.network:type_name -> nanopinggrpc.networks.Network
	1,  // 8: nanopinggrpc.networks.CreateNetworkResponse.network:type_name -> nanopinggrpc.networks.Network
	1,  // 9: nanopinggrpc.networks.UpdateNetworkRequest.network:type_name -> nanopinggrpc.networks.Network
	1,  // 10: nanopinggrpc.networks.UpdateNetworkResponse.network:type_name -> nanopinggrpc.networks.Network
	1,  // 11: nanopinggrpc.networks.StreamNetworksCreateEvent.network:type_name -> nanopinggrpc.networks.Network
	1,  // 12: nanopinggrpc.networks.StreamNetworksUpdateEvent.network:type_name -> nanopinggrpc.networks.Network
	1,  // 13: nanopinggrpc.networks.StreamNetworksDeleteEvent.network:type_name -> nanopinggrpc.networks.Network
	17, // 14: nanopinggrpc.networks.StreamNetworksEvent.create:type_name -> nanopinggrpc.networks.StreamNetworksCreateEvent
	18, // 15: nanopinggrpc.networks.StreamNetworksEvent.update:type_name -> nanopinggrpc.networks.StreamNetworksUpdateEvent
	19, // 16: nanopinggrpc.networks.StreamNetworksEvent.delete:type_name -> nanopinggrpc.networks.StreamNetworksDeleteEvent
	23, // 17: nanopinggrpc.networks.OpenNetworkLogStreamRequest.options:type_name -> nanopinggrpc.logging.Options
	24, // 18: nanopinggrpc.networks.NetworkLogStreamMessages.messages:type_name -> nanopinggrpc.logging.Message
	6,  // 19: nanopinggrpc.networks.Networks.getNetwork:input_type -> nanopinggrpc.networks.GetNetworkRequest
	8,  // 20: nanopinggrpc.networks.Networks.getNetworks:input_type -> nanopinggrpc.networks.GetNetworksRequest
	10, // 21: nanopinggrpc.networks.Networks.createNetwork:input_type -> nanopinggrpc.networks.CreateNetworkRequest
	12, // 22: nanopinggrpc.networks.Networks.updateNetwork:input_type -> nanopinggrpc.networks.UpdateNetworkRequest
	14, // 23: nanopinggrpc.networks.Networks.deleteNetwork:input_type -> nanopinggrpc.networks.DeleteNetworkRequest
	16, // 24: nanopinggrpc.networks.Networks.streamNetworks:input_type -> nanopinggrpc.networks.StreamNetworksRequest
	21, // 25: nanopinggrpc.networks.Networks.openLogStream:input_type -> nanopinggrpc.networks.OpenNetworkLogStreamRequest
	7,  // 26: nanopinggrpc.networks.Networks.getNetwork:output_type -> nanopinggrpc.networks.GetNetworkResponse
	9,  // 27: nanopinggrpc.networks.Networks.getNetworks:output_type -> nanopinggrpc.networks.GetNetworksResponse
	11, // 28: nanopinggrpc.networks.Networks.createNetwork:output_type -> nanopinggrpc.networks.CreateNetworkResponse
	13, // 29: nanopinggrpc.networks.Networks.updateNetwork:output_type -> nanopinggrpc.networks.UpdateNetworkResponse
	15, // 30: nanopinggrpc.networks.Networks.deleteNetwork:output_type -> nanopinggrpc.networks.DeleteNetworkResponse
	20, // 31: nanopinggrpc.networks.Networks.streamNetworks:output_type -> nanopinggrpc.networks.StreamNetworksEvent
	22, // 32: nanopinggrpc.networks.Networks.openLogStream:output_type -> nanopinggrpc.networks.NetworkLogStreamMessages
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_networks_proto_init() }
func file_networks_proto_init() {
	if File_networks_proto != nil {
		return
	}
	file_networks_proto_msgTypes[1].OneofWrappers = []any{
		(*NetworkBlueprints_RelayBlueprint)(nil),
		(*NetworkBlueprints_RelayClientBlueprint)(nil),
		(*NetworkBlueprints_ClientBlueprint)(nil),
	}
	file_networks_proto_msgTypes[3].OneofWrappers = []any{
		(*Carrier_Address)(nil),
		(*Carrier_Interface)(nil),
		(*Carrier_BandwidthPriority)(nil),
	}
	file_networks_proto_msgTypes[4].OneofWrappers = []any{
		(*Address_ExternalIp)(nil),
	}
	file_networks_proto_msgTypes[19].OneofWrappers = []any{
		(*StreamNetworksEvent_Create)(nil),
		(*StreamNetworksEvent_Update)(nil),
		(*StreamNetworksEvent_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networks_proto_rawDesc), len(file_networks_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_networks_proto_goTypes,
		DependencyIndexes: file_networks_proto_depIdxs,
		EnumInfos:         file_networks_proto_enumTypes,
		MessageInfos:      file_networks_proto_msgTypes,
	}.Build()
	File_networks_proto = out.File
	file_networks_proto_goTypes = nil
	file_networks_proto_depIdxs = nil
}
