// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: networks.proto

package networks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Networks_GetNetwork_FullMethodName     = "/nanopinggrpc.networks.Networks/getNetwork"
	Networks_GetNetworks_FullMethodName    = "/nanopinggrpc.networks.Networks/getNetworks"
	Networks_CreateNetwork_FullMethodName  = "/nanopinggrpc.networks.Networks/createNetwork"
	Networks_UpdateNetwork_FullMethodName  = "/nanopinggrpc.networks.Networks/updateNetwork"
	Networks_DeleteNetwork_FullMethodName  = "/nanopinggrpc.networks.Networks/deleteNetwork"
	Networks_StreamNetworks_FullMethodName = "/nanopinggrpc.networks.Networks/streamNetworks"
	Networks_OpenLogStream_FullMethodName  = "/nanopinggrpc.networks.Networks/openLogStream"
)

// NetworksClient is the client API for Networks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A network is a virtual network that connects nodes as if they shared a local network, giving each node its own IP
// address. All traffic flows through a central relay node. When a network is created or changed, the pipelines each
// node needs are generated from the network's blueprints and deployed automatically. Use this service to create and
// change networks and to follow their changes and logs. Networks are stored on the connected node that has networks
// enabled, and calls wait until that node is connected.
type NetworksClient interface {
	// Get a single network.
	GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error)
	// Get all networks.
	GetNetworks(ctx context.Context, in *GetNetworksRequest, opts ...grpc.CallOption) (*GetNetworksResponse, error)
	// Create a network and return it. Every connected node is added to the network automatically and assigned the first
	// free IP address in its subnet, so nodes given in the request are ignored.
	CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error)
	// Replace the settings of an existing network and return the updated network. Nodes cannot be added or removed, and
	// their IP address and role cannot be changed.
	UpdateNetwork(ctx context.Context, in *UpdateNetworkRequest, opts ...grpc.CallOption) (*UpdateNetworkResponse, error)
	// Delete a network.
	DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error)
	// Stream changes to networks. Nothing is sent when the stream opens; an event is sent each time a network is
	// created, updated or deleted. The stream ends if the connection to the networks node is lost.
	StreamNetworks(ctx context.Context, in *StreamNetworksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamNetworksEvent], error)
	// Stream the log messages of a network. The requested number of past lines is sent first, then new messages as
	// they are logged, until the connection to the networks node is lost.
	OpenLogStream(ctx context.Context, in *OpenNetworkLogStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetworkLogStreamMessages], error)
}

type networksClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworksClient(cc grpc.ClientConnInterface) NetworksClient {
	return &networksClient{cc}
}

func (c *networksClient) GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkResponse)
	err := c.cc.Invoke(ctx, Networks_GetNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networksClient) GetNetworks(ctx context.Context, in *GetNetworksRequest, opts ...grpc.CallOption) (*GetNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworksResponse)
	err := c.cc.Invoke(ctx, Networks_GetNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networksClient) CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNetworkResponse)
	err := c.cc.Invoke(ctx, Networks_CreateNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networksClient) UpdateNetwork(ctx context.Context, in *UpdateNetworkRequest, opts ...grpc.CallOption) (*UpdateNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNetworkResponse)
	err := c.cc.Invoke(ctx, Networks_UpdateNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networksClient) DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNetworkResponse)
	err := c.cc.Invoke(ctx, Networks_DeleteNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networksClient) StreamNetworks(ctx context.Context, in *StreamNetworksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamNetworksEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Networks_ServiceDesc.Streams[0], Networks_StreamNetworks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamNetworksRequest, StreamNetworksEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Networks_StreamNetworksClient = grpc.ServerStreamingClient[StreamNetworksEvent]

func (c *networksClient) OpenLogStream(ctx context.Context, in *OpenNetworkLogStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetworkLogStreamMessages], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Networks_ServiceDesc.Streams[1], Networks_OpenLogStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenNetworkLogStreamRequest, NetworkLogStreamMessages]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Networks_OpenLogStreamClient = grpc.ServerStreamingClient[NetworkLogStreamMessages]

// NetworksServer is the server API for Networks service.
// All implementations must embed UnimplementedNetworksServer
// for forward compatibility.
//
// A network is a virtual network that connects nodes as if they shared a local network, giving each node its own IP
// address. All traffic flows through a central relay node. When a network is created or changed, the pipelines each
// node needs are generated from the network's blueprints and deployed automatically. Use this service to create and
// change networks and to follow their changes and logs. Networks are stored on the connected node that has networks
// enabled, and calls wait until that node is connected.
type NetworksServer interface {
	// Get a single network.
	GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error)
	// Get all networks.
	GetNetworks(context.Context, *GetNetworksRequest) (*GetNetworksResponse, error)
	// Create a network and return it. Every connected node is added to the network automatically and assigned the first
	// free IP address in its subnet, so nodes given in the request are ignored.
	CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error)
	// Replace the settings of an existing network and return the updated network. Nodes cannot be added or removed, and
	// their IP address and role cannot be changed.
	UpdateNetwork(context.Context, *UpdateNetworkRequest) (*UpdateNetworkResponse, error)
	// Delete a network.
	DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error)
	// Stream changes to networks. Nothing is sent when the stream opens; an event is sent each time a network is
	// created, updated or deleted. The stream ends if the connection to the networks node is lost.
	StreamNetworks(*StreamNetworksRequest, grpc.ServerStreamingServer[StreamNetworksEvent]) error
	// Stream the log messages of a network. The requested number of past lines is sent first, then new messages as
	// they are logged, until the connection to the networks node is lost.
	OpenLogStream(*OpenNetworkLogStreamRequest, grpc.ServerStreamingServer[NetworkLogStreamMessages]) error
	mustEmbedUnimplementedNetworksServer()
}

// UnimplementedNetworksServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworksServer struct{}

func (UnimplementedNetworksServer) GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetwork not implemented")
}
func (UnimplementedNetworksServer) GetNetworks(context.Context, *GetNetworksRequest) (*GetNetworksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetworks not implemented")
}
func (UnimplementedNetworksServer) CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNetwork not implemented")
}
func (UnimplementedNetworksServer) UpdateNetwork(context.Context, *UpdateNetworkRequest) (*UpdateNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNetwork not implemented")
}
func (UnimplementedNetworksServer) DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNetwork not implemented")
}
func (UnimplementedNetworksServer) StreamNetworks(*StreamNetworksRequest, grpc.ServerStreamingServer[StreamNetworksEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamNetworks not implemented")
}
func (UnimplementedNetworksServer) OpenLogStream(*OpenNetworkLogStreamRequest, grpc.ServerStreamingServer[NetworkLogStreamMessages]) error {
	return status.Errorf(codes.Unimplemented, "method OpenLogStream not implemented")
}
func (UnimplementedNetworksServer) mustEmbedUnimplementedNetworksServer() {}
func (UnimplementedNetworksServer) testEmbeddedByValue()                  {}

// UnsafeNetworksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworksServer will
// result in compilation errors.
type UnsafeNetworksServer interface {
	mustEmbedUnimplementedNetworksServer()
}

func RegisterNetworksServer(s grpc.ServiceRegistrar, srv NetworksServer) {
	// If the following call pancis, it indicates UnimplementedNetworksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Networks_ServiceDesc, srv)
}

func _Networks_GetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworksServer).GetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Networks_GetNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworksServer).GetNetwork(ctx, req.(*GetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Networks_GetNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworksServer).GetNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Networks_GetNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworksServer).GetNetworks(ctx, req.(*GetNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Networks_CreateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworksServer).CreateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Networks_CreateNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworksServer).CreateNetwork(ctx, req.(*CreateNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Networks_UpdateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworksServer).UpdateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Networks_UpdateNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworksServer).UpdateNetwork(ctx, req.(*UpdateNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Networks_DeleteNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworksServer).DeleteNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Networks_DeleteNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworksServer).DeleteNetwork(ctx, req.(*DeleteNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Networks_StreamNetworks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamNetworksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetworksServer).StreamNetworks(m, &grpc.GenericServerStream[StreamNetworksRequest, StreamNetworksEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Networks_StreamNetworksServer = grpc.ServerStreamingServer[StreamNetworksEvent]

func _Networks_OpenLogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpenNetworkLogStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetworksServer).OpenLogStream(m, &grpc.GenericServerStream[OpenNetworkLogStreamRequest, NetworkLogStreamMessages]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Networks_OpenLogStreamServer = grpc.ServerStreamingServer[NetworkLogStreamMessages]

// Networks_ServiceDesc is the grpc.ServiceDesc for Networks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Networks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanopinggrpc.networks.Networks",
	HandlerType: (*NetworksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getNetwork",
			Handler:    _Networks_GetNetwork_Handler,
		},
		{
			MethodName: "getNetworks",
			Handler:    _Networks_GetNetworks_Handler,
		},
		{
			MethodName: "createNetwork",
			Handler:    _Networks_CreateNetwork_Handler,
		},
		{
			MethodName: "updateNetwork",
			Handler:    _Networks_UpdateNetwork_Handler,
		},
		{
			MethodName: "deleteNetwork",
			Handler:    _Networks_DeleteNetwork_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamNetworks",
			Handler:       _Networks_StreamNetworks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "openLogStream",
			Handler:       _Networks_OpenLogStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "networks.proto",
}
