// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: logging.proto

package logging

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoggingService_OpenLogStream_FullMethodName   = "/nanopinggrpc.logging.LoggingService/openLogStream"
	LoggingService_DownloadLogFile_FullMethodName = "/nanopinggrpc.logging.LoggingService/downloadLogFile"
)

// LoggingServiceClient is the client API for LoggingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Every node keeps logs: its application log, and a log for each pipeline run, network and network instance. Use this
// service to follow a log live or to download a complete log file, from any node.
type LoggingServiceClient interface {
	// Stream the log messages of one log on a node. The requested number of past entries is sent first, then new entries
	// as they are written. Fails with an invalid argument error when the node is invalid or no log is chosen, and ends
	// with an error when the log cannot be read or the node loses its connection.
	OpenLogStream(ctx context.Context, in *OpenLogStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Messages], error)
	// Download one complete log file from a node as a series of chunks. Join the chunks in order to get the file. The
	// stream ends when the whole file has been sent, or after an error chunk when the file could not be read.
	DownloadLogFile(ctx context.Context, in *DownloadLogFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadLogFileChunk], error)
}

type loggingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggingServiceClient(cc grpc.ClientConnInterface) LoggingServiceClient {
	return &loggingServiceClient{cc}
}

func (c *loggingServiceClient) OpenLogStream(ctx context.Context, in *OpenLogStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Messages], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LoggingService_ServiceDesc.Streams[0], LoggingService_OpenLogStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenLogStreamRequest, Messages]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoggingService_OpenLogStreamClient = grpc.ServerStreamingClient[Messages]

func (c *loggingServiceClient) DownloadLogFile(ctx context.Context, in *DownloadLogFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadLogFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LoggingService_ServiceDesc.Streams[1], LoggingService_DownloadLogFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadLogFileRequest, DownloadLogFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoggingService_DownloadLogFileClient = grpc.ServerStreamingClient[DownloadLogFileChunk]

// LoggingServiceServer is the server API for LoggingService service.
// All implementations must embed UnimplementedLoggingServiceServer
// for forward compatibility.
//
// Every node keeps logs: its application log, and a log for each pipeline run, network and network instance. Use this
// service to follow a log live or to download a complete log file, from any node.
type LoggingServiceServer interface {
	// Stream the log messages of one log on a node. The requested number of past entries is sent first, then new entries
	// as they are written. Fails with an invalid argument error when the node is invalid or no log is chosen, and ends
	// with an error when the log cannot be read or the node loses its connection.
	OpenLogStream(*OpenLogStreamRequest, grpc.ServerStreamingServer[Messages]) error
	// Download one complete log file from a node as a series of chunks. Join the chunks in order to get the file. The
	// stream ends when the whole file has been sent, or after an error chunk when the file could not be read.
	DownloadLogFile(*DownloadLogFileRequest, grpc.ServerStreamingServer[DownloadLogFileChunk]) error
	mustEmbedUnimplementedLoggingServiceServer()
}

// UnimplementedLoggingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoggingServiceServer struct{}

func (UnimplementedLoggingServiceServer) OpenLogStream(*OpenLogStreamRequest, grpc.ServerStreamingServer[Messages]) error {
	return status.Errorf(codes.Unimplemented, "method OpenLogStream not implemented")
}
func (UnimplementedLoggingServiceServer) DownloadLogFile(*DownloadLogFileRequest, grpc.ServerStreamingServer[DownloadLogFileChunk]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadLogFile not implemented")
}
func (UnimplementedLoggingServiceServer) mustEmbedUnimplementedLoggingServiceServer() {}
func (UnimplementedLoggingServiceServer) testEmbeddedByValue()                        {}

// UnsafeLoggingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoggingServiceServer will
// result in compilation errors.
type UnsafeLoggingServiceServer interface {
	mustEmbedUnimplementedLoggingServiceServer()
}

func RegisterLoggingServiceServer(s grpc.ServiceRegistrar, srv LoggingServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoggingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoggingService_ServiceDesc, srv)
}

func _LoggingService_OpenLogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpenLogStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingServiceServer).OpenLogStream(m, &grpc.GenericServerStream[OpenLogStreamRequest, Messages]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoggingService_OpenLogStreamServer = grpc.ServerStreamingServer[Messages]

func _LoggingService_DownloadLogFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadLogFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingServiceServer).DownloadLogFile(m, &grpc.GenericServerStream[DownloadLogFileRequest, DownloadLogFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoggingService_DownloadLogFileServer = grpc.ServerStreamingServer[DownloadLogFileChunk]

// LoggingService_ServiceDesc is the grpc.ServiceDesc for LoggingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoggingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanopinggrpc.logging.LoggingService",
	HandlerType: (*LoggingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "openLogStream",
			Handler:       _LoggingService_OpenLogStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "downloadLogFile",
			Handler:       _LoggingService_DownloadLogFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "logging.proto",
}
