// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.31.0
// source: logging.proto

package logging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity of a log message, from the most verbose to the most severe.
type Level int32

const (
	// State information, the most verbose level.
	Level_STATE Level = 0
	// Debugging details.
	Level_DEBUG Level = 1
	// General information.
	Level_INFO Level = 2
	// Something unexpected that did not stop the operation.
	Level_WARNING Level = 3
	// An operation failed.
	Level_ERROR Level = 4
	// A failure the process could not recover from.
	Level_FATAL Level = 5
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "STATE",
		1: "DEBUG",
		2: "INFO",
		3: "WARNING",
		4: "ERROR",
		5: "FATAL",
	}
	Level_value = map[string]int32{
		"STATE":   0,
		"DEBUG":   1,
		"INFO":    2,
		"WARNING": 3,
		"ERROR":   4,
		"FATAL":   5,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_logging_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_logging_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{0}
}

// Options for opening a log stream.
type Options struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of the most recent log entries to send when the stream opens. When unset, no earlier entries are sent and
	// the stream only delivers new ones.
	//
	// Types that are valid to be assigned to OptionalLines:
	//
	//	*Options_Lines
	OptionalLines isOptions_OptionalLines `protobuf_oneof:"optional_lines"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_logging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetOptionalLines() isOptions_OptionalLines {
	if x != nil {
		return x.OptionalLines
	}
	return nil
}

func (x *Options) GetLines() int64 {
	if x != nil {
		if x, ok := x.OptionalLines.(*Options_Lines); ok {
			return x.Lines
		}
	}
	return 0
}

type isOptions_OptionalLines interface {
	isOptions_OptionalLines()
}

type Options_Lines struct {
	// The number of entries.
	Lines int64 `protobuf:"varint,1,opt,name=lines,proto3,oneof"`
}

func (*Options_Lines) isOptions_OptionalLines() {}

// Opens a stream of log messages from one log on a node.
type OpenLogStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the node whose log to stream.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Stream options. When unset, only new entries are sent.
	Options *Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	// The log to stream. Exactly one must be set.
	//
	// Types that are valid to be assigned to Request:
	//
	//	*OpenLogStreamRequest_AppLogStreamRequest
	//	*OpenLogStreamRequest_PipelineRunLogStreamRequest
	//	*OpenLogStreamRequest_NetworkLogStreamRequest
	//	*OpenLogStreamRequest_NetworkInstanceLogStreamRequest
	Request       isOpenLogStreamRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenLogStreamRequest) Reset() {
	*x = OpenLogStreamRequest{}
	mi := &file_logging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenLogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenLogStreamRequest) ProtoMessage() {}

func (x *OpenLogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenLogStreamRequest.ProtoReflect.Descriptor instead.
func (*OpenLogStreamRequest) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{1}
}

func (x *OpenLogStreamRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *OpenLogStreamRequest) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *OpenLogStreamRequest) GetRequest() isOpenLogStreamRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *OpenLogStreamRequest) GetAppLogStreamRequest() *OpenAppLogStreamRequest {
	if x != nil {
		if x, ok := x.Request.(*OpenLogStreamRequest_AppLogStreamRequest); ok {
			return x.AppLogStreamRequest
		}
	}
	return nil
}

func (x *OpenLogStreamRequest) GetPipelineRunLogStreamRequest() *OpenPipelineRunLogStreamRequest {
	if x != nil {
		if x, ok := x.Request.(*OpenLogStreamRequest_PipelineRunLogStreamRequest); ok {
			return x.PipelineRunLogStreamRequest
		}
	}
	return nil
}

func (x *OpenLogStreamRequest) GetNetworkLogStreamRequest() *OpenNetworkLogStreamRequest {
	if x != nil {
		if x, ok := x.Request.(*OpenLogStreamRequest_NetworkLogStreamRequest); ok {
			return x.NetworkLogStreamRequest
		}
	}
	return nil
}

func (x *OpenLogStreamRequest) GetNetworkInstanceLogStreamRequest() *OpenNetworkInstanceLogStreamRequest {
	if x != nil {
		if x, ok := x.Request.(*OpenLogStreamRequest_NetworkInstanceLogStreamRequest); ok {
			return x.NetworkInstanceLogStreamRequest
		}
	}
	return nil
}

type isOpenLogStreamRequest_Request interface {
	isOpenLogStreamRequest_Request()
}

type OpenLogStreamRequest_AppLogStreamRequest struct {
	// Stream the node's application log.
	AppLogStreamRequest *OpenAppLogStreamRequest `protobuf:"bytes,3,opt,name=app_log_stream_request,json=appLogStreamRequest,proto3,oneof"`
}

type OpenLogStreamRequest_PipelineRunLogStreamRequest struct {
	// Stream the log of a pipeline run.
	PipelineRunLogStreamRequest *OpenPipelineRunLogStreamRequest `protobuf:"bytes,4,opt,name=pipeline_run_log_stream_request,json=pipelineRunLogStreamRequest,proto3,oneof"`
}

type OpenLogStreamRequest_NetworkLogStreamRequest struct {
	// Stream the log of a network.
	NetworkLogStreamRequest *OpenNetworkLogStreamRequest `protobuf:"bytes,5,opt,name=network_log_stream_request,json=networkLogStreamRequest,proto3,oneof"`
}

type OpenLogStreamRequest_NetworkInstanceLogStreamRequest struct {
	// Stream the log of a network instance.
	NetworkInstanceLogStreamRequest *OpenNetworkInstanceLogStreamRequest `protobuf:"bytes,6,opt,name=network_instance_log_stream_request,json=networkInstanceLogStreamRequest,proto3,oneof"`
}

func (*OpenLogStreamRequest_AppLogStreamRequest) isOpenLogStreamRequest_Request() {}

func (*OpenLogStreamRequest_PipelineRunLogStreamRequest) isOpenLogStreamRequest_Request() {}

func (*OpenLogStreamRequest_NetworkLogStreamRequest) isOpenLogStreamRequest_Request() {}

func (*OpenLogStreamRequest_NetworkInstanceLogStreamRequest) isOpenLogStreamRequest_Request() {}

// Selects the node's application log. Takes no parameters.
type OpenAppLogStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAppLogStreamRequest) Reset() {
	*x = OpenAppLogStreamRequest{}
	mi := &file_logging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAppLogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAppLogStreamRequest) ProtoMessage() {}

func (x *OpenAppLogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAppLogStreamRequest.ProtoReflect.Descriptor instead.
func (*OpenAppLogStreamRequest) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{2}
}

// Selects the log of a pipeline run.
type OpenPipelineRunLogStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the pipeline run. Must not be empty.
	PipelineRunId string `protobuf:"bytes,1,opt,name=pipeline_run_id,json=pipelineRunId,proto3" json:"pipeline_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenPipelineRunLogStreamRequest) Reset() {
	*x = OpenPipelineRunLogStreamRequest{}
	mi := &file_logging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenPipelineRunLogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPipelineRunLogStreamRequest) ProtoMessage() {}

func (x *OpenPipelineRunLogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPipelineRunLogStreamRequest.ProtoReflect.Descriptor instead.
func (*OpenPipelineRunLogStreamRequest) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{3}
}

func (x *OpenPipelineRunLogStreamRequest) GetPipelineRunId() string {
	if x != nil {
		return x.PipelineRunId
	}
	return ""
}

// Selects the log of a network.
type OpenNetworkLogStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the network. Must not be empty.
	NetworkId     string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenNetworkLogStreamRequest) Reset() {
	*x = OpenNetworkLogStreamRequest{}
	mi := &file_logging_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenNetworkLogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenNetworkLogStreamRequest) ProtoMessage() {}

func (x *OpenNetworkLogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenNetworkLogStreamRequest.ProtoReflect.Descriptor instead.
func (*OpenNetworkLogStreamRequest) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{4}
}

func (x *OpenNetworkLogStreamRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

// Selects the log of a network instance.
type OpenNetworkInstanceLogStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the network instance. Must not be empty.
	NetworkInstanceId string `protobuf:"bytes,1,opt,name=network_instance_id,json=networkInstanceId,proto3" json:"network_instance_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OpenNetworkInstanceLogStreamRequest) Reset() {
	*x = OpenNetworkInstanceLogStreamRequest{}
	mi := &file_logging_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenNetworkInstanceLogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenNetworkInstanceLogStreamRequest) ProtoMessage() {}

func (x *OpenNetworkInstanceLogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenNetworkInstanceLogStreamRequest.ProtoReflect.Descriptor instead.
func (*OpenNetworkInstanceLogStreamRequest) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{5}
}

func (x *OpenNetworkInstanceLogStreamRequest) GetNetworkInstanceId() string {
	if x != nil {
		return x.NetworkInstanceId
	}
	return ""
}

// A single log entry.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When the entry was logged.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Severity of the entry.
	Level Level `protobuf:"varint,2,opt,name=level,proto3,enum=nanopinggrpc.logging.Level" json:"level,omitempty"`
	// The log text. Holds the whole raw line when no message could be extracted from it.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// The raw log line when it is valid JSON, so structured fields can be read from it. Empty otherwise.
	Data          string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_logging_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Message) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_STATE
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Message) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// A batch of log entries, oldest first.
type Messages struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The log entries.
	Messages      []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Messages) Reset() {
	*x = Messages{}
	mi := &file_logging_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Messages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messages) ProtoMessage() {}

func (x *Messages) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messages.ProtoReflect.Descriptor instead.
func (*Messages) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{7}
}

func (x *Messages) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Downloads one log file from a node.
type DownloadLogFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the node that holds the log file.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// The log file to download. Exactly one must be set.
	//
	// Types that are valid to be assigned to Request:
	//
	//	*DownloadLogFileRequest_AppLogFileRequest
	//	*DownloadLogFileRequest_PipelineRunLogFileRequest
	//	*DownloadLogFileRequest_NetworkLogFileRequest
	//	*DownloadLogFileRequest_NetworkInstanceLogFileRequest
	Request       isDownloadLogFileRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadLogFileRequest) Reset() {
	*x = DownloadLogFileRequest{}
	mi := &file_logging_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadLogFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadLogFileRequest) ProtoMessage() {}

func (x *DownloadLogFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadLogFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadLogFileRequest) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadLogFileRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DownloadLogFileRequest) GetRequest() isDownloadLogFileRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *DownloadLogFileRequest) GetAppLogFileRequest() *DownloadAppLogFileRequest {
	if x != nil {
		if x, ok := x.Request.(*DownloadLogFileRequest_AppLogFileRequest); ok {
			return x.AppLogFileRequest
		}
	}
	return nil
}

func (x *DownloadLogFileRequest) GetPipelineRunLogFileRequest() *DownloadPipelineRunLogFileRequest {
	if x != nil {
		if x, ok := x.Request.(*DownloadLogFileRequest_PipelineRunLogFileRequest); ok {
			return x.PipelineRunLogFileRequest
		}
	}
	return nil
}

func (x *DownloadLogFileRequest) GetNetworkLogFileRequest() *DownloadNetworkLogFileRequest {
	if x != nil {
		if x, ok := x.Request.(*DownloadLogFileRequest_NetworkLogFileRequest); ok {
			return x.NetworkLogFileRequest
		}
	}
	return nil
}

func (x *DownloadLogFileRequest) GetNetworkInstanceLogFileRequest() *DownloadNetworkInstanceLogFileRequest {
	if x != nil {
		if x, ok := x.Request.(*DownloadLogFileRequest_NetworkInstanceLogFileRequest); ok {
			return x.NetworkInstanceLogFileRequest
		}
	}
	return nil
}

type isDownloadLogFileRequest_Request interface {
	isDownloadLogFileRequest_Request()
}

type DownloadLogFileRequest_AppLogFileRequest struct {
	// Download the node's application log.
	AppLogFileRequest *DownloadAppLogFileRequest `protobuf:"bytes,2,opt,name=app_log_file_request,json=appLogFileRequest,proto3,oneof"`
}

type DownloadLogFileRequest_PipelineRunLogFileRequest struct {
	// Download the log of a pipeline run.
	PipelineRunLogFileRequest *DownloadPipelineRunLogFileRequest `protobuf:"bytes,3,opt,name=pipeline_run_log_file_request,json=pipelineRunLogFileRequest,proto3,oneof"`
}

type DownloadLogFileRequest_NetworkLogFileRequest struct {
	// Download the log of a network.
	NetworkLogFileRequest *DownloadNetworkLogFileRequest `protobuf:"bytes,4,opt,name=network_log_file_request,json=networkLogFileRequest,proto3,oneof"`
}

type DownloadLogFileRequest_NetworkInstanceLogFileRequest struct {
	// Download the log of a network instance.
	NetworkInstanceLogFileRequest *DownloadNetworkInstanceLogFileRequest `protobuf:"bytes,5,opt,name=network_instance_log_file_request,json=networkInstanceLogFileRequest,proto3,oneof"`
}

func (*DownloadLogFileRequest_AppLogFileRequest) isDownloadLogFileRequest_Request() {}

func (*DownloadLogFileRequest_PipelineRunLogFileRequest) isDownloadLogFileRequest_Request() {}

func (*DownloadLogFileRequest_NetworkLogFileRequest) isDownloadLogFileRequest_Request() {}

func (*DownloadLogFileRequest_NetworkInstanceLogFileRequest) isDownloadLogFileRequest_Request() {}

// Selects the node's application log file. Takes no parameters.
type DownloadAppLogFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadAppLogFileRequest) Reset() {
	*x = DownloadAppLogFileRequest{}
	mi := &file_logging_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadAppLogFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadAppLogFileRequest) ProtoMessage() {}

func (x *DownloadAppLogFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadAppLogFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadAppLogFileRequest) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{9}
}

// Selects the log file of a pipeline run.
type DownloadPipelineRunLogFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the pipeline run. Must not be empty.
	PipelineRunId string `protobuf:"bytes,1,opt,name=pipeline_run_id,json=pipelineRunId,proto3" json:"pipeline_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPipelineRunLogFileRequest) Reset() {
	*x = DownloadPipelineRunLogFileRequest{}
	mi := &file_logging_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPipelineRunLogFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPipelineRunLogFileRequest) ProtoMessage() {}

func (x *DownloadPipelineRunLogFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPipelineRunLogFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadPipelineRunLogFileRequest) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadPipelineRunLogFileRequest) GetPipelineRunId() string {
	if x != nil {
		return x.PipelineRunId
	}
	return ""
}

// Selects the log file of a network.
type DownloadNetworkLogFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the network. Must not be empty.
	NetworkId     string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadNetworkLogFileRequest) Reset() {
	*x = DownloadNetworkLogFileRequest{}
	mi := &file_logging_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadNetworkLogFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadNetworkLogFileRequest) ProtoMessage() {}

func (x *DownloadNetworkLogFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadNetworkLogFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadNetworkLogFileRequest) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadNetworkLogFileRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

// Selects the log file of a network instance.
type DownloadNetworkInstanceLogFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the network instance. Must not be empty.
	NetworkInstanceId string `protobuf:"bytes,1,opt,name=network_instance_id,json=networkInstanceId,proto3" json:"network_instance_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DownloadNetworkInstanceLogFileRequest) Reset() {
	*x = DownloadNetworkInstanceLogFileRequest{}
	mi := &file_logging_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadNetworkInstanceLogFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadNetworkInstanceLogFileRequest) ProtoMessage() {}

func (x *DownloadNetworkInstanceLogFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadNetworkInstanceLogFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadNetworkInstanceLogFileRequest) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadNetworkInstanceLogFileRequest) GetNetworkInstanceId() string {
	if x != nil {
		return x.NetworkInstanceId
	}
	return ""
}

// One message of a log file download: either a piece of the file or an error.
type DownloadLogFileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The content of this message.
	//
	// Types that are valid to be assigned to Response:
	//
	//	*DownloadLogFileChunk_Error
	//	*DownloadLogFileChunk_FileChunk
	Response      isDownloadLogFileChunk_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadLogFileChunk) Reset() {
	*x = DownloadLogFileChunk{}
	mi := &file_logging_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadLogFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadLogFileChunk) ProtoMessage() {}

func (x *DownloadLogFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadLogFileChunk.ProtoReflect.Descriptor instead.
func (*DownloadLogFileChunk) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{13}
}

func (x *DownloadLogFileChunk) GetResponse() isDownloadLogFileChunk_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *DownloadLogFileChunk) GetError() string {
	if x != nil {
		if x, ok := x.Response.(*DownloadLogFileChunk_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *DownloadLogFileChunk) GetFileChunk() *LogFileChunk {
	if x != nil {
		if x, ok := x.Response.(*DownloadLogFileChunk_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

type isDownloadLogFileChunk_Response interface {
	isDownloadLogFileChunk_Response()
}

type DownloadLogFileChunk_Error struct {
	// Why the file could not be read, for example because it does not exist. No more chunks follow.
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type DownloadLogFileChunk_FileChunk struct {
	// The next piece of the file.
	FileChunk *LogFileChunk `protobuf:"bytes,1,opt,name=file_chunk,json=fileChunk,proto3,oneof"`
}

func (*DownloadLogFileChunk_Error) isDownloadLogFileChunk_Response() {}

func (*DownloadLogFileChunk_FileChunk) isDownloadLogFileChunk_Response() {}

// A piece of a log file.
type LogFileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw file bytes, up to 64 KiB per chunk.
	Content       []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFileChunk) Reset() {
	*x = LogFileChunk{}
	mi := &file_logging_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFileChunk) ProtoMessage() {}

func (x *LogFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_logging_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFileChunk.ProtoReflect.Descriptor instead.
func (*LogFileChunk) Descriptor() ([]byte, []int) {
	return file_logging_proto_rawDescGZIP(), []int{14}
}

func (x *LogFileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_logging_proto protoreflect.FileDescriptor

var file_logging_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x14, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f,
	0x67, 0x67, 0x69, 0x6e, 0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x16, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x42, 0x10, 0x0a, 0x0e, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x4a, 0x04, 0x08, 0x02, 0x10,
	0x03, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x22, 0xd6,
	0x04, 0x0a, 0x14, 0x4f, 0x70, 0x65, 0x6e, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x37, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x64, 0x0a, 0x16, 0x61, 0x70, 0x70,
	0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6e, 0x61, 0x6e, 0x6f,
	0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67,
	0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x70, 0x70, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x13, 0x61, 0x70, 0x70, 0x4c,
	0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x7d, 0x0a, 0x1f, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x75, 0x6e, 0x5f,
	0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70,
	0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e,
	0x4f, 0x70, 0x65, 0x6e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x75, 0x6e, 0x4c,
	0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x1b, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x75, 0x6e, 0x4c, 0x6f,
	0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x70,
	0x0a, 0x1a, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x17, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x89, 0x01, 0x0a, 0x23, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39,
	0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f,
	0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x1f, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x4f, 0x70, 0x65, 0x6e, 0x41,
	0x70, 0x70, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x49, 0x0a, 0x1f, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x52, 0x75, 0x6e, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x5f, 0x72, 0x75, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x75, 0x6e, 0x49, 0x64, 0x22, 0x3c, 0x0a,
	0x1b, 0x4f, 0x70, 0x65, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x67, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x23, 0x4f,
	0x70, 0x65, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x11, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x64, 0x22, 0xa4, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x31, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69,
	0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x08, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69,
	0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x22, 0x97, 0x04, 0x0a, 0x16, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x6f, 0x67,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x62, 0x0a, 0x14, 0x61, 0x70, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x5f,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x41, 0x70, 0x70, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x11, 0x61, 0x70, 0x70, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x7b, 0x0a, 0x1d, 0x70, 0x69, 0x70, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x75, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x37, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c,
	0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x75, 0x6e, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x19, 0x70, 0x69, 0x70, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x75, 0x6e, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x6e, 0x0a, 0x18, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69,
	0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4c, 0x6f,
	0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x15,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x87, 0x01, 0x0a, 0x21, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x3b, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x1d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x21, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x75, 0x6e, 0x4c, 0x6f,
	0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f,
	0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x75, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x75, 0x6e, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x1d, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x25, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4c,
	0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a,
	0x13, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0x7f, 0x0a,
	0x14, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x43, 0x0a,
	0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28,
	0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2a, 0x4a, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x44, 0x45, 0x42, 0x55, 0x47, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x41, 0x54,
	0x41, 0x4c, 0x10, 0x05, 0x32, 0xe2, 0x01, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x6e, 0x4c,
	0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x2a, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70,
	0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e,
	0x4f, 0x70, 0x65, 0x6e, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x6f, 0x0a, 0x0f, 0x64, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2c, 0x2e, 0x6e, 0x61,
	0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69,
	0x6e, 0x67, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x6f, 0x67, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6e, 0x61, 0x6e, 0x6f,
	0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67,
	0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x42, 0x17, 0x5a, 0x15, 0x6e, 0x61, 0x6e,
	0x6f, 0x70, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x69,
	0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_logging_proto_rawDescOnce sync.Once
	file_logging_proto_rawDescData []byte
)

func file_logging_proto_rawDescGZIP() []byte {
	file_logging_proto_rawDescOnce.Do(func() {
		file_logging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logging_proto_rawDesc), len(file_logging_proto_rawDesc)))
	})
	return file_logging_proto_rawDescData
}

var file_logging_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_logging_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_logging_proto_goTypes = []any{
	(Level)(0),                                    // 0: nanopinggrpc.logging.Level
	(*Options)(nil),                               // 1: nanopinggrpc.logging.Options
	(*OpenLogStreamRequest)(nil),                  // 2: nanopinggrpc.logging.OpenLogStreamRequest
	(*OpenAppLogStreamRequest)(nil),               // 3: nanopinggrpc.logging.OpenAppLogStreamRequest
	(*OpenPipelineRunLogStreamRequest)(nil),       // 4: nanopinggrpc.logging.OpenPipelineRunLogStreamRequest
	(*OpenNetworkLogStreamRequest)(nil),           // 5: nanopinggrpc.logging.OpenNetworkLogStreamRequest
	(*OpenNetworkInstanceLogStreamRequest)(nil),   // 6: nanopinggrpc.logging.OpenNetworkInstanceLogStreamRequest
	(*Message)(nil),                               // 7: nanopinggrpc.logging.Message
	(*Messages)(nil),                              // 8: nanopinggrpc.logging.Messages
	(*DownloadLogFileRequest)(nil),                // 9: nanopinggrpc.logging.DownloadLogFileRequest
	(*DownloadAppLogFileRequest)(nil),             // 10: nanopinggrpc.logging.DownloadAppLogFileRequest
	(*DownloadPipelineRunLogFileRequest)(nil),     // 11: nanopinggrpc.logging.DownloadPipelineRunLogFileRequest
	(*DownloadNetworkLogFileRequest)(nil),         // 12: nanopinggrpc.logging.DownloadNetworkLogFileRequest
	(*DownloadNetworkInstanceLogFileRequest)(nil), // 13: nanopinggrpc.logging.DownloadNetworkInstanceLogFileRequest
	(*DownloadLogFileChunk)(nil),                  // 14: nanopinggrpc.logging.DownloadLogFileChunk
	(*LogFileChunk)(nil),                          // 15: nanopinggrpc.logging.LogFileChunk
	(*timestamppb.Timestamp)(nil),                 // 16: google.protobuf.Timestamp
}
var file_logging_proto_depIdxs = []int32{
	1,  // 0: nanopinggrpc.logging.OpenLogStreamRequest.options:type_name -> nanopinggrpc.logging.Options
	3,  // 1: nanopinggrpc.logging.OpenLogStreamRequest.app_log_stream_request:type_name -> nanopinggrpc.logging.OpenAppLogStreamRequest
	4,  // 2: nanopinggrpc.logging.OpenLogStreamRequest.pipeline_run_log_stream_request:type_name -> nanopinggrpc.logging.OpenPipelineRunLogStreamRequest
	5,  // 3: nanopinggrpc.logging.OpenLogStreamRequest.network_log_stream_request:type_name -> nanopinggrpc.logging.OpenNetworkLogStreamRequest
	6,  // 4: nanopinggrpc.logging.OpenLogStreamRequest.network_instance_log_stream_request:type_name -> nanopinggrpc.logging.OpenNetworkInstanceLogStreamRequest
	16, // 5: nanopinggrpc.logging.Message.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: nanopinggrpc.logging.Message.level:type_name -> nanopinggrpc.logging.Level
	7,  // 7: nanopinggrpc.logging.Messages.messages:type_name -> nanopinggrpc.logging.Message
	10, // 8: nanopinggrpc.logging.DownloadLogFileRequest.app_log_file_request:type_name -> nanopinggrpc.logging.DownloadAppLogFileRequest
	11, // 9: nanopinggrpc.logging.DownloadLogFileRequest.pipeline_run_log_file_request:type_name -> nanopinggrpc.logging.DownloadPipelineRunLogFileRequest
	12, // 10: nanopinggrpc.logging.DownloadLogFileRequest.network_log_file_request:type_name -> nanopinggrpc.logging.DownloadNetworkLogFileRequest
	13, // 11: nanopinggrpc.logging.DownloadLogFileRequest.network_instance_log_file_request:type_name -> nanopinggrpc.logging.DownloadNetworkInstanceLogFileRequest
	15, // 12: nanopinggrpc.logging.DownloadLogFileChunk.file_chunk:type_name -> nanopinggrpc.logging.LogFileChunk
	2,  // 13: nanopinggrpc.logging.LoggingService.openLogStream:input_type -> nanopinggrpc.logging.OpenLogStreamRequest
	9,  // 14: nanopinggrpc.logging.LoggingService.downloadLogFile:input_type -> nanopinggrpc.logging.DownloadLogFileRequest
	8,  // 15: nanopinggrpc.logging.LoggingService.openLogStream:output_type -> nanopinggrpc.logging.Messages
	14, // 16: nanopinggrpc.logging.LoggingService.downloadLogFile:output_type -> nanopinggrpc.logging.DownloadLogFileChunk
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_logging_proto_init() }
func file_logging_proto_init() {
	if File_logging_proto != nil {
		return
	}
	file_logging_proto_msgTypes[0].OneofWrappers = []any{
		(*Options_Lines)(nil),
	}
	file_logging_proto_msgTypes[1].OneofWrappers = []any{
		(*OpenLogStreamRequest_AppLogStreamRequest)(nil),
		(*OpenLogStreamRequest_PipelineRunLogStreamRequest)(nil),
		(*OpenLogStreamRequest_NetworkLogStreamRequest)(nil),
		(*OpenLogStreamRequest_NetworkInstanceLogStreamRequest)(nil),
	}
	file_logging_proto_msgTypes[8].OneofWrappers = []any{
		(*DownloadLogFileRequest_AppLogFileRequest)(nil),
		(*DownloadLogFileRequest_PipelineRunLogFileRequest)(nil),
		(*DownloadLogFileRequest_NetworkLogFileRequest)(nil),
		(*DownloadLogFileRequest_NetworkInstanceLogFileRequest)(nil),
	}
	file_logging_proto_msgTypes[13].OneofWrappers = []any{
		(*DownloadLogFileChunk_Error)(nil),
		(*DownloadLogFileChunk_FileChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logging_proto_rawDesc), len(file_logging_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logging_proto_goTypes,
		DependencyIndexes: file_logging_proto_depIdxs,
		EnumInfos:         file_logging_proto_enumTypes,
		MessageInfos:      file_logging_proto_msgTypes,
	}.Build()
	File_logging_proto = out.File
	file_logging_proto_goTypes = nil
	file_logging_proto_depIdxs = nil
}
