// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: resources.proto

package resources

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResourcesService_OpenMetricsStream_FullMethodName = "/nanopinggrpc.resources.ResourcesService/openMetricsStream"
	ResourcesService_OpenFlowsStream_FullMethodName   = "/nanopinggrpc.resources.ResourcesService/openFlowsStream"
)

// ResourcesServiceClient is the client API for ResourcesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Live system information of a node: resource metrics such as CPU, memory, storage and network interface usage, and the
// network flows crossing its interfaces. Use this service to monitor the health and traffic of any node.
type ResourcesServiceClient interface {
	// Stream the resource metrics of a node, such as CPU, memory, disk and network interface usage. A sample of the
	// current metrics is sent when the stream opens. The stream stays open until the client closes it, and ends with an
	// error if the node loses its connection.
	OpenMetricsStream(ctx context.Context, in *OpenMetricsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsSample], error)
	// Stream a snapshot of the network flows crossing the interfaces of a node, about once a second, starting right away.
	// The node only captures packets while someone watches its flows, so the first samples may be empty or incomplete.
	OpenFlowsStream(ctx context.Context, in *OpenFlowsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowsSample], error)
}

type resourcesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourcesServiceClient(cc grpc.ClientConnInterface) ResourcesServiceClient {
	return &resourcesServiceClient{cc}
}

func (c *resourcesServiceClient) OpenMetricsStream(ctx context.Context, in *OpenMetricsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsSample], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourcesService_ServiceDesc.Streams[0], ResourcesService_OpenMetricsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenMetricsStreamRequest, MetricsSample]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourcesService_OpenMetricsStreamClient = grpc.ServerStreamingClient[MetricsSample]

func (c *resourcesServiceClient) OpenFlowsStream(ctx context.Context, in *OpenFlowsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowsSample], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourcesService_ServiceDesc.Streams[1], ResourcesService_OpenFlowsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenFlowsStreamRequest, FlowsSample]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourcesService_OpenFlowsStreamClient = grpc.ServerStreamingClient[FlowsSample]

// ResourcesServiceServer is the server API for ResourcesService service.
// All implementations must embed UnimplementedResourcesServiceServer
// for forward compatibility.
//
// Live system information of a node: resource metrics such as CPU, memory, storage and network interface usage, and the
// network flows crossing its interfaces. Use this service to monitor the health and traffic of any node.
type ResourcesServiceServer interface {
	// Stream the resource metrics of a node, such as CPU, memory, disk and network interface usage. A sample of the
	// current metrics is sent when the stream opens. The stream stays open until the client closes it, and ends with an
	// error if the node loses its connection.
	OpenMetricsStream(*OpenMetricsStreamRequest, grpc.ServerStreamingServer[MetricsSample]) error
	// Stream a snapshot of the network flows crossing the interfaces of a node, about once a second, starting right away.
	// The node only captures packets while someone watches its flows, so the first samples may be empty or incomplete.
	OpenFlowsStream(*OpenFlowsStreamRequest, grpc.ServerStreamingServer[FlowsSample]) error
	mustEmbedUnimplementedResourcesServiceServer()
}

// UnimplementedResourcesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourcesServiceServer struct{}

func (UnimplementedResourcesServiceServer) OpenMetricsStream(*OpenMetricsStreamRequest, grpc.ServerStreamingServer[MetricsSample]) error {
	return status.Errorf(codes.Unimplemented, "method OpenMetricsStream not implemented")
}
func (UnimplementedResourcesServiceServer) OpenFlowsStream(*OpenFlowsStreamRequest, grpc.ServerStreamingServer[FlowsSample]) error {
	return status.Errorf(codes.Unimplemented, "method OpenFlowsStream not implemented")
}
func (UnimplementedResourcesServiceServer) mustEmbedUnimplementedResourcesServiceServer() {}
func (UnimplementedResourcesServiceServer) testEmbeddedByValue()                          {}

// UnsafeResourcesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourcesServiceServer will
// result in compilation errors.
type UnsafeResourcesServiceServer interface {
	mustEmbedUnimplementedResourcesServiceServer()
}

func RegisterResourcesServiceServer(s grpc.ServiceRegistrar, srv ResourcesServiceServer) {
	// If the following call pancis, it indicates UnimplementedResourcesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourcesService_ServiceDesc, srv)
}

func _ResourcesService_OpenMetricsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpenMetricsStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourcesServiceServer).OpenMetricsStream(m, &grpc.GenericServerStream[OpenMetricsStreamRequest, MetricsSample]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourcesService_OpenMetricsStreamServer = grpc.ServerStreamingServer[MetricsSample]

func _ResourcesService_OpenFlowsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpenFlowsStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourcesServiceServer).OpenFlowsStream(m, &grpc.GenericServerStream[OpenFlowsStreamRequest, FlowsSample]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourcesService_OpenFlowsStreamServer = grpc.ServerStreamingServer[FlowsSample]

// ResourcesService_ServiceDesc is the grpc.ServiceDesc for ResourcesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourcesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanopinggrpc.resources.ResourcesService",
	HandlerType: (*ResourcesServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "openMetricsStream",
			Handler:       _ResourcesService_OpenMetricsStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "openFlowsStream",
			Handler:       _ResourcesService_OpenFlowsStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "resources.proto",
}
