// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.31.0
// source: hub_node.proto

package hub_node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Services a node can offer.
type NodeService int32

const (
	// The node hosts a hub server.
	NodeService_HUB_SERVER NodeService = 0
	// The node offers resources.
	NodeService_RESOURCES NodeService = 1
	// The node offers logging.
	NodeService_LOGGING NodeService = 2
	// The node can run pipelines.
	NodeService_PIPELINES NodeService = 3
)

// Enum value maps for NodeService.
var (
	NodeService_name = map[int32]string{
		0: "HUB_SERVER",
		1: "RESOURCES",
		2: "LOGGING",
		3: "PIPELINES",
	}
	NodeService_value = map[string]int32{
		"HUB_SERVER": 0,
		"RESOURCES":  1,
		"LOGGING":    2,
		"PIPELINES":  3,
	}
)

func (x NodeService) Enum() *NodeService {
	p := new(NodeService)
	*p = x
	return p
}

func (x NodeService) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeService) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_node_proto_enumTypes[0].Descriptor()
}

func (NodeService) Type() protoreflect.EnumType {
	return &file_hub_node_proto_enumTypes[0]
}

func (x NodeService) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeService.Descriptor instead.
func (NodeService) EnumDescriptor() ([]byte, []int) {
	return file_hub_node_proto_rawDescGZIP(), []int{0}
}

// A single metadata value of a node. Set exactly one of the value fields.
type NodeMetadataItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The metadata value.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*NodeMetadataItem_BytesValue
	//	*NodeMetadataItem_StringValue
	//	*NodeMetadataItem_IntValue
	//	*NodeMetadataItem_UintValue
	//	*NodeMetadataItem_DoubleValue
	//	*NodeMetadataItem_FloatValue
	//	*NodeMetadataItem_BoolValue
	Value         isNodeMetadataItem_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetadataItem) Reset() {
	*x = NodeMetadataItem{}
	mi := &file_hub_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetadataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetadataItem) ProtoMessage() {}

func (x *NodeMetadataItem) ProtoReflect() protoreflect.Message {
	mi := &file_hub_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetadataItem.ProtoReflect.Descriptor instead.
func (*NodeMetadataItem) Descriptor() ([]byte, []int) {
	return file_hub_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeMetadataItem) GetValue() isNodeMetadataItem_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *NodeMetadataItem) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*NodeMetadataItem_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *NodeMetadataItem) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*NodeMetadataItem_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *NodeMetadataItem) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*NodeMetadataItem_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *NodeMetadataItem) GetUintValue() uint64 {
	if x != nil {
		if x, ok := x.Value.(*NodeMetadataItem_UintValue); ok {
			return x.UintValue
		}
	}
	return 0
}

func (x *NodeMetadataItem) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*NodeMetadataItem_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *NodeMetadataItem) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*NodeMetadataItem_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *NodeMetadataItem) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*NodeMetadataItem_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isNodeMetadataItem_Value interface {
	isNodeMetadataItem_Value()
}

type NodeMetadataItem_BytesValue struct {
	// Raw bytes value.
	BytesValue []byte `protobuf:"bytes,1,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type NodeMetadataItem_StringValue struct {
	// Text value.
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type NodeMetadataItem_IntValue struct {
	// Signed 64-bit integer value.
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type NodeMetadataItem_UintValue struct {
	// Unsigned 64-bit integer value.
	UintValue uint64 `protobuf:"varint,4,opt,name=uint_value,json=uintValue,proto3,oneof"`
}

type NodeMetadataItem_DoubleValue struct {
	// 64-bit floating point value.
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type NodeMetadataItem_FloatValue struct {
	// 32-bit floating point value.
	FloatValue float32 `protobuf:"fixed32,6,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type NodeMetadataItem_BoolValue struct {
	// Boolean value.
	BoolValue bool `protobuf:"varint,7,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*NodeMetadataItem_BytesValue) isNodeMetadataItem_Value() {}

func (*NodeMetadataItem_StringValue) isNodeMetadataItem_Value() {}

func (*NodeMetadataItem_IntValue) isNodeMetadataItem_Value() {}

func (*NodeMetadataItem_UintValue) isNodeMetadataItem_Value() {}

func (*NodeMetadataItem_DoubleValue) isNodeMetadataItem_Value() {}

func (*NodeMetadataItem_FloatValue) isNodeMetadataItem_Value() {}

func (*NodeMetadataItem_BoolValue) isNodeMetadataItem_Value() {}

// User defined key/value metadata attached to a node.
type NodeMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata items keyed by name.
	Items         map[string]*NodeMetadataItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetadata) Reset() {
	*x = NodeMetadata{}
	mi := &file_hub_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetadata) ProtoMessage() {}

func (x *NodeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_hub_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetadata.ProtoReflect.Descriptor instead.
func (*NodeMetadata) Descriptor() ([]byte, []int) {
	return file_hub_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeMetadata) GetItems() map[string]*NodeMetadataItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Information about a node.
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique id of the node.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human readable name of the node.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Whether the node is currently online and connected to the hub server.
	Online bool `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	// Services offered by the node.
	Services []NodeService `protobuf:"varint,4,rep,packed,name=services,proto3,enum=nanopinggrpc.hub.NodeService" json:"services,omitempty"`
	// Metadata of the node.
	Metadata      *NodeMetadata `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_hub_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_hub_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_hub_node_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Node) GetServices() []NodeService {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Node) GetMetadata() *NodeMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_hub_node_proto protoreflect.FileDescriptor

var file_hub_node_proto_rawDesc = string([]byte{
	0x0a, 0x0e, 0x68, 0x75, 0x62, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68,
	0x75, 0x62, 0x22, 0x8c, 0x02, 0x0a, 0x10, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x21, 0x0a, 0x0b, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1d, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f,
	0x0a, 0x0a, 0x75, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x48, 0x00, 0x52, 0x09, 0x75, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x23, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62,
	0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0xad, 0x01, 0x0a, 0x0c, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x3f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x1a, 0x5c, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0xb9, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70,
	0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x12, 0x3a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x48, 0x0a,
	0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x0a,
	0x48, 0x55, 0x42, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4c,
	0x4f, 0x47, 0x47, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x49, 0x50, 0x45,
	0x4c, 0x49, 0x4e, 0x45, 0x53, 0x10, 0x03, 0x42, 0x18, 0x5a, 0x16, 0x6e, 0x61, 0x6e, 0x6f, 0x70,
	0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x75, 0x62, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_hub_node_proto_rawDescOnce sync.Once
	file_hub_node_proto_rawDescData []byte
)

func file_hub_node_proto_rawDescGZIP() []byte {
	file_hub_node_proto_rawDescOnce.Do(func() {
		file_hub_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_node_proto_rawDesc), len(file_hub_node_proto_rawDesc)))
	})
	return file_hub_node_proto_rawDescData
}

var file_hub_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hub_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hub_node_proto_goTypes = []any{
	(NodeService)(0),         // 0: nanopinggrpc.hub.NodeService
	(*NodeMetadataItem)(nil), // 1: nanopinggrpc.hub.NodeMetadataItem
	(*NodeMetadata)(nil),     // 2: nanopinggrpc.hub.NodeMetadata
	(*Node)(nil),             // 3: nanopinggrpc.hub.Node
	nil,                      // 4: nanopinggrpc.hub.NodeMetadata.ItemsEntry
}
var file_hub_node_proto_depIdxs = []int32{
	4, // 0: nanopinggrpc.hub.NodeMetadata.items:type_name -> nanopinggrpc.hub.NodeMetadata.ItemsEntry
	0, // 1: nanopinggrpc.hub.Node.services:type_name -> nanopinggrpc.hub.NodeService
	2, // 2: nanopinggrpc.hub.Node.metadata:type_name -> nanopinggrpc.hub.NodeMetadata
	1, // 3: nanopinggrpc.hub.NodeMetadata.ItemsEntry.value:type_name -> nanopinggrpc.hub.NodeMetadataItem
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hub_node_proto_init() }
func file_hub_node_proto_init() {
	if File_hub_node_proto != nil {
		return
	}
	file_hub_node_proto_msgTypes[0].OneofWrappers = []any{
		(*NodeMetadataItem_BytesValue)(nil),
		(*NodeMetadataItem_StringValue)(nil),
		(*NodeMetadataItem_IntValue)(nil),
		(*NodeMetadataItem_UintValue)(nil),
		(*NodeMetadataItem_DoubleValue)(nil),
		(*NodeMetadataItem_FloatValue)(nil),
		(*NodeMetadataItem_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_node_proto_rawDesc), len(file_hub_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hub_node_proto_goTypes,
		DependencyIndexes: file_hub_node_proto_depIdxs,
		EnumInfos:         file_hub_node_proto_enumTypes,
		MessageInfos:      file_hub_node_proto_msgTypes,
	}.Build()
	File_hub_node_proto = out.File
	file_hub_node_proto_goTypes = nil
	file_hub_node_proto_depIdxs = nil
}
