// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: pipelines.proto

package pipelines

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PipelinesService_GetPipelines_FullMethodName        = "/nanopinggrpc.pipeline.PipelinesService/getPipelines"
	PipelinesService_GetPipelineById_FullMethodName     = "/nanopinggrpc.pipeline.PipelinesService/getPipelineById"
	PipelinesService_GetPipelineByName_FullMethodName   = "/nanopinggrpc.pipeline.PipelinesService/getPipelineByName"
	PipelinesService_GetPipelineByRunId_FullMethodName  = "/nanopinggrpc.pipeline.PipelinesService/getPipelineByRunId"
	PipelinesService_CreatePipeline_FullMethodName      = "/nanopinggrpc.pipeline.PipelinesService/createPipeline"
	PipelinesService_UpdatePipeline_FullMethodName      = "/nanopinggrpc.pipeline.PipelinesService/updatePipeline"
	PipelinesService_DeletePipeline_FullMethodName      = "/nanopinggrpc.pipeline.PipelinesService/deletePipeline"
	PipelinesService_StartPipeline_FullMethodName       = "/nanopinggrpc.pipeline.PipelinesService/startPipeline"
	PipelinesService_StopPipeline_FullMethodName        = "/nanopinggrpc.pipeline.PipelinesService/stopPipeline"
	PipelinesService_StreamPipelines_FullMethodName     = "/nanopinggrpc.pipeline.PipelinesService/streamPipelines"
	PipelinesService_OpenLogStream_FullMethodName       = "/nanopinggrpc.pipeline.PipelinesService/openLogStream"
	PipelinesService_OpenTelemetryStream_FullMethodName = "/nanopinggrpc.pipeline.PipelinesService/openTelemetryStream"
)

// PipelinesServiceClient is the client API for PipelinesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A pipeline is the configuration a node runs to move traffic, connecting components such as UDP sockets, TUN
// interfaces and error correction encoders into a data flow. Each start of a pipeline creates a new run, with its own
// logs and telemetry. Use this service to create, change, start and stop pipelines on any node, and to follow their
// changes, logs and telemetry.
type PipelinesServiceClient interface {
	// Lists all pipelines on the node.
	GetPipelines(ctx context.Context, in *GetPipelinesRequest, opts ...grpc.CallOption) (*GetPipelinesResponse, error)
	// Get one pipeline. Fails with a not found error if it does not exist.
	GetPipelineById(ctx context.Context, in *GetPipelineByIdRequest, opts ...grpc.CallOption) (*GetPipelineByIdResponse, error)
	// Get one pipeline by name. Fails with a not found error if no pipeline, or more than one, has that name.
	GetPipelineByName(ctx context.Context, in *GetPipelineByNameRequest, opts ...grpc.CallOption) (*GetPipelineByNameResponse, error)
	// Get the pipeline that a run belongs to. An unknown run fails with a timeout error.
	GetPipelineByRunId(ctx context.Context, in *GetPipelineByRunIdRequest, opts ...grpc.CallOption) (*GetPipelineByRunIdResponse, error)
	// Create a pipeline from a JSON configuration and return it. The pipeline is not started. Fails with an invalid
	// argument error if the configuration is invalid or the CPU pin is not a thread of the node.
	CreatePipeline(ctx context.Context, in *CreatePipelineRequest, opts ...grpc.CallOption) (*CreatePipelineResponse, error)
	// Replace the settings of a pipeline and return the updated pipeline. If the pipeline is running and its
	// configuration changed, the new configuration is applied to the current run. If that is not possible, the call fails
	// because the pipeline is running, unless a restart is forced.
	UpdatePipeline(ctx context.Context, in *UpdatePipelineRequest, opts ...grpc.CallOption) (*UpdatePipelineResponse, error)
	// Delete a pipeline. Fails with a not found error if it does not exist.
	DeletePipeline(ctx context.Context, in *DeletePipelineRequest, opts ...grpc.CallOption) (*DeletePipelineResponse, error)
	// Start a pipeline and return its new run once it is running. Fails if the pipeline is unknown, already started, or
	// does not reach the running state within 10 seconds.
	StartPipeline(ctx context.Context, in *StartPipelineRequest, opts ...grpc.CallOption) (*StartPipelineResponse, error)
	// Stop a pipeline, found by its ID, its name or its current run. Returns once the stop is requested, without waiting
	// for the run to end. Fails if the pipeline is unknown or already stopped.
	StopPipeline(ctx context.Context, in *StopPipelineRequest, opts ...grpc.CallOption) (*StopPipelineResponse, error)
	// Stream changes to the pipelines of a node. Nothing is sent when the stream opens, so get the pipelines first for
	// the current list. An event is sent each time a pipeline is created, updated or deleted, and when a pipeline starts
	// or stops.
	StreamPipelines(ctx context.Context, in *StreamPipelinesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPipelinesEvent], error)
	// Stream the log messages of a pipeline run. The requested number of past lines is sent first, then new messages as
	// they are logged.
	OpenLogStream(ctx context.Context, in *OpenLogStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamMessages], error)
	// Streams telemetry samples (metrics and KPI values) of a pipeline run at regular intervals while the run is active.
	// The stream ends with an error when the run stops, when the run is unknown, or when the node disconnects.
	OpenTelemetryStream(ctx context.Context, in *OpenTelemetryStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetrySample], error)
}

type pipelinesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPipelinesServiceClient(cc grpc.ClientConnInterface) PipelinesServiceClient {
	return &pipelinesServiceClient{cc}
}

func (c *pipelinesServiceClient) GetPipelines(ctx context.Context, in *GetPipelinesRequest, opts ...grpc.CallOption) (*GetPipelinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPipelinesResponse)
	err := c.cc.Invoke(ctx, PipelinesService_GetPipelines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesServiceClient) GetPipelineById(ctx context.Context, in *GetPipelineByIdRequest, opts ...grpc.CallOption) (*GetPipelineByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPipelineByIdResponse)
	err := c.cc.Invoke(ctx, PipelinesService_GetPipelineById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesServiceClient) GetPipelineByName(ctx context.Context, in *GetPipelineByNameRequest, opts ...grpc.CallOption) (*GetPipelineByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPipelineByNameResponse)
	err := c.cc.Invoke(ctx, PipelinesService_GetPipelineByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesServiceClient) GetPipelineByRunId(ctx context.Context, in *GetPipelineByRunIdRequest, opts ...grpc.CallOption) (*GetPipelineByRunIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPipelineByRunIdResponse)
	err := c.cc.Invoke(ctx, PipelinesService_GetPipelineByRunId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesServiceClient) CreatePipeline(ctx context.Context, in *CreatePipelineRequest, opts ...grpc.CallOption) (*CreatePipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePipelineResponse)
	err := c.cc.Invoke(ctx, PipelinesService_CreatePipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesServiceClient) UpdatePipeline(ctx context.Context, in *UpdatePipelineRequest, opts ...grpc.CallOption) (*UpdatePipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePipelineResponse)
	err := c.cc.Invoke(ctx, PipelinesService_UpdatePipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesServiceClient) DeletePipeline(ctx context.Context, in *DeletePipelineRequest, opts ...grpc.CallOption) (*DeletePipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePipelineResponse)
	err := c.cc.Invoke(ctx, PipelinesService_DeletePipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesServiceClient) StartPipeline(ctx context.Context, in *StartPipelineRequest, opts ...grpc.CallOption) (*StartPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartPipelineResponse)
	err := c.cc.Invoke(ctx, PipelinesService_StartPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesServiceClient) StopPipeline(ctx context.Context, in *StopPipelineRequest, opts ...grpc.CallOption) (*StopPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopPipelineResponse)
	err := c.cc.Invoke(ctx, PipelinesService_StopPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesServiceClient) StreamPipelines(ctx context.Context, in *StreamPipelinesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPipelinesEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PipelinesService_ServiceDesc.Streams[0], PipelinesService_StreamPipelines_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPipelinesRequest, StreamPipelinesEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PipelinesService_StreamPipelinesClient = grpc.ServerStreamingClient[StreamPipelinesEvent]

func (c *pipelinesServiceClient) OpenLogStream(ctx context.Context, in *OpenLogStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamMessages], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PipelinesService_ServiceDesc.Streams[1], PipelinesService_OpenLogStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenLogStreamRequest, LogStreamMessages]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PipelinesService_OpenLogStreamClient = grpc.ServerStreamingClient[LogStreamMessages]

func (c *pipelinesServiceClient) OpenTelemetryStream(ctx context.Context, in *OpenTelemetryStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetrySample], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PipelinesService_ServiceDesc.Streams[2], PipelinesService_OpenTelemetryStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenTelemetryStreamRequest, TelemetrySample]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PipelinesService_OpenTelemetryStreamClient = grpc.ServerStreamingClient[TelemetrySample]

// PipelinesServiceServer is the server API for PipelinesService service.
// All implementations must embed UnimplementedPipelinesServiceServer
// for forward compatibility.
//
// A pipeline is the configuration a node runs to move traffic, connecting components such as UDP sockets, TUN
// interfaces and error correction encoders into a data flow. Each start of a pipeline creates a new run, with its own
// logs and telemetry. Use this service to create, change, start and stop pipelines on any node, and to follow their
// changes, logs and telemetry.
type PipelinesServiceServer interface {
	// Lists all pipelines on the node.
	GetPipelines(context.Context, *GetPipelinesRequest) (*GetPipelinesResponse, error)
	// Get one pipeline. Fails with a not found error if it does not exist.
	GetPipelineById(context.Context, *GetPipelineByIdRequest) (*GetPipelineByIdResponse, error)
	// Get one pipeline by name. Fails with a not found error if no pipeline, or more than one, has that name.
	GetPipelineByName(context.Context, *GetPipelineByNameRequest) (*GetPipelineByNameResponse, error)
	// Get the pipeline that a run belongs to. An unknown run fails with a timeout error.
	GetPipelineByRunId(context.Context, *GetPipelineByRunIdRequest) (*GetPipelineByRunIdResponse, error)
	// Create a pipeline from a JSON configuration and return it. The pipeline is not started. Fails with an invalid
	// argument error if the configuration is invalid or the CPU pin is not a thread of the node.
	CreatePipeline(context.Context, *CreatePipelineRequest) (*CreatePipelineResponse, error)
	// Replace the settings of a pipeline and return the updated pipeline. If the pipeline is running and its
	// configuration changed, the new configuration is applied to the current run. If that is not possible, the call fails
	// because the pipeline is running, unless a restart is forced.
	UpdatePipeline(context.Context, *UpdatePipelineRequest) (*UpdatePipelineResponse, error)
	// Delete a pipeline. Fails with a not found error if it does not exist.
	DeletePipeline(context.Context, *DeletePipelineRequest) (*DeletePipelineResponse, error)
	// Start a pipeline and return its new run once it is running. Fails if the pipeline is unknown, already started, or
	// does not reach the running state within 10 seconds.
	StartPipeline(context.Context, *StartPipelineRequest) (*StartPipelineResponse, error)
	// Stop a pipeline, found by its ID, its name or its current run. Returns once the stop is requested, without waiting
	// for the run to end. Fails if the pipeline is unknown or already stopped.
	StopPipeline(context.Context, *StopPipelineRequest) (*StopPipelineResponse, error)
	// Stream changes to the pipelines of a node. Nothing is sent when the stream opens, so get the pipelines first for
	// the current list. An event is sent each time a pipeline is created, updated or deleted, and when a pipeline starts
	// or stops.
	StreamPipelines(*StreamPipelinesRequest, grpc.ServerStreamingServer[StreamPipelinesEvent]) error
	// Stream the log messages of a pipeline run. The requested number of past lines is sent first, then new messages as
	// they are logged.
	OpenLogStream(*OpenLogStreamRequest, grpc.ServerStreamingServer[LogStreamMessages]) error
	// Streams telemetry samples (metrics and KPI values) of a pipeline run at regular intervals while the run is active.
	// The stream ends with an error when the run stops, when the run is unknown, or when the node disconnects.
	OpenTelemetryStream(*OpenTelemetryStreamRequest, grpc.ServerStreamingServer[TelemetrySample]) error
	mustEmbedUnimplementedPipelinesServiceServer()
}

// UnimplementedPipelinesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPipelinesServiceServer struct{}

func (UnimplementedPipelinesServiceServer) GetPipelines(context.Context, *GetPipelinesRequest) (*GetPipelinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPipelines not implemented")
}
func (UnimplementedPipelinesServiceServer) GetPipelineById(context.Context, *GetPipelineByIdRequest) (*GetPipelineByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPipelineById not implemented")
}
func (UnimplementedPipelinesServiceServer) GetPipelineByName(context.Context, *GetPipelineByNameRequest) (*GetPipelineByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPipelineByName not implemented")
}
func (UnimplementedPipelinesServiceServer) GetPipelineByRunId(context.Context, *GetPipelineByRunIdRequest) (*GetPipelineByRunIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPipelineByRunId not implemented")
}
func (UnimplementedPipelinesServiceServer) CreatePipeline(context.Context, *CreatePipelineRequest) (*CreatePipelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePipeline not implemented")
}
func (UnimplementedPipelinesServiceServer) UpdatePipeline(context.Context, *UpdatePipelineRequest) (*UpdatePipelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePipeline not implemented")
}
func (UnimplementedPipelinesServiceServer) DeletePipeline(context.Context, *DeletePipelineRequest) (*DeletePipelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePipeline not implemented")
}
func (UnimplementedPipelinesServiceServer) StartPipeline(context.Context, *StartPipelineRequest) (*StartPipelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPipeline not implemented")
}
func (UnimplementedPipelinesServiceServer) StopPipeline(context.Context, *StopPipelineRequest) (*StopPipelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopPipeline not implemented")
}
func (UnimplementedPipelinesServiceServer) StreamPipelines(*StreamPipelinesRequest, grpc.ServerStreamingServer[StreamPipelinesEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamPipelines not implemented")
}
func (UnimplementedPipelinesServiceServer) OpenLogStream(*OpenLogStreamRequest, grpc.ServerStreamingServer[LogStreamMessages]) error {
	return status.Errorf(codes.Unimplemented, "method OpenLogStream not implemented")
}
func (UnimplementedPipelinesServiceServer) OpenTelemetryStream(*OpenTelemetryStreamRequest, grpc.ServerStreamingServer[TelemetrySample]) error {
	return status.Errorf(codes.Unimplemented, "method OpenTelemetryStream not implemented")
}
func (UnimplementedPipelinesServiceServer) mustEmbedUnimplementedPipelinesServiceServer() {}
func (UnimplementedPipelinesServiceServer) testEmbeddedByValue()                          {}

// UnsafePipelinesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PipelinesServiceServer will
// result in compilation errors.
type UnsafePipelinesServiceServer interface {
	mustEmbedUnimplementedPipelinesServiceServer()
}

func RegisterPipelinesServiceServer(s grpc.ServiceRegistrar, srv PipelinesServiceServer) {
	// If the following call pancis, it indicates UnimplementedPipelinesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PipelinesService_ServiceDesc, srv)
}

func _PipelinesService_GetPipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServiceServer).GetPipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelinesService_GetPipelines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServiceServer).GetPipelines(ctx, req.(*GetPipelinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelinesService_GetPipelineById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServiceServer).GetPipelineById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelinesService_GetPipelineById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServiceServer).GetPipelineById(ctx, req.(*GetPipelineByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelinesService_GetPipelineByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServiceServer).GetPipelineByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelinesService_GetPipelineByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServiceServer).GetPipelineByName(ctx, req.(*GetPipelineByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelinesService_GetPipelineByRunId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineByRunIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServiceServer).GetPipelineByRunId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelinesService_GetPipelineByRunId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServiceServer).GetPipelineByRunId(ctx, req.(*GetPipelineByRunIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelinesService_CreatePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServiceServer).CreatePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelinesService_CreatePipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServiceServer).CreatePipeline(ctx, req.(*CreatePipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelinesService_UpdatePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServiceServer).UpdatePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelinesService_UpdatePipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServiceServer).UpdatePipeline(ctx, req.(*UpdatePipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelinesService_DeletePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServiceServer).DeletePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelinesService_DeletePipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServiceServer).DeletePipeline(ctx, req.(*DeletePipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelinesService_StartPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServiceServer).StartPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelinesService_StartPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServiceServer).StartPipeline(ctx, req.(*StartPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelinesService_StopPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServiceServer).StopPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelinesService_StopPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServiceServer).StopPipeline(ctx, req.(*StopPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelinesService_StreamPipelines_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPipelinesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PipelinesServiceServer).StreamPipelines(m, &grpc.GenericServerStream[StreamPipelinesRequest, StreamPipelinesEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PipelinesService_StreamPipelinesServer = grpc.ServerStreamingServer[StreamPipelinesEvent]

func _PipelinesService_OpenLogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpenLogStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PipelinesServiceServer).OpenLogStream(m, &grpc.GenericServerStream[OpenLogStreamRequest, LogStreamMessages]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PipelinesService_OpenLogStreamServer = grpc.ServerStreamingServer[LogStreamMessages]

func _PipelinesService_OpenTelemetryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpenTelemetryStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PipelinesServiceServer).OpenTelemetryStream(m, &grpc.GenericServerStream[OpenTelemetryStreamRequest, TelemetrySample]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PipelinesService_OpenTelemetryStreamServer = grpc.ServerStreamingServer[TelemetrySample]

// PipelinesService_ServiceDesc is the grpc.ServiceDesc for PipelinesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PipelinesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanopinggrpc.pipeline.PipelinesService",
	HandlerType: (*PipelinesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getPipelines",
			Handler:    _PipelinesService_GetPipelines_Handler,
		},
		{
			MethodName: "getPipelineById",
			Handler:    _PipelinesService_GetPipelineById_Handler,
		},
		{
			MethodName: "getPipelineByName",
			Handler:    _PipelinesService_GetPipelineByName_Handler,
		},
		{
			MethodName: "getPipelineByRunId",
			Handler:    _PipelinesService_GetPipelineByRunId_Handler,
		},
		{
			MethodName: "createPipeline",
			Handler:    _PipelinesService_CreatePipeline_Handler,
		},
		{
			MethodName: "updatePipeline",
			Handler:    _PipelinesService_UpdatePipeline_Handler,
		},
		{
			MethodName: "deletePipeline",
			Handler:    _PipelinesService_DeletePipeline_Handler,
		},
		{
			MethodName: "startPipeline",
			Handler:    _PipelinesService_StartPipeline_Handler,
		},
		{
			MethodName: "stopPipeline",
			Handler:    _PipelinesService_StopPipeline_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamPipelines",
			Handler:       _PipelinesService_StreamPipelines_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "openLogStream",
			Handler:       _PipelinesService_OpenLogStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "openTelemetryStream",
			Handler:       _PipelinesService_OpenTelemetryStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pipelines.proto",
}
