// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: config.proto

package config

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigService_GetDefaultNetworkCarriers_FullMethodName = "/nanopinggrpc.hub.ConfigService/getDefaultNetworkCarriers"
	ConfigService_SetDefaultNetworkCarriers_FullMethodName = "/nanopinggrpc.hub.ConfigService/setDefaultNetworkCarriers"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Settings stored in the configuration of a node. Use this service to read and change them on any node, such as the
// carriers a node uses by default when it joins a network.
type ConfigServiceClient interface {
	// Get the default network carriers of a node. These are the carriers the node receives every time it joins a new
	// network. Returns an empty list when none are configured.
	GetDefaultNetworkCarriers(ctx context.Context, in *GetDefaultNetworkCarriersRequest, opts ...grpc.CallOption) (*GetDefaultNetworkCarriersResponse, error)
	// Replace the default network carriers of a node. The new carriers apply to networks the node joins afterwards.
	SetDefaultNetworkCarriers(ctx context.Context, in *SetDefaultNetworkCarriersRequest, opts ...grpc.CallOption) (*SetDefaultNetworkCarriersResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) GetDefaultNetworkCarriers(ctx context.Context, in *GetDefaultNetworkCarriersRequest, opts ...grpc.CallOption) (*GetDefaultNetworkCarriersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDefaultNetworkCarriersResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetDefaultNetworkCarriers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) SetDefaultNetworkCarriers(ctx context.Context, in *SetDefaultNetworkCarriersRequest, opts ...grpc.CallOption) (*SetDefaultNetworkCarriersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDefaultNetworkCarriersResponse)
	err := c.cc.Invoke(ctx, ConfigService_SetDefaultNetworkCarriers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility.
//
// Settings stored in the configuration of a node. Use this service to read and change them on any node, such as the
// carriers a node uses by default when it joins a network.
type ConfigServiceServer interface {
	// Get the default network carriers of a node. These are the carriers the node receives every time it joins a new
	// network. Returns an empty list when none are configured.
	GetDefaultNetworkCarriers(context.Context, *GetDefaultNetworkCarriersRequest) (*GetDefaultNetworkCarriersResponse, error)
	// Replace the default network carriers of a node. The new carriers apply to networks the node joins afterwards.
	SetDefaultNetworkCarriers(context.Context, *SetDefaultNetworkCarriersRequest) (*SetDefaultNetworkCarriersResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) GetDefaultNetworkCarriers(context.Context, *GetDefaultNetworkCarriersRequest) (*GetDefaultNetworkCarriersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefaultNetworkCarriers not implemented")
}
func (UnimplementedConfigServiceServer) SetDefaultNetworkCarriers(context.Context, *SetDefaultNetworkCarriersRequest) (*SetDefaultNetworkCarriersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultNetworkCarriers not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_GetDefaultNetworkCarriers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultNetworkCarriersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetDefaultNetworkCarriers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetDefaultNetworkCarriers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetDefaultNetworkCarriers(ctx, req.(*GetDefaultNetworkCarriersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_SetDefaultNetworkCarriers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultNetworkCarriersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).SetDefaultNetworkCarriers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_SetDefaultNetworkCarriers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).SetDefaultNetworkCarriers(ctx, req.(*SetDefaultNetworkCarriersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanopinggrpc.hub.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getDefaultNetworkCarriers",
			Handler:    _ConfigService_GetDefaultNetworkCarriers_Handler,
		},
		{
			MethodName: "setDefaultNetworkCarriers",
			Handler:    _ConfigService_SetDefaultNetworkCarriers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}
