// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.31.0
// source: config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A list of default network carriers.
type DefaultNetworkCarriers struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The default network carriers.
	Carriers      []*DefaultNetworkCarrier `protobuf:"bytes,2,rep,name=carriers,proto3" json:"carriers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultNetworkCarriers) Reset() {
	*x = DefaultNetworkCarriers{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultNetworkCarriers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultNetworkCarriers) ProtoMessage() {}

func (x *DefaultNetworkCarriers) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultNetworkCarriers.ProtoReflect.Descriptor instead.
func (*DefaultNetworkCarriers) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *DefaultNetworkCarriers) GetCarriers() []*DefaultNetworkCarrier {
	if x != nil {
		return x.Carriers
	}
	return nil
}

// A carrier a node receives every time it joins a new network. Every setting is optional.
type DefaultNetworkCarrier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional address of the carrier.
	//
	// Types that are valid to be assigned to OptionalAddress:
	//
	//	*DefaultNetworkCarrier_Address
	OptionalAddress isDefaultNetworkCarrier_OptionalAddress `protobuf_oneof:"optional_address"`
	// Optional network interface of the carrier.
	//
	// Types that are valid to be assigned to OptionalInterface:
	//
	//	*DefaultNetworkCarrier_Interface
	OptionalInterface isDefaultNetworkCarrier_OptionalInterface `protobuf_oneof:"optional_interface"`
	// Optional bandwidth priority of the carrier.
	//
	// Types that are valid to be assigned to OptionalBandwidthPriority:
	//
	//	*DefaultNetworkCarrier_BandwidthPriority
	OptionalBandwidthPriority isDefaultNetworkCarrier_OptionalBandwidthPriority `protobuf_oneof:"optional_bandwidth_priority"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DefaultNetworkCarrier) Reset() {
	*x = DefaultNetworkCarrier{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultNetworkCarrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultNetworkCarrier) ProtoMessage() {}

func (x *DefaultNetworkCarrier) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultNetworkCarrier.ProtoReflect.Descriptor instead.
func (*DefaultNetworkCarrier) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultNetworkCarrier) GetOptionalAddress() isDefaultNetworkCarrier_OptionalAddress {
	if x != nil {
		return x.OptionalAddress
	}
	return nil
}

func (x *DefaultNetworkCarrier) GetAddress() *DefaultNetworkCarrierAddress {
	if x != nil {
		if x, ok := x.OptionalAddress.(*DefaultNetworkCarrier_Address); ok {
			return x.Address
		}
	}
	return nil
}

func (x *DefaultNetworkCarrier) GetOptionalInterface() isDefaultNetworkCarrier_OptionalInterface {
	if x != nil {
		return x.OptionalInterface
	}
	return nil
}

func (x *DefaultNetworkCarrier) GetInterface() string {
	if x != nil {
		if x, ok := x.OptionalInterface.(*DefaultNetworkCarrier_Interface); ok {
			return x.Interface
		}
	}
	return ""
}

func (x *DefaultNetworkCarrier) GetOptionalBandwidthPriority() isDefaultNetworkCarrier_OptionalBandwidthPriority {
	if x != nil {
		return x.OptionalBandwidthPriority
	}
	return nil
}

func (x *DefaultNetworkCarrier) GetBandwidthPriority() uint32 {
	if x != nil {
		if x, ok := x.OptionalBandwidthPriority.(*DefaultNetworkCarrier_BandwidthPriority); ok {
			return x.BandwidthPriority
		}
	}
	return 0
}

type isDefaultNetworkCarrier_OptionalAddress interface {
	isDefaultNetworkCarrier_OptionalAddress()
}

type DefaultNetworkCarrier_Address struct {
	// Address the carrier uses.
	Address *DefaultNetworkCarrierAddress `protobuf:"bytes,1,opt,name=address,proto3,oneof"`
}

func (*DefaultNetworkCarrier_Address) isDefaultNetworkCarrier_OptionalAddress() {}

type isDefaultNetworkCarrier_OptionalInterface interface {
	isDefaultNetworkCarrier_OptionalInterface()
}

type DefaultNetworkCarrier_Interface struct {
	// Name of the network interface the carrier uses. Example: `eth0`
	Interface string `protobuf:"bytes,2,opt,name=interface,proto3,oneof"`
}

func (*DefaultNetworkCarrier_Interface) isDefaultNetworkCarrier_OptionalInterface() {}

type isDefaultNetworkCarrier_OptionalBandwidthPriority interface {
	isDefaultNetworkCarrier_OptionalBandwidthPriority()
}

type DefaultNetworkCarrier_BandwidthPriority struct {
	// Bandwidth priority of the carrier. Example: `100`
	BandwidthPriority uint32 `protobuf:"varint,3,opt,name=bandwidth_priority,json=bandwidthPriority,proto3,oneof"`
}

func (*DefaultNetworkCarrier_BandwidthPriority) isDefaultNetworkCarrier_OptionalBandwidthPriority() {}

// Address of a default network carrier.
type DefaultNetworkCarrierAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP address of the carrier. Example: `192.168.1.20`
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Port of the carrier. Example: `3425`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Optional external IP address of the carrier.
	//
	// Types that are valid to be assigned to OptionalExternalIp:
	//
	//	*DefaultNetworkCarrierAddress_ExternalIp
	OptionalExternalIp isDefaultNetworkCarrierAddress_OptionalExternalIp `protobuf_oneof:"optional_external_ip"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DefaultNetworkCarrierAddress) Reset() {
	*x = DefaultNetworkCarrierAddress{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultNetworkCarrierAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultNetworkCarrierAddress) ProtoMessage() {}

func (x *DefaultNetworkCarrierAddress) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultNetworkCarrierAddress.ProtoReflect.Descriptor instead.
func (*DefaultNetworkCarrierAddress) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *DefaultNetworkCarrierAddress) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DefaultNetworkCarrierAddress) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DefaultNetworkCarrierAddress) GetOptionalExternalIp() isDefaultNetworkCarrierAddress_OptionalExternalIp {
	if x != nil {
		return x.OptionalExternalIp
	}
	return nil
}

func (x *DefaultNetworkCarrierAddress) GetExternalIp() string {
	if x != nil {
		if x, ok := x.OptionalExternalIp.(*DefaultNetworkCarrierAddress_ExternalIp); ok {
			return x.ExternalIp
		}
	}
	return ""
}

type isDefaultNetworkCarrierAddress_OptionalExternalIp interface {
	isDefaultNetworkCarrierAddress_OptionalExternalIp()
}

type DefaultNetworkCarrierAddress_ExternalIp struct {
	// IP address the carrier is reachable at from outside, for example behind NAT. Example: `203.0.113.10`
	ExternalIp string `protobuf:"bytes,3,opt,name=external_ip,json=externalIp,proto3,oneof"`
}

func (*DefaultNetworkCarrierAddress_ExternalIp) isDefaultNetworkCarrierAddress_OptionalExternalIp() {}

// Request for getDefaultNetworkCarriers.
type GetDefaultNetworkCarriersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the node to read the default network carriers from.
	NodeId        string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultNetworkCarriersRequest) Reset() {
	*x = GetDefaultNetworkCarriersRequest{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultNetworkCarriersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultNetworkCarriersRequest) ProtoMessage() {}

func (x *GetDefaultNetworkCarriersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultNetworkCarriersRequest.ProtoReflect.Descriptor instead.
func (*GetDefaultNetworkCarriersRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *GetDefaultNetworkCarriersRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// Response for getDefaultNetworkCarriers.
type GetDefaultNetworkCarriersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The default network carriers of the node. Empty when none are configured.
	Carriers      []*DefaultNetworkCarrier `protobuf:"bytes,1,rep,name=carriers,proto3" json:"carriers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultNetworkCarriersResponse) Reset() {
	*x = GetDefaultNetworkCarriersResponse{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultNetworkCarriersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultNetworkCarriersResponse) ProtoMessage() {}

func (x *GetDefaultNetworkCarriersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultNetworkCarriersResponse.ProtoReflect.Descriptor instead.
func (*GetDefaultNetworkCarriersResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *GetDefaultNetworkCarriersResponse) GetCarriers() []*DefaultNetworkCarrier {
	if x != nil {
		return x.Carriers
	}
	return nil
}

// Request for setDefaultNetworkCarriers.
type SetDefaultNetworkCarriersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the node to set the default network carriers on.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Optional new default network carriers.
	//
	// Types that are valid to be assigned to OptionalCarriers:
	//
	//	*SetDefaultNetworkCarriersRequest_Carriers
	OptionalCarriers isSetDefaultNetworkCarriersRequest_OptionalCarriers `protobuf_oneof:"optional_carriers"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetDefaultNetworkCarriersRequest) Reset() {
	*x = SetDefaultNetworkCarriersRequest{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultNetworkCarriersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultNetworkCarriersRequest) ProtoMessage() {}

func (x *SetDefaultNetworkCarriersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultNetworkCarriersRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultNetworkCarriersRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *SetDefaultNetworkCarriersRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SetDefaultNetworkCarriersRequest) GetOptionalCarriers() isSetDefaultNetworkCarriersRequest_OptionalCarriers {
	if x != nil {
		return x.OptionalCarriers
	}
	return nil
}

func (x *SetDefaultNetworkCarriersRequest) GetCarriers() *DefaultNetworkCarriers {
	if x != nil {
		if x, ok := x.OptionalCarriers.(*SetDefaultNetworkCarriersRequest_Carriers); ok {
			return x.Carriers
		}
	}
	return nil
}

type isSetDefaultNetworkCarriersRequest_OptionalCarriers interface {
	isSetDefaultNetworkCarriersRequest_OptionalCarriers()
}

type SetDefaultNetworkCarriersRequest_Carriers struct {
	// The new default network carriers, replacing the current ones. Leave unset to remove all default carriers.
	Carriers *DefaultNetworkCarriers `protobuf:"bytes,2,opt,name=carriers,proto3,oneof"`
}

func (*SetDefaultNetworkCarriersRequest_Carriers) isSetDefaultNetworkCarriersRequest_OptionalCarriers() {
}

// Response for setDefaultNetworkCarriers.
type SetDefaultNetworkCarriersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultNetworkCarriersResponse) Reset() {
	*x = SetDefaultNetworkCarriersResponse{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultNetworkCarriersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultNetworkCarriersResponse) ProtoMessage() {}

func (x *SetDefaultNetworkCarriersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultNetworkCarriersResponse.ProtoReflect.Descriptor instead.
func (*SetDefaultNetworkCarriersResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

var File_config_proto protoreflect.FileDescriptor

var file_config_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62,
	0x22, 0x5d, 0x0a, 0x16, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x12, 0x43, 0x0a, 0x08, 0x63, 0x61,
	0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6e,
	0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61,
	0x72, 0x72, 0x69, 0x65, 0x72, 0x52, 0x08, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x22,
	0xfd, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6e, 0x61, 0x6e,
	0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61, 0x72, 0x72,
	0x69, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x12, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x5f, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x02, 0x52, 0x11, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x50, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x42, 0x12, 0x0a, 0x10, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x14, 0x0a, 0x12, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x42, 0x1d, 0x0a, 0x1b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x62, 0x61, 0x6e,
	0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x22,
	0x7d, 0x0a, 0x1c, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f,
	0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x49, 0x70, 0x42, 0x16, 0x0a, 0x14, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x70, 0x22, 0x3b,
	0x0a, 0x20, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x21, 0x47,
	0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x43, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x52, 0x08, 0x63, 0x61, 0x72,
	0x72, 0x69, 0x65, 0x72, 0x73, 0x22, 0x98, 0x01, 0x0a, 0x20, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61, 0x72, 0x72, 0x69,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x12, 0x46, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x48,
	0x00, 0x52, 0x08, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x42, 0x13, 0x0a, 0x11, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73,
	0x22, 0x23, 0x0a, 0x21, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa1, 0x02, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x86, 0x01, 0x0a, 0x19, 0x67, 0x65, 0x74, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61, 0x72,
	0x72, 0x69, 0x65, 0x72, 0x73, 0x12, 0x32, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x6e, 0x61, 0x6e, 0x6f,
	0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61,
	0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x86, 0x01, 0x0a, 0x19, 0x73, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x12, 0x32,
	0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x75,
	0x62, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x33, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x6e, 0x61, 0x6e,
	0x6f, 0x70, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_config_proto_goTypes = []any{
	(*DefaultNetworkCarriers)(nil),            // 0: nanopinggrpc.hub.DefaultNetworkCarriers
	(*DefaultNetworkCarrier)(nil),             // 1: nanopinggrpc.hub.DefaultNetworkCarrier
	(*DefaultNetworkCarrierAddress)(nil),      // 2: nanopinggrpc.hub.DefaultNetworkCarrierAddress
	(*GetDefaultNetworkCarriersRequest)(nil),  // 3: nanopinggrpc.hub.GetDefaultNetworkCarriersRequest
	(*GetDefaultNetworkCarriersResponse)(nil), // 4: nanopinggrpc.hub.GetDefaultNetworkCarriersResponse
	(*SetDefaultNetworkCarriersRequest)(nil),  // 5: nanopinggrpc.hub.SetDefaultNetworkCarriersRequest
	(*SetDefaultNetworkCarriersResponse)(nil), // 6: nanopinggrpc.hub.SetDefaultNetworkCarriersResponse
}
var file_config_proto_depIdxs = []int32{
	1, // 0: nanopinggrpc.hub.DefaultNetworkCarriers.carriers:type_name -> nanopinggrpc.hub.DefaultNetworkCarrier
	2, // 1: nanopinggrpc.hub.DefaultNetworkCarrier.address:type_name -> nanopinggrpc.hub.DefaultNetworkCarrierAddress
	1, // 2: nanopinggrpc.hub.GetDefaultNetworkCarriersResponse.carriers:type_name -> nanopinggrpc.hub.DefaultNetworkCarrier
	0, // 3: nanopinggrpc.hub.SetDefaultNetworkCarriersRequest.carriers:type_name -> nanopinggrpc.hub.DefaultNetworkCarriers
	3, // 4: nanopinggrpc.hub.ConfigService.getDefaultNetworkCarriers:input_type -> nanopinggrpc.hub.GetDefaultNetworkCarriersRequest
	5, // 5: nanopinggrpc.hub.ConfigService.setDefaultNetworkCarriers:input_type -> nanopinggrpc.hub.SetDefaultNetworkCarriersRequest
	4, // 6: nanopinggrpc.hub.ConfigService.getDefaultNetworkCarriers:output_type -> nanopinggrpc.hub.GetDefaultNetworkCarriersResponse
	6, // 7: nanopinggrpc.hub.ConfigService.setDefaultNetworkCarriers:output_type -> nanopinggrpc.hub.SetDefaultNetworkCarriersResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_config_proto_msgTypes[1].OneofWrappers = []any{
		(*DefaultNetworkCarrier_Address)(nil),
		(*DefaultNetworkCarrier_Interface)(nil),
		(*DefaultNetworkCarrier_BandwidthPriority)(nil),
	}
	file_config_proto_msgTypes[2].OneofWrappers = []any{
		(*DefaultNetworkCarrierAddress_ExternalIp)(nil),
	}
	file_config_proto_msgTypes[5].OneofWrappers = []any{
		(*SetDefaultNetworkCarriersRequest_Carriers)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
