// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: hub_server.proto

package hub_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HubServerService_GetNodes_FullMethodName                 = "/nanopinggrpc.hub.HubServerService/getNodes"
	HubServerService_RemoveNode_FullMethodName               = "/nanopinggrpc.hub.HubServerService/removeNode"
	HubServerService_StreamNodes_FullMethodName              = "/nanopinggrpc.hub.HubServerService/streamNodes"
	HubServerService_AuthenticationByRequests_FullMethodName = "/nanopinggrpc.hub.HubServerService/authenticationByRequests"
)

// HubServerServiceClient is the client API for HubServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A hub server is the control plane of a NanoPing setup: nodes authenticate with it, and every node on the same hub can
// find and manage the others. Use this service to list the nodes on the hub, follow them as they come and go, remove
// nodes, and approve or reject nodes that ask to join. The node hosting the API must host the hub server or be
// authenticated with one, otherwise calls fail with FailedPrecondition.
type HubServerServiceClient interface {
	// Get the nodes authenticated with the hub server, optionally filtered.
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
	// Remove a node from the hub server. This disconnects the node from the hub server and removes it from its networks.
	RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*RemoveNodeResponse, error)
	// Stream the nodes authenticated with the hub server. The matching nodes are sent first, followed by an update every
	// time a node is authenticated, deauthenticated, connects, disconnects or changes its details. Updates are not
	// filtered. The stream stays open until the caller closes it.
	StreamNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamNodesResponse], error)
	// Receive the authentication requests sent to the hub server on the node hosting the API, and accept or reject each
	// one. Nothing is sent when the stream opens. A request is sent each time a node asks to authenticate, and the caller
	// answers it by sending an answer for that request.
	AuthenticationByRequests(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AuthenticationByRequestAnswer, AuthenticationByRequestRequest], error)
}

type hubServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHubServerServiceClient(cc grpc.ClientConnInterface) HubServerServiceClient {
	return &hubServerServiceClient{cc}
}

func (c *hubServerServiceClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, HubServerService_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServerServiceClient) RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*RemoveNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveNodeResponse)
	err := c.cc.Invoke(ctx, HubServerService_RemoveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServerServiceClient) StreamNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamNodesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubServerService_ServiceDesc.Streams[0], HubServerService_StreamNodes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetNodesRequest, StreamNodesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubServerService_StreamNodesClient = grpc.ServerStreamingClient[StreamNodesResponse]

func (c *hubServerServiceClient) AuthenticationByRequests(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AuthenticationByRequestAnswer, AuthenticationByRequestRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubServerService_ServiceDesc.Streams[1], HubServerService_AuthenticationByRequests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuthenticationByRequestAnswer, AuthenticationByRequestRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubServerService_AuthenticationByRequestsClient = grpc.BidiStreamingClient[AuthenticationByRequestAnswer, AuthenticationByRequestRequest]

// HubServerServiceServer is the server API for HubServerService service.
// All implementations must embed UnimplementedHubServerServiceServer
// for forward compatibility.
//
// A hub server is the control plane of a NanoPing setup: nodes authenticate with it, and every node on the same hub can
// find and manage the others. Use this service to list the nodes on the hub, follow them as they come and go, remove
// nodes, and approve or reject nodes that ask to join. The node hosting the API must host the hub server or be
// authenticated with one, otherwise calls fail with FailedPrecondition.
type HubServerServiceServer interface {
	// Get the nodes authenticated with the hub server, optionally filtered.
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
	// Remove a node from the hub server. This disconnects the node from the hub server and removes it from its networks.
	RemoveNode(context.Context, *RemoveNodeRequest) (*RemoveNodeResponse, error)
	// Stream the nodes authenticated with the hub server. The matching nodes are sent first, followed by an update every
	// time a node is authenticated, deauthenticated, connects, disconnects or changes its details. Updates are not
	// filtered. The stream stays open until the caller closes it.
	StreamNodes(*GetNodesRequest, grpc.ServerStreamingServer[StreamNodesResponse]) error
	// Receive the authentication requests sent to the hub server on the node hosting the API, and accept or reject each
	// one. Nothing is sent when the stream opens. A request is sent each time a node asks to authenticate, and the caller
	// answers it by sending an answer for that request.
	AuthenticationByRequests(grpc.BidiStreamingServer[AuthenticationByRequestAnswer, AuthenticationByRequestRequest]) error
	mustEmbedUnimplementedHubServerServiceServer()
}

// UnimplementedHubServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHubServerServiceServer struct{}

func (UnimplementedHubServerServiceServer) GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedHubServerServiceServer) RemoveNode(context.Context, *RemoveNodeRequest) (*RemoveNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNode not implemented")
}
func (UnimplementedHubServerServiceServer) StreamNodes(*GetNodesRequest, grpc.ServerStreamingServer[StreamNodesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamNodes not implemented")
}
func (UnimplementedHubServerServiceServer) AuthenticationByRequests(grpc.BidiStreamingServer[AuthenticationByRequestAnswer, AuthenticationByRequestRequest]) error {
	return status.Errorf(codes.Unimplemented, "method AuthenticationByRequests not implemented")
}
func (UnimplementedHubServerServiceServer) mustEmbedUnimplementedHubServerServiceServer() {}
func (UnimplementedHubServerServiceServer) testEmbeddedByValue()                          {}

// UnsafeHubServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubServerServiceServer will
// result in compilation errors.
type UnsafeHubServerServiceServer interface {
	mustEmbedUnimplementedHubServerServiceServer()
}

func RegisterHubServerServiceServer(s grpc.ServiceRegistrar, srv HubServerServiceServer) {
	// If the following call pancis, it indicates UnimplementedHubServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HubServerService_ServiceDesc, srv)
}

func _HubServerService_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServerServiceServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubServerService_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServerServiceServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubServerService_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServerServiceServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubServerService_RemoveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServerServiceServer).RemoveNode(ctx, req.(*RemoveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubServerService_StreamNodes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetNodesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubServerServiceServer).StreamNodes(m, &grpc.GenericServerStream[GetNodesRequest, StreamNodesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubServerService_StreamNodesServer = grpc.ServerStreamingServer[StreamNodesResponse]

func _HubServerService_AuthenticationByRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HubServerServiceServer).AuthenticationByRequests(&grpc.GenericServerStream[AuthenticationByRequestAnswer, AuthenticationByRequestRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubServerService_AuthenticationByRequestsServer = grpc.BidiStreamingServer[AuthenticationByRequestAnswer, AuthenticationByRequestRequest]

// HubServerService_ServiceDesc is the grpc.ServiceDesc for HubServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanopinggrpc.hub.HubServerService",
	HandlerType: (*HubServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getNodes",
			Handler:    _HubServerService_GetNodes_Handler,
		},
		{
			MethodName: "removeNode",
			Handler:    _HubServerService_RemoveNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamNodes",
			Handler:       _HubServerService_StreamNodes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "authenticationByRequests",
			Handler:       _HubServerService_AuthenticationByRequests_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hub_server.proto",
}
