// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.31.0
// source: metrics.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How the value of a metric changes over time.
type Kind int32

const (
	// The value can both increase and decrease, for example memory in use.
	Kind_GAUGE Kind = 0
	// The value can only increase, for example a total byte count.
	Kind_COUNTER Kind = 1
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "GAUGE",
		1: "COUNTER",
	}
	Kind_value = map[string]int32{
		"GAUGE":   0,
		"COUNTER": 1,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_metrics_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

// A metric holding an unsigned 64-bit integer value.
type UInt64Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current value of the metric.
	//
	// Types that are valid to be assigned to OptionalValue:
	//
	//	*UInt64Metric_Value
	OptionalValue isUInt64Metric_OptionalValue `protobuf_oneof:"optional_value"`
	// Human-readable description of what the metric measures.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Whether the value can only increase or can also decrease.
	Kind Kind `protobuf:"varint,3,opt,name=kind,proto3,enum=nanopinggrpc.metrics.Kind" json:"kind,omitempty"`
	// The unit of the value.
	//
	// Types that are valid to be assigned to OptionalUnit:
	//
	//	*UInt64Metric_Unit
	OptionalUnit isUInt64Metric_OptionalUnit `protobuf_oneof:"optional_unit"`
	// The lowest value the metric can take.
	//
	// Types that are valid to be assigned to OptionalMin:
	//
	//	*UInt64Metric_Min
	OptionalMin isUInt64Metric_OptionalMin `protobuf_oneof:"optional_min"`
	// The highest value the metric can take.
	//
	// Types that are valid to be assigned to OptionalMax:
	//
	//	*UInt64Metric_Max
	OptionalMax   isUInt64Metric_OptionalMax `protobuf_oneof:"optional_max"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UInt64Metric) Reset() {
	*x = UInt64Metric{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UInt64Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInt64Metric) ProtoMessage() {}

func (x *UInt64Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInt64Metric.ProtoReflect.Descriptor instead.
func (*UInt64Metric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *UInt64Metric) GetOptionalValue() isUInt64Metric_OptionalValue {
	if x != nil {
		return x.OptionalValue
	}
	return nil
}

func (x *UInt64Metric) GetValue() uint64 {
	if x != nil {
		if x, ok := x.OptionalValue.(*UInt64Metric_Value); ok {
			return x.Value
		}
	}
	return 0
}

func (x *UInt64Metric) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UInt64Metric) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_GAUGE
}

func (x *UInt64Metric) GetOptionalUnit() isUInt64Metric_OptionalUnit {
	if x != nil {
		return x.OptionalUnit
	}
	return nil
}

func (x *UInt64Metric) GetUnit() string {
	if x != nil {
		if x, ok := x.OptionalUnit.(*UInt64Metric_Unit); ok {
			return x.Unit
		}
	}
	return ""
}

func (x *UInt64Metric) GetOptionalMin() isUInt64Metric_OptionalMin {
	if x != nil {
		return x.OptionalMin
	}
	return nil
}

func (x *UInt64Metric) GetMin() uint64 {
	if x != nil {
		if x, ok := x.OptionalMin.(*UInt64Metric_Min); ok {
			return x.Min
		}
	}
	return 0
}

func (x *UInt64Metric) GetOptionalMax() isUInt64Metric_OptionalMax {
	if x != nil {
		return x.OptionalMax
	}
	return nil
}

func (x *UInt64Metric) GetMax() uint64 {
	if x != nil {
		if x, ok := x.OptionalMax.(*UInt64Metric_Max); ok {
			return x.Max
		}
	}
	return 0
}

type isUInt64Metric_OptionalValue interface {
	isUInt64Metric_OptionalValue()
}

type UInt64Metric_Value struct {
	// The value. Unset when the metric has no value in this sample.
	Value uint64 `protobuf:"varint,1,opt,name=value,proto3,oneof"`
}

func (*UInt64Metric_Value) isUInt64Metric_OptionalValue() {}

type isUInt64Metric_OptionalUnit interface {
	isUInt64Metric_OptionalUnit()
}

type UInt64Metric_Unit struct {
	// The unit, for example `bytes` or `percent`. Unset when the value has no unit.
	Unit string `protobuf:"bytes,4,opt,name=unit,proto3,oneof"`
}

func (*UInt64Metric_Unit) isUInt64Metric_OptionalUnit() {}

type isUInt64Metric_OptionalMin interface {
	isUInt64Metric_OptionalMin()
}

type UInt64Metric_Min struct {
	// The minimum. Unset when there is no known lower bound.
	Min uint64 `protobuf:"varint,5,opt,name=min,proto3,oneof"`
}

func (*UInt64Metric_Min) isUInt64Metric_OptionalMin() {}

type isUInt64Metric_OptionalMax interface {
	isUInt64Metric_OptionalMax()
}

type UInt64Metric_Max struct {
	// The maximum. Unset when there is no known upper bound.
	Max uint64 `protobuf:"varint,6,opt,name=max,proto3,oneof"`
}

func (*UInt64Metric_Max) isUInt64Metric_OptionalMax() {}

// A metric holding a signed 64-bit integer value.
type Int64Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current value of the metric.
	//
	// Types that are valid to be assigned to OptionalValue:
	//
	//	*Int64Metric_Value
	OptionalValue isInt64Metric_OptionalValue `protobuf_oneof:"optional_value"`
	// Human-readable description of what the metric measures.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Whether the value can only increase or can also decrease.
	Kind Kind `protobuf:"varint,3,opt,name=kind,proto3,enum=nanopinggrpc.metrics.Kind" json:"kind,omitempty"`
	// The unit of the value.
	//
	// Types that are valid to be assigned to OptionalUnit:
	//
	//	*Int64Metric_Unit
	OptionalUnit isInt64Metric_OptionalUnit `protobuf_oneof:"optional_unit"`
	// The lowest value the metric can take.
	//
	// Types that are valid to be assigned to OptionalMin:
	//
	//	*Int64Metric_Min
	OptionalMin isInt64Metric_OptionalMin `protobuf_oneof:"optional_min"`
	// The highest value the metric can take.
	//
	// Types that are valid to be assigned to OptionalMax:
	//
	//	*Int64Metric_Max
	OptionalMax   isInt64Metric_OptionalMax `protobuf_oneof:"optional_max"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64Metric) Reset() {
	*x = Int64Metric{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Metric) ProtoMessage() {}

func (x *Int64Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Metric.ProtoReflect.Descriptor instead.
func (*Int64Metric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Int64Metric) GetOptionalValue() isInt64Metric_OptionalValue {
	if x != nil {
		return x.OptionalValue
	}
	return nil
}

func (x *Int64Metric) GetValue() int64 {
	if x != nil {
		if x, ok := x.OptionalValue.(*Int64Metric_Value); ok {
			return x.Value
		}
	}
	return 0
}

func (x *Int64Metric) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Int64Metric) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_GAUGE
}

func (x *Int64Metric) GetOptionalUnit() isInt64Metric_OptionalUnit {
	if x != nil {
		return x.OptionalUnit
	}
	return nil
}

func (x *Int64Metric) GetUnit() string {
	if x != nil {
		if x, ok := x.OptionalUnit.(*Int64Metric_Unit); ok {
			return x.Unit
		}
	}
	return ""
}

func (x *Int64Metric) GetOptionalMin() isInt64Metric_OptionalMin {
	if x != nil {
		return x.OptionalMin
	}
	return nil
}

func (x *Int64Metric) GetMin() int64 {
	if x != nil {
		if x, ok := x.OptionalMin.(*Int64Metric_Min); ok {
			return x.Min
		}
	}
	return 0
}

func (x *Int64Metric) GetOptionalMax() isInt64Metric_OptionalMax {
	if x != nil {
		return x.OptionalMax
	}
	return nil
}

func (x *Int64Metric) GetMax() int64 {
	if x != nil {
		if x, ok := x.OptionalMax.(*Int64Metric_Max); ok {
			return x.Max
		}
	}
	return 0
}

type isInt64Metric_OptionalValue interface {
	isInt64Metric_OptionalValue()
}

type Int64Metric_Value struct {
	// The value. Unset when the metric has no value in this sample.
	Value int64 `protobuf:"varint,1,opt,name=value,proto3,oneof"`
}

func (*Int64Metric_Value) isInt64Metric_OptionalValue() {}

type isInt64Metric_OptionalUnit interface {
	isInt64Metric_OptionalUnit()
}

type Int64Metric_Unit struct {
	// The unit, for example `bytes` or `percent`. Unset when the value has no unit.
	Unit string `protobuf:"bytes,4,opt,name=unit,proto3,oneof"`
}

func (*Int64Metric_Unit) isInt64Metric_OptionalUnit() {}

type isInt64Metric_OptionalMin interface {
	isInt64Metric_OptionalMin()
}

type Int64Metric_Min struct {
	// The minimum. Unset when there is no known lower bound.
	Min int64 `protobuf:"varint,5,opt,name=min,proto3,oneof"`
}

func (*Int64Metric_Min) isInt64Metric_OptionalMin() {}

type isInt64Metric_OptionalMax interface {
	isInt64Metric_OptionalMax()
}

type Int64Metric_Max struct {
	// The maximum. Unset when there is no known upper bound.
	Max int64 `protobuf:"varint,6,opt,name=max,proto3,oneof"`
}

func (*Int64Metric_Max) isInt64Metric_OptionalMax() {}

// A metric holding an unsigned 32-bit integer value.
type UInt32Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current value of the metric.
	//
	// Types that are valid to be assigned to OptionalValue:
	//
	//	*UInt32Metric_Value
	OptionalValue isUInt32Metric_OptionalValue `protobuf_oneof:"optional_value"`
	// Human-readable description of what the metric measures.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Whether the value can only increase or can also decrease.
	Kind Kind `protobuf:"varint,3,opt,name=kind,proto3,enum=nanopinggrpc.metrics.Kind" json:"kind,omitempty"`
	// The unit of the value.
	//
	// Types that are valid to be assigned to OptionalUnit:
	//
	//	*UInt32Metric_Unit
	OptionalUnit isUInt32Metric_OptionalUnit `protobuf_oneof:"optional_unit"`
	// The lowest value the metric can take.
	//
	// Types that are valid to be assigned to OptionalMin:
	//
	//	*UInt32Metric_Min
	OptionalMin isUInt32Metric_OptionalMin `protobuf_oneof:"optional_min"`
	// The highest value the metric can take.
	//
	// Types that are valid to be assigned to OptionalMax:
	//
	//	*UInt32Metric_Max
	OptionalMax   isUInt32Metric_OptionalMax `protobuf_oneof:"optional_max"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UInt32Metric) Reset() {
	*x = UInt32Metric{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UInt32Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInt32Metric) ProtoMessage() {}

func (x *UInt32Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInt32Metric.ProtoReflect.Descriptor instead.
func (*UInt32Metric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *UInt32Metric) GetOptionalValue() isUInt32Metric_OptionalValue {
	if x != nil {
		return x.OptionalValue
	}
	return nil
}

func (x *UInt32Metric) GetValue() uint32 {
	if x != nil {
		if x, ok := x.OptionalValue.(*UInt32Metric_Value); ok {
			return x.Value
		}
	}
	return 0
}

func (x *UInt32Metric) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UInt32Metric) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_GAUGE
}

func (x *UInt32Metric) GetOptionalUnit() isUInt32Metric_OptionalUnit {
	if x != nil {
		return x.OptionalUnit
	}
	return nil
}

func (x *UInt32Metric) GetUnit() string {
	if x != nil {
		if x, ok := x.OptionalUnit.(*UInt32Metric_Unit); ok {
			return x.Unit
		}
	}
	return ""
}

func (x *UInt32Metric) GetOptionalMin() isUInt32Metric_OptionalMin {
	if x != nil {
		return x.OptionalMin
	}
	return nil
}

func (x *UInt32Metric) GetMin() uint32 {
	if x != nil {
		if x, ok := x.OptionalMin.(*UInt32Metric_Min); ok {
			return x.Min
		}
	}
	return 0
}

func (x *UInt32Metric) GetOptionalMax() isUInt32Metric_OptionalMax {
	if x != nil {
		return x.OptionalMax
	}
	return nil
}

func (x *UInt32Metric) GetMax() uint32 {
	if x != nil {
		if x, ok := x.OptionalMax.(*UInt32Metric_Max); ok {
			return x.Max
		}
	}
	return 0
}

type isUInt32Metric_OptionalValue interface {
	isUInt32Metric_OptionalValue()
}

type UInt32Metric_Value struct {
	// The value. Unset when the metric has no value in this sample.
	Value uint32 `protobuf:"varint,1,opt,name=value,proto3,oneof"`
}

func (*UInt32Metric_Value) isUInt32Metric_OptionalValue() {}

type isUInt32Metric_OptionalUnit interface {
	isUInt32Metric_OptionalUnit()
}

type UInt32Metric_Unit struct {
	// The unit, for example `bytes` or `percent`. Unset when the value has no unit.
	Unit string `protobuf:"bytes,4,opt,name=unit,proto3,oneof"`
}

func (*UInt32Metric_Unit) isUInt32Metric_OptionalUnit() {}

type isUInt32Metric_OptionalMin interface {
	isUInt32Metric_OptionalMin()
}

type UInt32Metric_Min struct {
	// The minimum. Unset when there is no known lower bound.
	Min uint32 `protobuf:"varint,5,opt,name=min,proto3,oneof"`
}

func (*UInt32Metric_Min) isUInt32Metric_OptionalMin() {}

type isUInt32Metric_OptionalMax interface {
	isUInt32Metric_OptionalMax()
}

type UInt32Metric_Max struct {
	// The maximum. Unset when there is no known upper bound.
	Max uint32 `protobuf:"varint,6,opt,name=max,proto3,oneof"`
}

func (*UInt32Metric_Max) isUInt32Metric_OptionalMax() {}

// A metric holding a signed 32-bit integer value.
type Int32Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current value of the metric.
	//
	// Types that are valid to be assigned to OptionalValue:
	//
	//	*Int32Metric_Value
	OptionalValue isInt32Metric_OptionalValue `protobuf_oneof:"optional_value"`
	// Human-readable description of what the metric measures.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Whether the value can only increase or can also decrease.
	Kind Kind `protobuf:"varint,3,opt,name=kind,proto3,enum=nanopinggrpc.metrics.Kind" json:"kind,omitempty"`
	// The unit of the value.
	//
	// Types that are valid to be assigned to OptionalUnit:
	//
	//	*Int32Metric_Unit
	OptionalUnit isInt32Metric_OptionalUnit `protobuf_oneof:"optional_unit"`
	// The lowest value the metric can take.
	//
	// Types that are valid to be assigned to OptionalMin:
	//
	//	*Int32Metric_Min
	OptionalMin isInt32Metric_OptionalMin `protobuf_oneof:"optional_min"`
	// The highest value the metric can take.
	//
	// Types that are valid to be assigned to OptionalMax:
	//
	//	*Int32Metric_Max
	OptionalMax   isInt32Metric_OptionalMax `protobuf_oneof:"optional_max"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32Metric) Reset() {
	*x = Int32Metric{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Metric) ProtoMessage() {}

func (x *Int32Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Metric.ProtoReflect.Descriptor instead.
func (*Int32Metric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *Int32Metric) GetOptionalValue() isInt32Metric_OptionalValue {
	if x != nil {
		return x.OptionalValue
	}
	return nil
}

func (x *Int32Metric) GetValue() int32 {
	if x != nil {
		if x, ok := x.OptionalValue.(*Int32Metric_Value); ok {
			return x.Value
		}
	}
	return 0
}

func (x *Int32Metric) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Int32Metric) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_GAUGE
}

func (x *Int32Metric) GetOptionalUnit() isInt32Metric_OptionalUnit {
	if x != nil {
		return x.OptionalUnit
	}
	return nil
}

func (x *Int32Metric) GetUnit() string {
	if x != nil {
		if x, ok := x.OptionalUnit.(*Int32Metric_Unit); ok {
			return x.Unit
		}
	}
	return ""
}

func (x *Int32Metric) GetOptionalMin() isInt32Metric_OptionalMin {
	if x != nil {
		return x.OptionalMin
	}
	return nil
}

func (x *Int32Metric) GetMin() int32 {
	if x != nil {
		if x, ok := x.OptionalMin.(*Int32Metric_Min); ok {
			return x.Min
		}
	}
	return 0
}

func (x *Int32Metric) GetOptionalMax() isInt32Metric_OptionalMax {
	if x != nil {
		return x.OptionalMax
	}
	return nil
}

func (x *Int32Metric) GetMax() int32 {
	if x != nil {
		if x, ok := x.OptionalMax.(*Int32Metric_Max); ok {
			return x.Max
		}
	}
	return 0
}

type isInt32Metric_OptionalValue interface {
	isInt32Metric_OptionalValue()
}

type Int32Metric_Value struct {
	// The value. Unset when the metric has no value in this sample.
	Value int32 `protobuf:"varint,1,opt,name=value,proto3,oneof"`
}

func (*Int32Metric_Value) isInt32Metric_OptionalValue() {}

type isInt32Metric_OptionalUnit interface {
	isInt32Metric_OptionalUnit()
}

type Int32Metric_Unit struct {
	// The unit, for example `bytes` or `percent`. Unset when the value has no unit.
	Unit string `protobuf:"bytes,4,opt,name=unit,proto3,oneof"`
}

func (*Int32Metric_Unit) isInt32Metric_OptionalUnit() {}

type isInt32Metric_OptionalMin interface {
	isInt32Metric_OptionalMin()
}

type Int32Metric_Min struct {
	// The minimum. Unset when there is no known lower bound.
	Min int32 `protobuf:"varint,5,opt,name=min,proto3,oneof"`
}

func (*Int32Metric_Min) isInt32Metric_OptionalMin() {}

type isInt32Metric_OptionalMax interface {
	isInt32Metric_OptionalMax()
}

type Int32Metric_Max struct {
	// The maximum. Unset when there is no known upper bound.
	Max int32 `protobuf:"varint,6,opt,name=max,proto3,oneof"`
}

func (*Int32Metric_Max) isInt32Metric_OptionalMax() {}

// A metric holding a 64-bit floating-point value.
type Float64Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current value of the metric.
	//
	// Types that are valid to be assigned to OptionalValue:
	//
	//	*Float64Metric_Value
	OptionalValue isFloat64Metric_OptionalValue `protobuf_oneof:"optional_value"`
	// Human-readable description of what the metric measures.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Whether the value can only increase or can also decrease.
	Kind Kind `protobuf:"varint,3,opt,name=kind,proto3,enum=nanopinggrpc.metrics.Kind" json:"kind,omitempty"`
	// The unit of the value.
	//
	// Types that are valid to be assigned to OptionalUnit:
	//
	//	*Float64Metric_Unit
	OptionalUnit isFloat64Metric_OptionalUnit `protobuf_oneof:"optional_unit"`
	// The lowest value the metric can take.
	//
	// Types that are valid to be assigned to OptionalMin:
	//
	//	*Float64Metric_Min
	OptionalMin isFloat64Metric_OptionalMin `protobuf_oneof:"optional_min"`
	// The highest value the metric can take.
	//
	// Types that are valid to be assigned to OptionalMax:
	//
	//	*Float64Metric_Max
	OptionalMax   isFloat64Metric_OptionalMax `protobuf_oneof:"optional_max"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Float64Metric) Reset() {
	*x = Float64Metric{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Float64Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float64Metric) ProtoMessage() {}

func (x *Float64Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float64Metric.ProtoReflect.Descriptor instead.
func (*Float64Metric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *Float64Metric) GetOptionalValue() isFloat64Metric_OptionalValue {
	if x != nil {
		return x.OptionalValue
	}
	return nil
}

func (x *Float64Metric) GetValue() float64 {
	if x != nil {
		if x, ok := x.OptionalValue.(*Float64Metric_Value); ok {
			return x.Value
		}
	}
	return 0
}

func (x *Float64Metric) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Float64Metric) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_GAUGE
}

func (x *Float64Metric) GetOptionalUnit() isFloat64Metric_OptionalUnit {
	if x != nil {
		return x.OptionalUnit
	}
	return nil
}

func (x *Float64Metric) GetUnit() string {
	if x != nil {
		if x, ok := x.OptionalUnit.(*Float64Metric_Unit); ok {
			return x.Unit
		}
	}
	return ""
}

func (x *Float64Metric) GetOptionalMin() isFloat64Metric_OptionalMin {
	if x != nil {
		return x.OptionalMin
	}
	return nil
}

func (x *Float64Metric) GetMin() float64 {
	if x != nil {
		if x, ok := x.OptionalMin.(*Float64Metric_Min); ok {
			return x.Min
		}
	}
	return 0
}

func (x *Float64Metric) GetOptionalMax() isFloat64Metric_OptionalMax {
	if x != nil {
		return x.OptionalMax
	}
	return nil
}

func (x *Float64Metric) GetMax() float64 {
	if x != nil {
		if x, ok := x.OptionalMax.(*Float64Metric_Max); ok {
			return x.Max
		}
	}
	return 0
}

type isFloat64Metric_OptionalValue interface {
	isFloat64Metric_OptionalValue()
}

type Float64Metric_Value struct {
	// The value. Unset when the metric has no value in this sample.
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3,oneof"`
}

func (*Float64Metric_Value) isFloat64Metric_OptionalValue() {}

type isFloat64Metric_OptionalUnit interface {
	isFloat64Metric_OptionalUnit()
}

type Float64Metric_Unit struct {
	// The unit, for example `bytes` or `percent`. Unset when the value has no unit.
	Unit string `protobuf:"bytes,4,opt,name=unit,proto3,oneof"`
}

func (*Float64Metric_Unit) isFloat64Metric_OptionalUnit() {}

type isFloat64Metric_OptionalMin interface {
	isFloat64Metric_OptionalMin()
}

type Float64Metric_Min struct {
	// The minimum. Unset when there is no known lower bound.
	Min float64 `protobuf:"fixed64,5,opt,name=min,proto3,oneof"`
}

func (*Float64Metric_Min) isFloat64Metric_OptionalMin() {}

type isFloat64Metric_OptionalMax interface {
	isFloat64Metric_OptionalMax()
}

type Float64Metric_Max struct {
	// The maximum. Unset when there is no known upper bound.
	Max float64 `protobuf:"fixed64,6,opt,name=max,proto3,oneof"`
}

func (*Float64Metric_Max) isFloat64Metric_OptionalMax() {}

// A metric holding a 32-bit floating-point value.
type Float32Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current value of the metric.
	//
	// Types that are valid to be assigned to OptionalValue:
	//
	//	*Float32Metric_Value
	OptionalValue isFloat32Metric_OptionalValue `protobuf_oneof:"optional_value"`
	// Human-readable description of what the metric measures.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Whether the value can only increase or can also decrease.
	Kind Kind `protobuf:"varint,3,opt,name=kind,proto3,enum=nanopinggrpc.metrics.Kind" json:"kind,omitempty"`
	// The unit of the value.
	//
	// Types that are valid to be assigned to OptionalUnit:
	//
	//	*Float32Metric_Unit
	OptionalUnit isFloat32Metric_OptionalUnit `protobuf_oneof:"optional_unit"`
	// The lowest value the metric can take.
	//
	// Types that are valid to be assigned to OptionalMin:
	//
	//	*Float32Metric_Min
	OptionalMin isFloat32Metric_OptionalMin `protobuf_oneof:"optional_min"`
	// The highest value the metric can take.
	//
	// Types that are valid to be assigned to OptionalMax:
	//
	//	*Float32Metric_Max
	OptionalMax   isFloat32Metric_OptionalMax `protobuf_oneof:"optional_max"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Float32Metric) Reset() {
	*x = Float32Metric{}
	mi := &file_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Float32Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float32Metric) ProtoMessage() {}

func (x *Float32Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float32Metric.ProtoReflect.Descriptor instead.
func (*Float32Metric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *Float32Metric) GetOptionalValue() isFloat32Metric_OptionalValue {
	if x != nil {
		return x.OptionalValue
	}
	return nil
}

func (x *Float32Metric) GetValue() float32 {
	if x != nil {
		if x, ok := x.OptionalValue.(*Float32Metric_Value); ok {
			return x.Value
		}
	}
	return 0
}

func (x *Float32Metric) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Float32Metric) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_GAUGE
}

func (x *Float32Metric) GetOptionalUnit() isFloat32Metric_OptionalUnit {
	if x != nil {
		return x.OptionalUnit
	}
	return nil
}

func (x *Float32Metric) GetUnit() string {
	if x != nil {
		if x, ok := x.OptionalUnit.(*Float32Metric_Unit); ok {
			return x.Unit
		}
	}
	return ""
}

func (x *Float32Metric) GetOptionalMin() isFloat32Metric_OptionalMin {
	if x != nil {
		return x.OptionalMin
	}
	return nil
}

func (x *Float32Metric) GetMin() float32 {
	if x != nil {
		if x, ok := x.OptionalMin.(*Float32Metric_Min); ok {
			return x.Min
		}
	}
	return 0
}

func (x *Float32Metric) GetOptionalMax() isFloat32Metric_OptionalMax {
	if x != nil {
		return x.OptionalMax
	}
	return nil
}

func (x *Float32Metric) GetMax() float32 {
	if x != nil {
		if x, ok := x.OptionalMax.(*Float32Metric_Max); ok {
			return x.Max
		}
	}
	return 0
}

type isFloat32Metric_OptionalValue interface {
	isFloat32Metric_OptionalValue()
}

type Float32Metric_Value struct {
	// The value. Unset when the metric has no value in this sample.
	Value float32 `protobuf:"fixed32,1,opt,name=value,proto3,oneof"`
}

func (*Float32Metric_Value) isFloat32Metric_OptionalValue() {}

type isFloat32Metric_OptionalUnit interface {
	isFloat32Metric_OptionalUnit()
}

type Float32Metric_Unit struct {
	// The unit, for example `bytes` or `percent`. Unset when the value has no unit.
	Unit string `protobuf:"bytes,4,opt,name=unit,proto3,oneof"`
}

func (*Float32Metric_Unit) isFloat32Metric_OptionalUnit() {}

type isFloat32Metric_OptionalMin interface {
	isFloat32Metric_OptionalMin()
}

type Float32Metric_Min struct {
	// The minimum. Unset when there is no known lower bound.
	Min float32 `protobuf:"fixed32,5,opt,name=min,proto3,oneof"`
}

func (*Float32Metric_Min) isFloat32Metric_OptionalMin() {}

type isFloat32Metric_OptionalMax interface {
	isFloat32Metric_OptionalMax()
}

type Float32Metric_Max struct {
	// The maximum. Unset when there is no known upper bound.
	Max float32 `protobuf:"fixed32,6,opt,name=max,proto3,oneof"`
}

func (*Float32Metric_Max) isFloat32Metric_OptionalMax() {}

// A metric holding a true or false value.
type BoolMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current value of the metric.
	//
	// Types that are valid to be assigned to OptionalValue:
	//
	//	*BoolMetric_Value
	OptionalValue isBoolMetric_OptionalValue `protobuf_oneof:"optional_value"`
	// Human-readable description of what the metric measures.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The unit of the value.
	//
	// Types that are valid to be assigned to OptionalUnit:
	//
	//	*BoolMetric_Unit
	OptionalUnit  isBoolMetric_OptionalUnit `protobuf_oneof:"optional_unit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolMetric) Reset() {
	*x = BoolMetric{}
	mi := &file_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolMetric) ProtoMessage() {}

func (x *BoolMetric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolMetric.ProtoReflect.Descriptor instead.
func (*BoolMetric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *BoolMetric) GetOptionalValue() isBoolMetric_OptionalValue {
	if x != nil {
		return x.OptionalValue
	}
	return nil
}

func (x *BoolMetric) GetValue() bool {
	if x != nil {
		if x, ok := x.OptionalValue.(*BoolMetric_Value); ok {
			return x.Value
		}
	}
	return false
}

func (x *BoolMetric) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BoolMetric) GetOptionalUnit() isBoolMetric_OptionalUnit {
	if x != nil {
		return x.OptionalUnit
	}
	return nil
}

func (x *BoolMetric) GetUnit() string {
	if x != nil {
		if x, ok := x.OptionalUnit.(*BoolMetric_Unit); ok {
			return x.Unit
		}
	}
	return ""
}

type isBoolMetric_OptionalValue interface {
	isBoolMetric_OptionalValue()
}

type BoolMetric_Value struct {
	// The value. Unset when the metric has no value in this sample.
	Value bool `protobuf:"varint,1,opt,name=value,proto3,oneof"`
}

func (*BoolMetric_Value) isBoolMetric_OptionalValue() {}

type isBoolMetric_OptionalUnit interface {
	isBoolMetric_OptionalUnit()
}

type BoolMetric_Unit struct {
	// The unit. Unset when the value has no unit.
	Unit string `protobuf:"bytes,3,opt,name=unit,proto3,oneof"`
}

func (*BoolMetric_Unit) isBoolMetric_OptionalUnit() {}

// A metric holding one value out of a fixed set of named values.
type Enum8Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current value of the metric, as an index into `values`.
	//
	// Types that are valid to be assigned to OptionalValue:
	//
	//	*Enum8Metric_Value
	OptionalValue isEnum8Metric_OptionalValue `protobuf_oneof:"optional_value"`
	// Human-readable description of what the metric measures.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The values the metric can take, keyed by index.
	Values map[uint32]*Enum8Metric_EnumValue `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The unit of the value.
	//
	// Types that are valid to be assigned to OptionalUnit:
	//
	//	*Enum8Metric_Unit
	OptionalUnit  isEnum8Metric_OptionalUnit `protobuf_oneof:"optional_unit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enum8Metric) Reset() {
	*x = Enum8Metric{}
	mi := &file_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enum8Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum8Metric) ProtoMessage() {}

func (x *Enum8Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum8Metric.ProtoReflect.Descriptor instead.
func (*Enum8Metric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *Enum8Metric) GetOptionalValue() isEnum8Metric_OptionalValue {
	if x != nil {
		return x.OptionalValue
	}
	return nil
}

func (x *Enum8Metric) GetValue() uint32 {
	if x != nil {
		if x, ok := x.OptionalValue.(*Enum8Metric_Value); ok {
			return x.Value
		}
	}
	return 0
}

func (x *Enum8Metric) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Enum8Metric) GetValues() map[uint32]*Enum8Metric_EnumValue {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Enum8Metric) GetOptionalUnit() isEnum8Metric_OptionalUnit {
	if x != nil {
		return x.OptionalUnit
	}
	return nil
}

func (x *Enum8Metric) GetUnit() string {
	if x != nil {
		if x, ok := x.OptionalUnit.(*Enum8Metric_Unit); ok {
			return x.Unit
		}
	}
	return ""
}

type isEnum8Metric_OptionalValue interface {
	isEnum8Metric_OptionalValue()
}

type Enum8Metric_Value struct {
	// The index. Unset when the metric has no value in this sample.
	Value uint32 `protobuf:"varint,1,opt,name=value,proto3,oneof"`
}

func (*Enum8Metric_Value) isEnum8Metric_OptionalValue() {}

type isEnum8Metric_OptionalUnit interface {
	isEnum8Metric_OptionalUnit()
}

type Enum8Metric_Unit struct {
	// The unit. Unset when the value has no unit.
	Unit string `protobuf:"bytes,5,opt,name=unit,proto3,oneof"`
}

func (*Enum8Metric_Unit) isEnum8Metric_OptionalUnit() {}

// A metric whose value never changes, such as the CPU architecture.
type Constant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fixed value. Exactly one is set, depending on its type.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Constant_Uint64
	//	*Constant_Int64
	//	*Constant_Float64
	//	*Constant_Boolean
	//	*Constant_String_
	Value isConstant_Value `protobuf_oneof:"value"`
	// Human-readable description of what the constant describes.
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// The unit of the value.
	//
	// Types that are valid to be assigned to OptionalUnit:
	//
	//	*Constant_Unit
	OptionalUnit  isConstant_OptionalUnit `protobuf_oneof:"optional_unit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constant) Reset() {
	*x = Constant{}
	mi := &file_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constant) ProtoMessage() {}

func (x *Constant) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constant.ProtoReflect.Descriptor instead.
func (*Constant) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *Constant) GetValue() isConstant_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Constant) GetUint64() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Constant_Uint64); ok {
			return x.Uint64
		}
	}
	return 0
}

func (x *Constant) GetInt64() int64 {
	if x != nil {
		if x, ok := x.Value.(*Constant_Int64); ok {
			return x.Int64
		}
	}
	return 0
}

func (x *Constant) GetFloat64() float64 {
	if x != nil {
		if x, ok := x.Value.(*Constant_Float64); ok {
			return x.Float64
		}
	}
	return 0
}

func (x *Constant) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Value.(*Constant_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

func (x *Constant) GetString_() string {
	if x != nil {
		if x, ok := x.Value.(*Constant_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *Constant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Constant) GetOptionalUnit() isConstant_OptionalUnit {
	if x != nil {
		return x.OptionalUnit
	}
	return nil
}

func (x *Constant) GetUnit() string {
	if x != nil {
		if x, ok := x.OptionalUnit.(*Constant_Unit); ok {
			return x.Unit
		}
	}
	return ""
}

type isConstant_Value interface {
	isConstant_Value()
}

type Constant_Uint64 struct {
	// An unsigned integer value.
	Uint64 uint64 `protobuf:"varint,1,opt,name=uint64,proto3,oneof"`
}

type Constant_Int64 struct {
	// A signed integer value.
	Int64 int64 `protobuf:"varint,2,opt,name=int64,proto3,oneof"`
}

type Constant_Float64 struct {
	// A floating-point value.
	Float64 float64 `protobuf:"fixed64,3,opt,name=float64,proto3,oneof"`
}

type Constant_Boolean struct {
	// A true or false value.
	Boolean bool `protobuf:"varint,4,opt,name=boolean,proto3,oneof"`
}

type Constant_String_ struct {
	// A text value.
	String_ string `protobuf:"bytes,5,opt,name=string,proto3,oneof"`
}

func (*Constant_Uint64) isConstant_Value() {}

func (*Constant_Int64) isConstant_Value() {}

func (*Constant_Float64) isConstant_Value() {}

func (*Constant_Boolean) isConstant_Value() {}

func (*Constant_String_) isConstant_Value() {}

type isConstant_OptionalUnit interface {
	isConstant_OptionalUnit()
}

type Constant_Unit struct {
	// The unit. Unset when the value has no unit.
	Unit string `protobuf:"bytes,7,opt,name=unit,proto3,oneof"`
}

func (*Constant_Unit) isConstant_OptionalUnit() {}

// A single metric. Exactly one of the fields is set, depending on the metric's type.
type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The metric, by type.
	//
	// Types that are valid to be assigned to Type:
	//
	//	*Metric_Constant
	//	*Metric_Uint64
	//	*Metric_Int64
	//	*Metric_Uint32
	//	*Metric_Int32
	//	*Metric_Float64
	//	*Metric_Float32
	//	*Metric_Boolean
	//	*Metric_Enum8
	Type          isMetric_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *Metric) GetType() isMetric_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Metric) GetConstant() *Constant {
	if x != nil {
		if x, ok := x.Type.(*Metric_Constant); ok {
			return x.Constant
		}
	}
	return nil
}

func (x *Metric) GetUint64() *UInt64Metric {
	if x != nil {
		if x, ok := x.Type.(*Metric_Uint64); ok {
			return x.Uint64
		}
	}
	return nil
}

func (x *Metric) GetInt64() *Int64Metric {
	if x != nil {
		if x, ok := x.Type.(*Metric_Int64); ok {
			return x.Int64
		}
	}
	return nil
}

func (x *Metric) GetUint32() *UInt32Metric {
	if x != nil {
		if x, ok := x.Type.(*Metric_Uint32); ok {
			return x.Uint32
		}
	}
	return nil
}

func (x *Metric) GetInt32() *Int32Metric {
	if x != nil {
		if x, ok := x.Type.(*Metric_Int32); ok {
			return x.Int32
		}
	}
	return nil
}

func (x *Metric) GetFloat64() *Float64Metric {
	if x != nil {
		if x, ok := x.Type.(*Metric_Float64); ok {
			return x.Float64
		}
	}
	return nil
}

func (x *Metric) GetFloat32() *Float32Metric {
	if x != nil {
		if x, ok := x.Type.(*Metric_Float32); ok {
			return x.Float32
		}
	}
	return nil
}

func (x *Metric) GetBoolean() *BoolMetric {
	if x != nil {
		if x, ok := x.Type.(*Metric_Boolean); ok {
			return x.Boolean
		}
	}
	return nil
}

func (x *Metric) GetEnum8() *Enum8Metric {
	if x != nil {
		if x, ok := x.Type.(*Metric_Enum8); ok {
			return x.Enum8
		}
	}
	return nil
}

type isMetric_Type interface {
	isMetric_Type()
}

type Metric_Constant struct {
	// A metric with a fixed value.
	Constant *Constant `protobuf:"bytes,1,opt,name=constant,proto3,oneof"`
}

type Metric_Uint64 struct {
	// An unsigned 64-bit integer metric.
	Uint64 *UInt64Metric `protobuf:"bytes,2,opt,name=uint64,proto3,oneof"`
}

type Metric_Int64 struct {
	// A signed 64-bit integer metric.
	Int64 *Int64Metric `protobuf:"bytes,3,opt,name=int64,proto3,oneof"`
}

type Metric_Uint32 struct {
	// An unsigned 32-bit integer metric.
	Uint32 *UInt32Metric `protobuf:"bytes,4,opt,name=uint32,proto3,oneof"`
}

type Metric_Int32 struct {
	// A signed 32-bit integer metric.
	Int32 *Int32Metric `protobuf:"bytes,5,opt,name=int32,proto3,oneof"`
}

type Metric_Float64 struct {
	// A 64-bit floating-point metric.
	Float64 *Float64Metric `protobuf:"bytes,6,opt,name=float64,proto3,oneof"`
}

type Metric_Float32 struct {
	// A 32-bit floating-point metric.
	Float32 *Float32Metric `protobuf:"bytes,7,opt,name=float32,proto3,oneof"`
}

type Metric_Boolean struct {
	// A true or false metric.
	Boolean *BoolMetric `protobuf:"bytes,8,opt,name=boolean,proto3,oneof"`
}

type Metric_Enum8 struct {
	// A metric with one of a fixed set of named values.
	Enum8 *Enum8Metric `protobuf:"bytes,9,opt,name=enum8,proto3,oneof"`
}

func (*Metric_Constant) isMetric_Type() {}

func (*Metric_Uint64) isMetric_Type() {}

func (*Metric_Int64) isMetric_Type() {}

func (*Metric_Uint32) isMetric_Type() {}

func (*Metric_Int32) isMetric_Type() {}

func (*Metric_Float64) isMetric_Type() {}

func (*Metric_Float32) isMetric_Type() {}

func (*Metric_Boolean) isMetric_Type() {}

func (*Metric_Enum8) isMetric_Type() {}

// A group of related metrics, such as the memory metrics of a node.
type Collection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path identifying the collection, for example `/system/memory`.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The metrics in the collection, keyed by metric name.
	Metrics       map[string]*Metric `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *Collection) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Collection) GetMetrics() map[string]*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// A named value the metric can take.
type Enum8Metric_EnumValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the value.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional description of the value.
	//
	// Types that are valid to be assigned to OptionalDescription:
	//
	//	*Enum8Metric_EnumValue_Description
	OptionalDescription isEnum8Metric_EnumValue_OptionalDescription `protobuf_oneof:"optional_description"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Enum8Metric_EnumValue) Reset() {
	*x = Enum8Metric_EnumValue{}
	mi := &file_metrics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enum8Metric_EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum8Metric_EnumValue) ProtoMessage() {}

func (x *Enum8Metric_EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum8Metric_EnumValue.ProtoReflect.Descriptor instead.
func (*Enum8Metric_EnumValue) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Enum8Metric_EnumValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enum8Metric_EnumValue) GetOptionalDescription() isEnum8Metric_EnumValue_OptionalDescription {
	if x != nil {
		return x.OptionalDescription
	}
	return nil
}

func (x *Enum8Metric_EnumValue) GetDescription() string {
	if x != nil {
		if x, ok := x.OptionalDescription.(*Enum8Metric_EnumValue_Description); ok {
			return x.Description
		}
	}
	return ""
}

type isEnum8Metric_EnumValue_OptionalDescription interface {
	isEnum8Metric_EnumValue_OptionalDescription()
}

type Enum8Metric_EnumValue_Description struct {
	// The description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3,oneof"`
}

func (*Enum8Metric_EnumValue_Description) isEnum8Metric_EnumValue_OptionalDescription() {}

var File_metrics_proto protoreflect.FileDescriptor

var file_metrics_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x14, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0xf9, 0x01, 0x0a, 0x0c, 0x55, 0x49, 0x6e, 0x74, 0x36, 0x34,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2e, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a,
	0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x12, 0x14, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x48, 0x02, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x03, 0x6d, 0x61,
	0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x48, 0x03, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x42, 0x10,
	0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x42, 0x0f, 0x0a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x6e, 0x69,
	0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x69,
	0x6e, 0x42, 0x0e, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x61,
	0x78, 0x22, 0xf8, 0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6e, 0x61, 0x6e, 0x6f,
	0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x75,
	0x6e, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x75, 0x6e, 0x69,
	0x74, 0x12, 0x12, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x02,
	0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x03, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x42, 0x10, 0x0a, 0x0e, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x42, 0x0e, 0x0a, 0x0c,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x69, 0x6e, 0x42, 0x0e, 0x0a, 0x0c,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x78, 0x22, 0xf9, 0x01, 0x0a,
	0x0c, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x16, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x4b, 0x69, 0x6e,
	0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x0a,
	0x03, 0x6d, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x02, 0x52, 0x03, 0x6d, 0x69,
	0x6e, 0x12, 0x12, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x03,
	0x52, 0x03, 0x6d, 0x61, 0x78, 0x42, 0x10, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x69, 0x6e, 0x42, 0x0e, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x78, 0x22, 0xf8, 0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x74,
	0x33, 0x32, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1a, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x02, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x03,
	0x6d, 0x61, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x48, 0x03, 0x52, 0x03, 0x6d, 0x61, 0x78,
	0x42, 0x10, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x75,
	0x6e, 0x69, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f,
	0x6d, 0x69, 0x6e, 0x42, 0x0e, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f,
	0x6d, 0x61, 0x78, 0x22, 0xfa, 0x01, 0x0a, 0x0d, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2e, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e,
	0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x14, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x48, 0x02, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x03, 0x6d, 0x61, 0x78,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x48, 0x03, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x42, 0x10, 0x0a,
	0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42,
	0x0f, 0x0a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x6e, 0x69, 0x74,
	0x42, 0x0e, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x69, 0x6e,
	0x42, 0x0e, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x78,
	0x22, 0xfa, 0x01, 0x0a, 0x0d, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6e, 0x61, 0x6e,
	0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x04,
	0x75, 0x6e, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x48,
	0x02, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x03, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x42, 0x10, 0x0a, 0x0e, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0f, 0x0a, 0x0d,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x42, 0x0e, 0x0a,
	0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x69, 0x6e, 0x42, 0x0e, 0x0a,
	0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x78, 0x22, 0x7f, 0x0a,
	0x0a, 0x42, 0x6f, 0x6f, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x42, 0x10, 0x0a, 0x0e, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0f, 0x0a,
	0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x22, 0x8c,
	0x03, 0x0a, 0x0b, 0x45, 0x6e, 0x75, 0x6d, 0x38, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x16,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70,
	0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e,
	0x45, 0x6e, 0x75, 0x6d, 0x38, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12,
	0x14, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x04, 0x75, 0x6e, 0x69, 0x74, 0x1a, 0x5b, 0x0a, 0x09, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x16, 0x0a, 0x14, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x66, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x41, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x38, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0f, 0x0a, 0x0d,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x22, 0xe0, 0x01,
	0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x75, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x06, 0x75, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x12, 0x16, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x1a, 0x0a, 0x07,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52,
	0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x12, 0x1a, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6c,
	0x65, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x62, 0x6f, 0x6f,
	0x6c, 0x65, 0x61, 0x6e, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42,
	0x0f, 0x0a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x6e, 0x69, 0x74,
	0x22, 0xbb, 0x04, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x3c, 0x0a, 0x08, 0x63,
	0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x06, 0x75, 0x69, 0x6e,
	0x74, 0x36, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x61, 0x6e, 0x6f,
	0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x2e, 0x55, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x48, 0x00, 0x52,
	0x06, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x39, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e,
	0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x74,
	0x36, 0x34, 0x12, 0x3c, 0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x48, 0x00, 0x52, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x12, 0x39, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x3f, 0x0a, 0x07, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6e,
	0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x48, 0x00, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x12, 0x3f, 0x0a, 0x07,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x48, 0x00, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x12, 0x3c, 0x0a,
	0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x48, 0x00, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x12, 0x39, 0x0a, 0x05, 0x65,
	0x6e, 0x75, 0x6d, 0x38, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6e, 0x61, 0x6e,
	0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x38, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x6e, 0x75, 0x6d, 0x38, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xc3,
	0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x12, 0x47, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x58, 0x0a, 0x0c, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6e, 0x61,
	0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x2a, 0x1e, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x09, 0x0a, 0x05,
	0x47, 0x41, 0x55, 0x47, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x55, 0x4e, 0x54,
	0x45, 0x52, 0x10, 0x01, 0x42, 0x17, 0x5a, 0x15, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x69, 0x6e, 0x67,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_metrics_proto_goTypes = []any{
	(Kind)(0),                     // 0: nanopinggrpc.metrics.Kind
	(*UInt64Metric)(nil),          // 1: nanopinggrpc.metrics.UInt64Metric
	(*Int64Metric)(nil),           // 2: nanopinggrpc.metrics.Int64Metric
	(*UInt32Metric)(nil),          // 3: nanopinggrpc.metrics.UInt32Metric
	(*Int32Metric)(nil),           // 4: nanopinggrpc.metrics.Int32Metric
	(*Float64Metric)(nil),         // 5: nanopinggrpc.metrics.Float64Metric
	(*Float32Metric)(nil),         // 6: nanopinggrpc.metrics.Float32Metric
	(*BoolMetric)(nil),            // 7: nanopinggrpc.metrics.BoolMetric
	(*Enum8Metric)(nil),           // 8: nanopinggrpc.metrics.Enum8Metric
	(*Constant)(nil),              // 9: nanopinggrpc.metrics.Constant
	(*Metric)(nil),                // 10: nanopinggrpc.metrics.Metric
	(*Collection)(nil),            // 11: nanopinggrpc.metrics.Collection
	(*Enum8Metric_EnumValue)(nil), // 12: nanopinggrpc.metrics.Enum8Metric.EnumValue
	nil,                           // 13: nanopinggrpc.metrics.Enum8Metric.ValuesEntry
	nil,                           // 14: nanopinggrpc.metrics.Collection.MetricsEntry
}
var file_metrics_proto_depIdxs = []int32{
	0,  // 0: nanopinggrpc.metrics.UInt64Metric.kind:type_name -> nanopinggrpc.metrics.Kind
	0,  // 1: nanopinggrpc.metrics.Int64Metric.kind:type_name -> nanopinggrpc.metrics.Kind
	0,  // 2: nanopinggrpc.metrics.UInt32Metric.kind:type_name -> nanopinggrpc.metrics.Kind
	0,  // 3: nanopinggrpc.metrics.Int32Metric.kind:type_name -> nanopinggrpc.metrics.Kind
	0,  // 4: nanopinggrpc.metrics.Float64Metric.kind:type_name -> nanopinggrpc.metrics.Kind
	0,  // 5: nanopinggrpc.metrics.Float32Metric.kind:type_name -> nanopinggrpc.metrics.Kind
	13, // 6: nanopinggrpc.metrics.Enum8Metric.values:type_name -> nanopinggrpc.metrics.Enum8Metric.ValuesEntry
	9,  // 7: nanopinggrpc.metrics.Metric.constant:type_name -> nanopinggrpc.metrics.Constant
	1,  // 8: nanopinggrpc.metrics.Metric.uint64:type_name -> nanopinggrpc.metrics.UInt64Metric
	2,  // 9: nanopinggrpc.metrics.Metric.int64:type_name -> nanopinggrpc.metrics.Int64Metric
	3,  // 10: nanopinggrpc.metrics.Metric.uint32:type_name -> nanopinggrpc.metrics.UInt32Metric
	4,  // 11: nanopinggrpc.metrics.Metric.int32:type_name -> nanopinggrpc.metrics.Int32Metric
	5,  // 12: nanopinggrpc.metrics.Metric.float64:type_name -> nanopinggrpc.metrics.Float64Metric
	6,  // 13: nanopinggrpc.metrics.Metric.float32:type_name -> nanopinggrpc.metrics.Float32Metric
	7,  // 14: nanopinggrpc.metrics.Metric.boolean:type_name -> nanopinggrpc.metrics.BoolMetric
	8,  // 15: nanopinggrpc.metrics.Metric.enum8:type_name -> nanopinggrpc.metrics.Enum8Metric
	14, // 16: nanopinggrpc.metrics.Collection.metrics:type_name -> nanopinggrpc.metrics.Collection.MetricsEntry
	12, // 17: nanopinggrpc.metrics.Enum8Metric.ValuesEntry.value:type_name -> nanopinggrpc.metrics.Enum8Metric.EnumValue
	10, // 18: nanopinggrpc.metrics.Collection.MetricsEntry.value:type_name -> nanopinggrpc.metrics.Metric
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	file_metrics_proto_msgTypes[0].OneofWrappers = []any{
		(*UInt64Metric_Value)(nil),
		(*UInt64Metric_Unit)(nil),
		(*UInt64Metric_Min)(nil),
		(*UInt64Metric_Max)(nil),
	}
	file_metrics_proto_msgTypes[1].OneofWrappers = []any{
		(*Int64Metric_Value)(nil),
		(*Int64Metric_Unit)(nil),
		(*Int64Metric_Min)(nil),
		(*Int64Metric_Max)(nil),
	}
	file_metrics_proto_msgTypes[2].OneofWrappers = []any{
		(*UInt32Metric_Value)(nil),
		(*UInt32Metric_Unit)(nil),
		(*UInt32Metric_Min)(nil),
		(*UInt32Metric_Max)(nil),
	}
	file_metrics_proto_msgTypes[3].OneofWrappers = []any{
		(*Int32Metric_Value)(nil),
		(*Int32Metric_Unit)(nil),
		(*Int32Metric_Min)(nil),
		(*Int32Metric_Max)(nil),
	}
	file_metrics_proto_msgTypes[4].OneofWrappers = []any{
		(*Float64Metric_Value)(nil),
		(*Float64Metric_Unit)(nil),
		(*Float64Metric_Min)(nil),
		(*Float64Metric_Max)(nil),
	}
	file_metrics_proto_msgTypes[5].OneofWrappers = []any{
		(*Float32Metric_Value)(nil),
		(*Float32Metric_Unit)(nil),
		(*Float32Metric_Min)(nil),
		(*Float32Metric_Max)(nil),
	}
	file_metrics_proto_msgTypes[6].OneofWrappers = []any{
		(*BoolMetric_Value)(nil),
		(*BoolMetric_Unit)(nil),
	}
	file_metrics_proto_msgTypes[7].OneofWrappers = []any{
		(*Enum8Metric_Value)(nil),
		(*Enum8Metric_Unit)(nil),
	}
	file_metrics_proto_msgTypes[8].OneofWrappers = []any{
		(*Constant_Uint64)(nil),
		(*Constant_Int64)(nil),
		(*Constant_Float64)(nil),
		(*Constant_Boolean)(nil),
		(*Constant_String_)(nil),
		(*Constant_Unit)(nil),
	}
	file_metrics_proto_msgTypes[9].OneofWrappers = []any{
		(*Metric_Constant)(nil),
		(*Metric_Uint64)(nil),
		(*Metric_Int64)(nil),
		(*Metric_Uint32)(nil),
		(*Metric_Int32)(nil),
		(*Metric_Float64)(nil),
		(*Metric_Float32)(nil),
		(*Metric_Boolean)(nil),
		(*Metric_Enum8)(nil),
	}
	file_metrics_proto_msgTypes[11].OneofWrappers = []any{
		(*Enum8Metric_EnumValue_Description)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		EnumInfos:         file_metrics_proto_enumTypes,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
